export const matTranNhapXuatKho = {
  noViewPermission: 'Bạn không có quyền xem danh sách phiếu nhập xuất kho.',
  deleteTitle: 'Xóa phiếu nhập/xuất?',
  deleteMessage: 'Phiếu và toàn bộ chi tiết hàng hóa sẽ bị xóa. Tồn kho sẽ thay đổi tương ứng.',
  bulkDeleteTitle: 'Xóa nhiều phiếu?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} phiếu (kèm chi tiết hàng hóa). Tồn kho sẽ thay đổi tương ứng.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'phieu-nhap-xuat-kho',
  exportFileNameCt: 'chi-tiet-nhap-xuat-kho',
  toast: {
    create: 'Đã lập phiếu.',
    update: 'Đã cập nhật phiếu.',
    delete: 'Đã xóa {{count}} phiếu.',
  },
  service: {
    notFound: 'Không tìm thấy phiếu.',
    chiTietRong: 'Phiếu phải có ít nhất 1 dòng chi tiết.',
    /** Mặc định khi parse lỗi PG `TON_KHO_KHONG_DU:` từ trigger. */
    tonKhoKhongDu: 'Tồn kho không đủ để xuất. Vui lòng kiểm tra lại số lượng.',
  },
  validation: {
    ngayPhieuRequired: 'Chọn ngày lập phiếu.',
    khoXuatRequired: 'Chọn kho xuất.',
    khoNhapRequired: 'Chọn kho nhập.',
    donViCuuTroRequired: 'Chọn đơn vị cứu trợ.',
    dotCuuTroRequired: 'Chọn đợt cứu trợ.',
    khoXuatNhapKhacNhau: 'Kho nhập phải khác kho xuất.',
    chiTietMin: 'Phiếu cần ít nhất 1 dòng chi tiết hàng hóa.',
    soLuongInvalid: 'Số lượng phải là số dương.',
    donGiaInvalid: 'Đơn giá phải là số không âm.',
    hangHoaRequired: 'Chọn hàng hóa.',
  },
  store: {
    ttCol: 'TT',
    soPhieuCol: 'Số phiếu',
    loaiPhieuCol: 'Loại phiếu',
    ngayPhieuCol: 'Ngày phiếu',
    khoXuatCol: 'Kho xuất',
    khoNhapCol: 'Kho nhập',
    donViCuuTroCol: 'Đơn vị cứu trợ',
    dotCuuTroCol: 'Đợt cứu trợ',
    soDongCol: 'Số dòng',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
    /** Tab Chi tiết (flat lines). */
    hangHoaCol: 'Hàng hoá',
    donViTinhCol: 'ĐVT',
    soLuongCol: 'Số lượng',
    donGiaCol: 'Đơn giá',
    thanhTienCol: 'Thành tiền',
    ghiChuCol: 'Ghi chú',
  },
  loaiPhieu: {
    nhap_ngoai: 'Nhập từ ngoài',
    xuat_ngoai: 'Xuất ra ngoài',
    chuyen_kho: 'Chuyển kho',
    all: 'Tất cả loại phiếu',
  },
  toolbar: {
    titleList: 'Phiếu nhập xuất',
    titleCt: 'Chi tiết hàng hoá',
    filterLoaiPhieu: 'Loại phiếu',
    filterKho: 'Kho',
    filterHangHoa: 'Hàng hoá',
  },
  tabDanhSach: 'Danh sách',
  tabChiTiet: 'Chi tiết',
  searchPlaceholderList: 'Tìm theo số phiếu, kho, đơn vị, đợt cứu trợ…',
  searchPlaceholderCt: 'Tìm theo số phiếu, hàng hoá, kho…',
  emptyTitleList: 'Chưa có phiếu nhập xuất',
  emptyHintList:
    'Lập phiếu nhập kho từ đơn vị cứu trợ, xuất kho cho đợt cứu trợ, hoặc chuyển hàng giữa các kho.',
  emptyTitleCt: 'Chưa có dòng chi tiết',
  emptyHintCt: 'Khi có phiếu được lập, các dòng hàng hoá sẽ hiển thị tại đây.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionLoai: 'Loại phiếu',
    sectionMain: 'Thông tin phiếu',
    sectionChiTiet: 'Chi tiết hàng hoá',
    sectionGhiChu: 'Ghi chú',
    soPhieu: 'Số phiếu',
    soPhieuHintAuto: 'Để trống — hệ thống tự sinh sau khi lưu.',
    ngayPhieu: 'Ngày phiếu',
    khoXuat: 'Kho xuất',
    khoNhap: 'Kho nhập',
    donViCuuTro: 'Đơn vị cứu trợ',
    dotCuuTro: 'Đợt cứu trợ',
    ghiChu: 'Ghi chú',
    addLine: 'Thêm dòng',
    chiTietEmptyHint: 'Chưa có dòng chi tiết — bấm “Thêm dòng” để thêm hàng hoá.',
    hangHoa: 'Hàng hoá',
    donViTinh: 'ĐVT',
    soLuong: 'Số lượng',
    donGia: 'Đơn giá',
    thanhTien: 'Thành tiền',
    chiTietGhiChu: 'Ghi chú',
    tonKhoCurrent: 'Tồn hiện tại: {{value}}',
    tonKhoMissing: 'Chưa có tồn — chọn kho xuất.',
    tonKhoLoading: 'Đang tải tồn kho…',
    tonKhoNotEnough: 'Vượt tồn kho ({{available}})',
    createSubtitle: 'Lập phiếu mới',
    editSubtitle: 'Sửa phiếu',
    cannotDeleteLast: 'Phiếu phải có tối thiểu 1 dòng — không thể xóa dòng cuối.',
    deleteLineTitle: 'Xóa dòng?',
    deleteLineMessage: 'Dòng chi tiết hàng hoá sẽ bị xóa khỏi phiếu.',
  },
  detail: {
    title: 'Chi tiết phiếu',
    sectionMain: 'Thông tin chung',
    sectionChiTiet: 'Chi tiết hàng hoá',
    soPhieu: 'Số phiếu',
    loaiPhieu: 'Loại phiếu',
    ngayPhieu: 'Ngày phiếu',
    khoXuat: 'Kho xuất',
    khoNhap: 'Kho nhập',
    donViCuuTro: 'Đơn vị cứu trợ',
    dotCuuTro: 'Đợt cứu trợ',
    ghiChu: 'Ghi chú',
    soDong: 'Số dòng chi tiết',
    tongTien: 'Tổng thành tiền',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    chiTietEmpty: 'Phiếu chưa có dòng chi tiết.',
    tabChinh: 'Thông tin chung',
    tabChiTiet: 'Chi tiết hàng hoá',
  },
};
