export const matTranNhapXuatKho = {
  noViewPermission: 'Bạn không có quyền xem danh sách phiếu nhập xuất kho.',
  deleteTitle: 'Xóa phiếu nhập/xuất?',
  deleteMessage: 'Phiếu và toàn bộ chi tiết hàng hóa sẽ bị xóa. Tồn kho sẽ thay đổi tương ứng.',
  bulkDeleteTitle: 'Xóa nhiều phiếu?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} phiếu (kèm chi tiết hàng hóa). Tồn kho sẽ thay đổi tương ứng.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'phieu-nhap-xuat-kho',
  exportFileNameCt: 'chi-tiet-nhap-xuat-kho',
  toast: {
    create: 'Đã lập phiếu.',
    update: 'Đã cập nhật phiếu.',
    delete: 'Đã xóa {{count}} phiếu.',
  },
  service: {
    notFound: 'Không tìm thấy phiếu.',
    chiTietRong: 'Phiếu phải có ít nhất 1 dòng chi tiết.',
    /** Mặc định khi parse lỗi PG `TON_KHO_KHONG_DU:` từ trigger. */
    tonKhoKhongDu: 'Tồn kho không đủ để xuất. Vui lòng kiểm tra lại số lượng.',
    /** Mặc định khi parse lỗi PG `LOAI_PHIEU_KHONG_DOI_DUOC:` từ trigger. */
    loaiPhieuKhongDoiDuoc:
      'Phiếu đã phát hành số nên không đổi được loại phiếu. Hãy xóa phiếu lập sai rồi lập phiếu mới đúng loại.',
  },
  validation: {
    ngayPhieuRequired: 'Chọn ngày lập phiếu.',
    khoXuatRequired: 'Chọn kho xuất.',
    khoNhapRequired: 'Chọn kho nhập.',
    donViCuuTroRequired: 'Chọn đơn vị cứu trợ.',
    dotCuuTroRequired: 'Chọn đợt cứu trợ.',
    khoXuatNhapKhacNhau: 'Kho nhập phải khác kho xuất.',
    chiTietMin: 'Phiếu cần ít nhất 1 dòng chi tiết hàng hóa.',
    soLuongInvalid: 'Số lượng phải là số dương.',
    donGiaInvalid: 'Đơn giá phải là số không âm.',
    hangHoaRequired: 'Chọn hàng hóa.',
  },
  store: {
    ttCol: 'TT',
    soPhieuCol: 'Số phiếu',
    loaiPhieuCol: 'Loại phiếu',
    ngayPhieuCol: 'Ngày phiếu',
    khoXuatCol: 'Kho xuất',
    khoNhapCol: 'Kho nhập',
    donViCuuTroCol: 'Đơn vị cứu trợ',
    dotCuuTroCol: 'Đợt cứu trợ',
    nguoiLapCol: 'Người lập phiếu',
    soDongCol: 'Số dòng',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
    /** Tab Chi tiết (flat lines). */
    hangHoaCol: 'Hàng hoá',
    donViTinhCol: 'ĐVT',
    soLuongCol: 'Số lượng',
    donGiaCol: 'Đơn giá',
    thanhTienCol: 'Thành tiền',
    ghiChuCol: 'Ghi chú',
  },
  loaiPhieu: {
    nhap_ngoai: 'Nhập từ ngoài',
    xuat_ngoai: 'Xuất ra ngoài',
    chuyen_kho: 'Chuyển kho',
    all: 'Tất cả loại phiếu',
  },
  toolbar: {
    titleList: 'Phiếu nhập xuất',
    titleCt: 'Chi tiết hàng hoá',
    filterLoaiPhieu: 'Loại phiếu',
    filterKho: 'Kho',
    filterHangHoa: 'Hàng hoá',
    filterDonViCuuTro: 'Đơn vị cứu trợ',
    filterDotCuuTro: 'Đợt cứu trợ',
  },
  tabDanhSach: 'Danh sách',
  tabChiTiet: 'Chi tiết',
  emptyTitleList: 'Chưa có phiếu nhập xuất',
  emptyHintList:
    'Lập phiếu nhập kho từ đơn vị cứu trợ, xuất kho cho đợt cứu trợ, hoặc chuyển hàng giữa các kho.',
  emptyTitleCt: 'Chưa có dòng chi tiết',
  emptyHintCt: 'Khi có phiếu được lập, các dòng hàng hoá sẽ hiển thị tại đây.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionLoai: 'Loại phiếu',
    sectionMain: 'Thông tin phiếu',
    sectionChiTiet: 'Chi tiết hàng hoá',
    sectionGhiChu: 'Ghi chú',
    soPhieu: 'Số phiếu',
    soPhieuHintAuto: 'Để trống — hệ thống tự sinh sau khi lưu.',
    /** Hiện khi sửa phiếu: số phiếu đã phát hành nên loại phiếu bị khoá. */
    loaiPhieuKhoaKhiSua: 'Số phiếu đã phát hành theo loại này nên không đổi loại được.',
    ngayPhieu: 'Ngày phiếu',
    khoXuat: 'Kho xuất',
    khoNhap: 'Kho nhập',
    donViCuuTro: 'Đơn vị cứu trợ',
    dotCuuTro: 'Đợt cứu trợ',
    ghiChu: 'Ghi chú',
    addLine: 'Thêm dòng',
    chiTietEmptyHint: 'Chưa có dòng chi tiết — bấm “Thêm dòng” để thêm hàng hoá.',
    hangHoa: 'Hàng hoá',
    donViTinh: 'ĐVT',
    soLuong: 'Số lượng',
    donGia: 'Đơn giá',
    donGiaAutoHint: 'Đơn giá lấy từ lần nhập gần nhất.',
    thanhTien: 'Thành tiền',
    chiTietGhiChu: 'Ghi chú',
    sectionChungTu: 'Thông tin chứng từ',
    nguoiGiaoHang: 'Họ và tên người giao hàng',
    nguoiNhanHang: 'Họ và tên người nhận hàng',
    boPhan: 'Bộ phận',
    chungTuGoc: 'Chứng từ gốc kèm theo',
    tonKhoCurrent: 'Tồn hiện tại: {{value}}',
    tonKhoMissing: 'Chưa có tồn — chọn kho xuất.',
    tonKhoLoading: 'Đang tải tồn kho…',
    tonKhoNotEnough: 'Vượt tồn kho ({{available}})',
    createSubtitle: 'Lập phiếu mới',
    editSubtitle: 'Sửa phiếu',
    cannotDeleteLast: 'Phiếu phải có tối thiểu 1 dòng — không thể xóa dòng cuối.',
    deleteLineTitle: 'Xóa dòng?',
    deleteLineMessage: 'Dòng chi tiết hàng hoá sẽ bị xóa khỏi phiếu.',
  },
  detail: {
    title: 'Chi tiết phiếu',
    sectionMain: 'Thông tin chung',
    sectionChiTiet: 'Chi tiết hàng hoá',
    soPhieu: 'Số phiếu',
    loaiPhieu: 'Loại phiếu',
    ngayPhieu: 'Ngày phiếu',
    khoXuat: 'Kho xuất',
    khoNhap: 'Kho nhập',
    donViCuuTro: 'Đơn vị cứu trợ',
    dotCuuTro: 'Đợt cứu trợ',
    ghiChu: 'Ghi chú',
    nguoiGiaoHang: 'Người giao hàng',
    nguoiNhanHang: 'Người nhận hàng',
    boPhan: 'Bộ phận',
    chungTuGoc: 'Chứng từ gốc kèm theo',
    soDong: 'Số dòng chi tiết',
    tongTien: 'Tổng thành tiền',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    chiTietEmpty: 'Phiếu chưa có dòng chi tiết.',
    lineDetailTitle: 'Chi tiết dòng hàng hoá',
    toolbarPrint: 'In phiếu',
    tabChinh: 'Thông tin chung',
    tabChiTiet: 'Chi tiết hàng hoá',
  },
  printPreview: {
    pageTitle: 'Xem trước phiếu in',
    documentTitle: 'Phiếu nhập/xuất/chuyển kho',
    fileName: 'phieu-nhap-xuat-kho',
    printPopupBlocked: 'Trình duyệt chặn cửa sổ in — vui lòng cho phép popup.',
    empty: 'Phiếu chưa có dòng chi tiết hàng hoá.',
    noGhiChu: 'Không có ghi chú.',
    colStt: 'STT',
    colTenHang: 'Tên hàng hóa',
    donViLabel: 'Đơn vị',
    diaChiLabel: 'Địa chỉ',
    boPhan: 'Bộ phận',
    soPhieuLabel: 'Số',
    mauSoLabel: 'Mẫu số',
    ngayLapPhieu: 'Ngày lập phiếu',
    mauSoNhap: 'C30 - HD',
    mauSoXuat: 'C21 - HD',
    thongTuNhap: '(Ban hành theo Thông tư số 107/2017/TT-BTC ngày 10/10/2017 của Bộ Tài chính)',
    thongTuXuat: '(Ban hành theo Thông tư số 19/2006/TT-BTC ngày 30/03/2006 của Bộ Tài chính)',
    nguoiGiaoHang: 'Họ và tên người giao hàng',
    nguoiNhanHang: 'Họ và tên người nhận hàng',
    nhapTaiKho: 'Nhập tại kho',
    xuatTaiKho: 'Xuất tại kho',
    donViCuuTro: 'Đơn vị cứu trợ',
    dotCuuTro: 'Đợt cứu trợ',
    tongTienBangChuLabel: 'Tổng số tiền (Viết bằng chữ)',
    chungTuGoc: 'Chứng từ gốc kèm theo',
    cong: 'Cộng',
    ghiChuNoiBo: 'Ghi chú nội bộ',
    signatureDateLine: 'Ngày {{day}} tháng {{month}} năm {{year}}',
    docTitleNhap: 'PHIẾU NHẬP KHO',
    docTitleXuat: 'PHIẾU XUẤT KHO',
    docTitleChuyen: 'PHIẾU CHUYỂN KHO',
    footerCol1Nhap: 'NGƯỜI GIAO HÀNG',
    footerCol2Nhap: 'NGƯỜI LẬP PHIẾU',
    footerCol3Nhap: 'THỦ KHO',
    footerCol1Xuat: 'NGƯỜI NHẬN HÀNG',
    footerCol2Xuat: 'NGƯỜI LẬP PHIẾU',
    footerCol3Xuat: 'THỦ KHO',
    footerCol1Chuyen: 'NGƯỜI NHẬN HÀNG',
    footerCol2Chuyen: 'NGƯỜI LẬP PHIẾU',
    footerCol3Chuyen: 'THỦ KHO',
    footerCol4: 'THỦ TRƯỞNG ĐƠN VỊ',
  },
  import: {
    templateFileName: 'mau-nhap-phieu-nhap-xuat-kho',
    colMaPhieu: 'Mã phiếu',
    colLoaiPhieu: 'Loại phiếu',
    colNgayPhieu: 'Ngày phiếu',
    colKhoXuat: 'Kho xuất',
    colKhoNhap: 'Kho nhập',
    colDonViCuuTro: 'Đơn vị cứu trợ',
    colDotCuuTro: 'Đợt cứu trợ',
    colNguoiGiaoNhan: 'Người giao / nhận hàng',
    colBoPhan: 'Bộ phận',
    colChungTuGoc: 'Chứng từ gốc',
    colGhiChu: 'Ghi chú phiếu',
    colHangHoa: 'Tên hàng hóa',
    colDonViTinh: 'Đơn vị tính',
    colSoLuong: 'Số lượng',
    colDonGia: 'Đơn giá',
    colGhiChuDong: 'Ghi chú dòng hàng',
    rowPrefix: 'Dòng {{row}}: ',
    errMaPhieuEmpty:
      'chưa điền Mã phiếu. Mọi dòng hàng của cùng một phiếu phải ghi CÙNG một mã phiếu (ví dụ P1, P2) để hệ thống gom lại.',
    errLoaiPhieu:
      'Loại phiếu « {{gia_tri}} » không hợp lệ. Chỉ điền « Nhập từ ngoài », « Xuất ra ngoài » hoặc « Chuyển kho ».',
    errNgayPhieu: 'Ngày phiếu « {{gia_tri}} » không đọc được. Điền dạng ngày/tháng/năm, ví dụ 15/09/2026.',
    errKhoNotFound:
      'không tìm thấy kho « {{ten}} » ở cột {{cot}}. Xem sheet « Kho » trong file mẫu để điền đúng tên kho.',
    errKhoNgoaiPhamVi: 'kho « {{ten}} » không thuộc đơn vị của bạn nên bạn không lập được phiếu cho kho này.',
    errDonViCuuTroNotFound:
      'không tìm thấy đơn vị cứu trợ « {{ten}} ». Xem sheet « Đơn vị cứu trợ » trong file mẫu.',
    errDotCuuTroNotFound: 'không tìm thấy đợt cứu trợ « {{ten}} ». Xem sheet « Đợt cứu trợ » trong file mẫu.',
    errHangHoaEmpty: 'chưa điền Tên hàng hóa cho dòng hàng này.',
    errHangHoaNotFound:
      'không tìm thấy hàng hóa « {{ten}} ». Xem sheet « Hàng hóa » trong file mẫu, hoặc thêm hàng hóa vào danh mục trước.',
    errSoLuong: 'Số lượng « {{gia_tri}} » không phải là số.',
    errSoLuongDuong: 'Số lượng « {{gia_tri}} » phải lớn hơn 0.',
    errSoLuongPhanCach:
      'Số lượng « {{gia_tri}} » có dấu phân cách hàng nghìn nên không rõ là bao nhiêu. Hãy gõ số thuần, ví dụ 1000 hoặc 12.5.',
    errDonGia: 'Đơn giá « {{gia_tri}} » không hợp lệ. Điền số từ 0 trở lên, hoặc để trống.',
    errDonGiaPhanCach:
      'Đơn giá « {{gia_tri}} » có dấu phân cách hàng nghìn nên không rõ là bao nhiêu. Hãy gõ số thuần, ví dụ 150000.',
    errDonViTinhEmpty:
      'chưa điền Đơn vị tính và hàng « {{ten}} » trong danh mục cũng chưa có đơn vị tính.',
    errHeaderLech:
      'cột {{cot}} khác với dòng {{row}} của cùng mã phiếu « {{ma_phieu}} ». Mọi dòng của một phiếu phải ghi thông tin đầu phiếu giống hệt nhau.',
    errPhieuHongTheoDong:
      'phiếu « {{ma_phieu}} » có lỗi ở dòng {{row}} nên CẢ PHIẾU chưa được nhập. Sửa dòng lỗi rồi nhập lại toàn bộ các dòng của phiếu này.',
    errPhieuKhongCoDongHang: 'phiếu « {{ma_phieu}} » không có dòng hàng hợp lệ nào nên chưa được nhập.',
    errPhieuKhongHopLe: 'phiếu « {{ma_phieu}} » chưa hợp lệ: {{message}}',
    errPhieuGhiThatBai: 'phiếu « {{ma_phieu}} » không ghi được: {{message}}',
    errTooManyRows:
      'File có {{count}} dòng, vượt mức {{max}} dòng cho một lần nhập. Hãy tách file nhỏ hơn rồi nhập từng lần.',
    errSummary: 'Tổng cộng {{count}} dòng lỗi. Bấm « Tải file dòng lỗi » bên dưới để xem đầy đủ và sửa.',
    toastSuccess: 'Đã nhập {{count}} phiếu từ Excel.',
    sheetHuongDan: 'Hướng dẫn',
    sheetKho: 'Kho',
    sheetHangHoa: 'Hàng hóa',
    sheetDonViCuuTro: 'Đơn vị cứu trợ',
    sheetDotCuuTro: 'Đợt cứu trợ',
    huongDanColKey: 'Cột',
    huongDanColVal: 'Cách điền',
    refColId: 'ID',
    refColTen: 'Tên',
    refColDonViTinh: 'Đơn vị tính',
    hd1k: 'Mã phiếu',
    hd1v:
      'Bắt buộc. Mã TẠM do bạn tự đặt (P1, P2…) chỉ để gom các dòng hàng của cùng một phiếu. Số phiếu thật do hệ thống tự cấp khi lưu.',
    hd2k: 'Một dòng Excel',
    hd2v: 'Là MỘT DÒNG HÀNG. Phiếu có 5 mặt hàng thì ghi 5 dòng, cùng một Mã phiếu.',
    hd3k: 'Thông tin đầu phiếu',
    hd3v:
      'Loại phiếu, Ngày phiếu, Kho, Đơn vị cứu trợ, Đợt cứu trợ — LẶP LẠI GIỐNG HỆT ở mọi dòng của cùng mã phiếu.',
    hd4k: 'Loại phiếu',
    hd4v:
      '« Nhập từ ngoài » cần Kho nhập + Đơn vị cứu trợ. « Xuất ra ngoài » cần Kho xuất + Đợt cứu trợ. « Chuyển kho » cần cả Kho xuất và Kho nhập (hai kho khác nhau).',
    hd5k: 'Số lượng / Đơn giá',
    hd5v: 'Gõ số thuần, KHÔNG dùng dấu phân cách hàng nghìn. Đơn giá để trống thì tính bằng 0.',
    hd6k: 'Đơn vị tính',
    hd6v: 'Để trống thì lấy theo đơn vị tính của hàng hóa trong danh mục.',
    hd7k: 'Nếu một dòng sai',
    hd7v: 'Cả phiếu đó không được nhập, để không ghi thiếu hàng. Các phiếu khác trong file vẫn nhập bình thường.',
    hd8k: 'Người lập phiếu',
    hd8v: 'Không có cột này. Hệ thống tự ghi người đang đăng nhập làm người lập phiếu.',
  },
};
