export const danTocCaNhanTieuBieu = {
  noViewPermission: 'Bạn không có quyền xem thông tin cá nhân tiêu biểu.',
  noViewRowPermission: 'Bạn không có quyền xem hồ sơ cá nhân này.',
  noEditOtherDonVi: 'Bạn chỉ được sửa bản ghi thuộc đơn vị của mình.',
  noDeleteOtherDonVi: 'Bạn chỉ được xóa bản ghi thuộc đơn vị của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  emptyTitle: 'Chưa có cá nhân tiêu biểu',
  emptyHint: 'Thêm hồ sơ cá nhân tiêu biểu để bắt đầu quản lý.',
  emptyFilteredHint: 'Không có bản ghi phù hợp bộ lọc. Thử điều chỉnh tìm kiếm hoặc chip lọc.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'thong-tin-ca-nhan-tieu-bieu',
  deleteTitle: 'Xóa cá nhân tiêu biểu',
  deleteMessage: 'Bạn có chắc muốn xóa hồ sơ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều hồ sơ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} hồ sơ đã chọn? Hành động không hoàn tác.',
  statusChangeTitle: 'Đổi trạng thái hoạt động',
  statusChangeMessage: 'Chuyển trạng thái «{{name}}» sang «{{status}}»?',
  service: {
    notFound: 'Không tìm thấy hồ sơ cá nhân tiêu biểu',
    noEmployeeProfile: 'Không xác định được hồ sơ nhân viên. Vui lòng đăng nhập lại.',
  },
  toast: {
    create: 'Đã thêm cá nhân tiêu biểu',
    update: 'Đã cập nhật hồ sơ',
    delete: 'Đã xóa {{count}} hồ sơ',
    importSuccess: 'Đã nhập {{count}} cá nhân tiêu biểu',
  },
  import: {
    templateName: 'ca-nhan-tieu-bieu',
    rowError: 'Dòng {{row}}: {{message}}',
    toastDone: 'Đã nhập: {{created}} cá nhân mới, {{updated}} cá nhân được ghi đè.',
    keyHoTenNgaySinh: 'họ tên + ngày sinh',
    matchHoTenNgaySinh: 'Họ và tên + Ngày sinh',
    errDonVi: 'không tìm thấy xã, phường “{{gia_tri}}”.',
    errDonViTrungTen: 'có nhiều xã, phường tên “{{gia_tri}}”. Nhập mã (id) xã, phường thay cho tên.',
    errDoiTuong: 'đối tượng “{{gia_tri}}” không hợp lệ — chỉ nhận: {{hop_le}}.',
    errTrangThai: 'trạng thái “{{gia_tri}}” không hợp lệ — chỉ nhận: {{hop_le}}.',
    errNgaySinh: 'ngày sinh “{{gia_tri}}” không hợp lệ — dùng dd/mm/yyyy hoặc yyyy-mm-dd.',
    errNgoaiDonVi: 'bạn chỉ được nhập hồ sơ thuộc xã, phường của mình.',
    errChuaGanDonVi: 'Tài khoản cấp xã, phường chưa được gán đơn vị nên không nhập file được.',
  },
  validation: {
    hoVaTenRequired: 'Vui lòng nhập họ và tên',
    doiTuongInvalid: 'Đối tượng không hợp lệ',
    trangThaiInvalid: 'Trạng thái không hợp lệ',
    donViInvalid: 'Xã/phường không hợp lệ',
  },
  store: {
    hoVaTenCol: 'Họ và tên',
    doiTuongCol: 'Đối tượng',
    chucVuViTriCol: 'Chức vụ / Vị trí',
    tonGiaoDanTocCol: 'Tôn giáo / Dân tộc',
    donViCol: 'Xã, Phường',
    soDienThoaiCol: 'Số điện thoại',
    trangThaiCol: 'Trạng thái',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm cá nhân tiêu biểu',
    editSubtitle: 'Cập nhật hồ sơ',
    sectionMain: 'Thông tin chính',
    sectionContact: 'Liên hệ & địa chỉ',
    sectionContribution: 'Đóng góp',
    hoVaTen: 'Họ và tên',
    ngaySinh: 'Ngày sinh',
    doiTuong: 'Đối tượng',
    chucVuViTri: 'Chức vụ / Vị trí',
    tonGiaoDanToc: 'Tôn giáo / Dân tộc',
    diaChi: 'Địa chỉ',
    donVi: 'Xã, Phường',
    donViHint: 'Chọn xã/phường từ danh mục địa bàn hệ thống.',
    soDienThoai: 'Số điện thoại',
    dongGopNoiBat: 'Đóng góp nổi bật',
    trangThai: 'Trạng thái hoạt động',
  },
  detail: {
    title: 'Chi tiết cá nhân tiêu biểu',
    sectionMain: 'Thông tin chính',
    sectionContact: 'Liên hệ & địa chỉ',
    sectionContribution: 'Đóng góp nổi bật',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    nguoiTao: 'Người tạo',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
    sectionThamHoi: 'Lịch sử thăm hỏi',
    noThamHoi: 'Chưa có lượt thăm hỏi',
    noThamHoiHint: 'Thêm kế hoạch thăm hỏi tại module Thăm hỏi cá nhân.',
    viewAllThamHoi: 'Xem tất cả',
  },
} as const;
