/** Báo cáo / thống kê cán bộ */
export const matTranOfficerStats = {
  title: 'Báo cáo cán bộ',
  noViewPermission: 'Bạn không có quyền xem báo cáo cán bộ.',
  loading: 'Đang tải dữ liệu…',
  noData: 'Không có cán bộ trong khoảng và bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng ngày tạo hoặc bỏ bớt bộ lọc.',
  dateRangeLabel: 'Khoảng ngày tạo',
  filterTrangThai: 'Trạng thái',
  trangThaiChuaGan: 'Chưa gán',
  filterGioiTinh: 'Giới tính',
  filterChucVu: 'Chức vụ',
  filterPhongBan: 'Phòng ban',
  filterDonVi: 'Đơn vị xã',
  filterDanToc: 'Dân tộc',
  filterTrinhDo: 'Trình độ',
  filterToChuc: 'Tổ chức',
  filterDangVien: 'Đảng viên',
  exportFileName: 'Bao_Cao_Can_Bo',
  noExportData: 'Không có dữ liệu để xuất',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  kpiTotal: 'Tổng số cán bộ',
  kpiNam: 'Nam',
  kpiNu: 'Nữ',
  kpiDangVien: 'Đảng viên',
  chartTrendCount: 'Số lượng theo ngày tạo',
  chartGioiTinh: 'Theo giới tính',
  chartTopPhongBan: 'Theo phòng ban (Top)',
  chartTopDonVi: 'Theo đơn vị xã (Top)',
  chartTopChucVu: 'Theo chức vụ (Top)',
  tableLookupTitle: 'Tra cứu',
  tableColHoTen: 'Họ tên',
  tableColDonVi: 'Đơn vị',
  tableColChucVu: 'Chức vụ',
  tableColTrangThai: 'Trạng thái',
  tableColDienThoai: 'Điện thoại',
  tableColTuoi: 'Tuổi',
  tableColGioiTinh: 'Giới tính',
  tableTwoColLabel: 'Nhóm',
  tableTwoColValue: 'Số người',
  preset: {
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    thisQuarter: 'Quý này',
    thisYear: 'Năm nay',
    custom: 'Tùy chọn',
  },
  dangVienYes: 'Có',
  dangVienNo: 'Không',
} as const;
