/** Báo cáo tiếp nhận & phân bổ — kho cứu trợ */
export const matTranReliefSupportReport = {
  title: 'Báo cáo tiếp nhận & phân bổ',
  noViewPermission: 'Bạn không có quyền xem báo cáo tiếp nhận & phân bổ.',
  loading: 'Đang tải dữ liệu…',
  noData: 'Không có dữ liệu trong khoảng và bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng ngày phiếu hoặc bỏ bớt bộ lọc.',
  dateRangeLabel: 'Khoảng ngày phiếu',
  filterKho: 'Kho',
  filterLoaiPhieu: 'Loại phiếu',
  filterDonVi: 'Nhà tài trợ',
  filterDot: 'Chương trình vận động',
  filterHangHoa: 'Hàng hóa',
  filterDanhMuc: 'Danh mục hàng',
  exportFileName: 'Bao_Cao_Ho_Tro',
  noExportData: 'Không có dữ liệu để xuất',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  exportRangeAll: 'Tất cả',
  kpiPhieu: 'Số phiếu',
  kpiLine: 'Số dòng chi tiết',
  kpiNhapSl: 'SL nhập',
  kpiNhapTien: 'Giá trị nhập',
  kpiXuatSl: 'SL xuất',
  kpiXuatTien: 'Giá trị xuất',
  kpiChuyenSl: 'SL chuyển kho',
  kpiDonVi: 'Đơn vị có phát sinh',
  kpiDot: 'Đợt có xuất',
  kpiTonSl: 'Tồn hiện tại (SL)',
  kpiKhoCoHang: 'Kho có hàng',
  chartTrend: 'Xu hướng nhập / xuất (số lượng)',
  chartTrendNhap: 'Nhập',
  chartTrendXuat: 'Xuất',
  chartTopDonVi: 'Top nhà tài trợ (giá trị nhập)',
  chartTopDot: 'Top chương trình vận động (giá trị xuất)',
  chartByLoaiDonVi: 'Theo loại nhà tài trợ',
  chartTopHangNhap: 'Top hàng hóa nhập',
  chartTopHangXuat: 'Top hàng hóa xuất',
  tableLookupTitle: 'Tra cứu chi tiết',
  tableColNgay: 'Ngày phiếu',
  tableColSoPhieu: 'Số phiếu',
  tableColLoai: 'Loại phiếu',
  tableColKho: 'Kho',
  tableColNguonDich: 'Nguồn / Đích',
  tableColHang: 'Hàng hóa',
  tableColSl: 'Số lượng',
  tableColDvt: 'ĐVT',
  tableColTien: 'Thành tiền',
  tableTwoColLabel: 'Nhóm',
  tableTwoColValue: 'Giá trị',
  preset: {
    all: 'Tất cả',
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    thisQuarter: 'Quý này',
    thisYear: 'Năm nay',
    custom: 'Tùy chọn',
  },
  exportSheetSummary: 'Tong_hop',
  exportSheetDetail: 'Chi_tiet',
  exportKpiLabel: 'Chỉ tiêu',
  exportKpiValue: 'Giá trị',
  export: {
    success: 'Xuất báo cáo Excel thành công',
    error: 'Xuất báo cáo thất bại',
  },
} as const;
