/** Báo cáo / thống kê ủy viên ủy ban */
export const matTranCommitteeMemberStats = {
  title: 'Báo cáo ủy viên',
  noViewPermission: 'Bạn không có quyền xem báo cáo ủy viên.',
  loading: 'Đang tải dữ liệu…',
  noData: 'Không có ủy viên trong khoảng và bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng ngày tạo hoặc bỏ bớt bộ lọc.',
  dateRangeLabel: 'Khoảng ngày tạo',
  filterNhiemKy: 'Nhiệm kỳ',
  filterDonVi: 'Đơn vị',
  filterGioiTinh: 'Giới tính',
  filterTrangThamGia: 'Trạng thái tham gia',
  trangThaiChuaGan: 'Chưa gán',
  filterDangVien: 'Đảng viên',
  exportFileName: 'Bao_Cao_Uy_Vien',
  noExportData: 'Không có dữ liệu để xuất',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  kpiTotal: 'Tổng số ủy viên',
  kpiNam: 'Nam',
  kpiNu: 'Nữ',
  kpiDangVien: 'Đảng viên',
  chartTrendCount: 'Số lượng theo ngày tạo',
  chartGioiTinh: 'Theo giới tính',
  chartTopDonVi: 'Theo đơn vị (Top)',
  chartTopNhiemKy: 'Theo nhiệm kỳ (Top)',
  chartTopChucVu: 'Theo chức vụ đơn vị (Top)',
  tableLookupTitle: 'Tra cứu',
  tableColHoTen: 'Họ tên',
  tableColNhiemKy: 'Nhiệm kỳ',
  tableColDonVi: 'Đơn vị',
  tableColChucVu: 'Chức vụ đơn vị',
  tableColTrangThamGia: 'Trạng thái tham gia',
  tableColDienThoai: 'Điện thoại',
  tableColTuoi: 'Tuổi',
  tableColGioiTinh: 'Giới tính',
  tableTwoColLabel: 'Nhóm',
  tableTwoColValue: 'Số người',
  preset: {
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    thisQuarter: 'Quý này',
    thisYear: 'Năm nay',
    custom: 'Tùy chọn',
  },
  dangVienYes: 'Có',
  dangVienNo: 'Không',
} as const;
