/** BC thống kê bài viết */
export const articleStats = {
  title: 'BC thống kê bài viết',
  accessDenied: 'Bạn không có quyền xem báo cáo thống kê bài viết.',
  noViewPermission: 'Bạn không có quyền xem module BC thống kê bài viết.',
  loading: 'Đang tải thống kê…',
  noData: 'Không có dữ liệu trong khoảng ngày tạo đã chọn.',
  noDataHint: 'Thử đổi khoảng ngày tạo hoặc bỏ bớt bộ lọc.',
  clearFilters: 'Xóa bộ lọc',
  dateRangeLabel: 'Khoảng ngày tạo',
  filterTheLoai: 'Thể loại',
  filterNguon: 'Nguồn đăng',
  filterTrang: 'Trang đăng',
  filterNguoiTao: 'Người tạo',
  export: 'Xuất Excel',
  exportFileName: 'BC_Thong_Ke_Bai_Viet',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  noExportData: 'Không có dữ liệu để xuất',
  kpiTotal: 'Tổng số bài',
  kpiTotalDonGia: 'Tổng đơn giá (VNĐ)',
  kpiAvgDonGia: 'Đơn giá trung bình',
  kpiDistinctTheLoai: 'Số thể loại',
  kpiDistinctAuthors: 'Số người có bài',
  chartTrendCount: 'Số bài theo thời gian',
  chartTrendAmount: 'Tổng đơn giá theo thời gian',
  chartTopTheLoai: 'Theo thể loại (Top)',
  chartTopNguon: 'Theo nguồn đăng (Top)',
  chartTopNguoi: 'Theo người tạo (Top)',
  tableLookupTitle: 'Tra cứu chi tiết',
  tableColTenBai: 'Tên bài',
  tableColTheLoai: 'Thể loại',
  tableColNgayDang: 'Ngày đăng',
  tableColDonGia: 'Đơn giá',
  tableColNguon: 'Nguồn',
  tableColTrang: 'Trang',
  tableColNguoi: 'Người tạo',
  tableColLink: 'Liên kết',
  tableTwoColLabel: 'Nhóm',
  tableTwoColValue: 'Số bài',
  preset: {
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    thisQuarter: 'Quý này',
    thisYear: 'Năm nay',
    custom: 'Tùy chọn',
  },
} as const;
