/** BC thống kê bài viết */
export const articleStats = {
  title: 'BC thống kê bài viết',
  accessDenied: 'Bạn không có quyền xem báo cáo thống kê bài viết.',
  noViewPermission: 'Bạn không có quyền xem module BC thống kê bài viết.',
  loading: 'Đang tải thống kê…',
  noData: 'Không có dữ liệu trong khoảng ngày tạo đã chọn.',
  noDataHint: 'Thử đổi khoảng ngày tạo hoặc bỏ bớt bộ lọc.',
  clearFilters: 'Xóa bộ lọc',
  dateRangeLabel: 'Khoảng ngày tạo',
  filterTheLoai: 'Thể loại',
  filterNguon: 'Nguồn đăng',
  filterTrang: 'Trang đăng',
  filterNguoiTao: 'Người tạo',
  filterDonVi: 'Đơn vị',
  export: 'Xuất Excel',
  exportFileName: 'BC_Thong_Ke_Bai_Viet',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  exportRangeAll: 'Toàn bộ thời gian',
  exportFailed: 'Không xuất được file. Vui lòng thử lại.',
  exportColStt: 'STT',
  exportColChiTieu: 'Chỉ tiêu',
  exportColGiaTri: 'Giá trị',
  exportColKy: 'Kỳ',
  exportTongSoTien: 'Tổng số tiền',
  /* Tên sheet không dấu: tránh mọi rủi ro với phần mềm bảng tính cũ. */
  exportSheetTongHop: 'Tong hop',
  exportSheetTheoDonVi: 'Theo don vi',
  exportSheetTheoTheLoai: 'Theo the loai',
  exportSheetTheoNguon: 'Theo nguon dang',
  exportSheetTheoTrang: 'Theo trang dang',
  exportSheetTheoNguoiTao: 'Theo nguoi tao',
  exportSheetTheoThoiGian: 'Theo thoi gian',
  exportSheetChiTiet: 'Chi tiet',
  noExportData: 'Không có dữ liệu để xuất',
  kpiTotal: 'Tổng số bài',
  kpiTongDonVi: 'Tổng đơn vị',
  kpiTbSoBai: 'Trung bình số bài',
  kpiDistinctTheLoai: 'Số thể loại',
  kpiDistinctAuthors: 'Số người có bài',
  chartTrendCount: 'Số bài theo thời gian',
  chartTheLoaiCount: 'Số bài theo thể loại',
  chartTopTheLoai: 'Theo thể loại (Top)',
  chartTopNguon: 'Theo nguồn đăng (Top)',
  chartTopNguoi: 'Theo người tạo (Top)',
  chartTopDonVi: 'Số bài theo đơn vị (Top 10)',
  tableDonViTitle: 'Tổng hợp theo đơn vị',
  tableColDonVi: 'Đơn vị',
  tableColSoBai: 'Số bài',
  /** Chỉ dùng cho file xuất — màn hình báo cáo vẫn không hiện tiền. */
  tableColSoTien: 'Số tiền',
  tableColTyTrong: 'Tỷ trọng',
  tableRowTong: 'Tổng cộng',
  donViKhongXacDinh: 'Chưa xác định đơn vị',
  tableLookupTitle: 'Tra cứu chi tiết',
  tableColTenBai: 'Tên bài',
  tableColTheLoai: 'Thể loại',
  tableColNgayDang: 'Ngày đăng',
  tableColNguon: 'Nguồn',
  tableColTrang: 'Trang',
  tableColNguoi: 'Người tạo',
  tableColLink: 'Liên kết',
  tableTwoColLabel: 'Nhóm',
  tableTwoColValue: 'Số bài',
  preset: {
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    thisQuarter: 'Quý này',
    thisYear: 'Năm nay',
    custom: 'Tùy chọn',
  },
} as const;
