export const matTranKyHop = {
  noViewPermission: 'Bạn không có quyền xem danh sách kỳ họp.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo bản ghi.',
  tinhCap: 'MTTQ tỉnh',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy bản ghi kỳ họp.',
  },
  deleteTitle: 'Xóa kỳ họp?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều kỳ họp?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-ky-hop',
  toast: {
    create: 'Đã tạo kỳ họp.',
    update: 'Đã cập nhật kỳ họp.',
    delete: 'Đã xóa {{count}} bản ghi.',
    importSuccess: 'Đã nhập {{count}} kỳ họp.',
  },
  import: {
    rowError: 'Dòng {{row}}: {{message}}',
    templateName: 'mau-nhap-ky-hop',
    badNhiemKy: 'Không tìm thấy nhiệm kỳ (ten_nhiem_ky / nhiem_ky_id).',
    nhiemKyIdCol: 'nhiem_ky_id (tùy chọn, số)',
    donViIdCol: 'don_vi_id (tùy chọn, số)',
  },
  export: {
    nhiemKyIdCol: 'ID nhiệm kỳ',
    donViIdCol: 'ID đơn vị (xã/phường, để trống = MTTQ tỉnh)',
  },
  validation: {
    nhiemKyRequired: 'Chọn nhiệm kỳ.',
    kyThuRequired: 'Nhập kỳ thứ.',
    taiLieuHopUrl: 'Tài liệu họp phải là URL hợp lệ (http/https) hoặc để trống.',
  },
  store: {
    tenNhiemKyCol: 'Nhiệm kỳ',
    kyThuCol: 'Kỳ thứ',
    ngayHopCol: 'Ngày họp',
    donViCol: 'Đơn vị',
    noiDungCol: 'Nội dung kỳ họp',
    diemDanhCoMatCol: 'Có mặt',
    diemDanhVangMatCol: 'Vắng mặt',
    diemDanhChuaCol: 'Chưa điểm danh',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Kỳ họp',
  },
  searchPlaceholder: 'Tìm theo nhiệm kỳ, kỳ thứ, đơn vị, nội dung…',
  emptyTitle: 'Chưa có kỳ họp',
  emptyHint: 'Thêm kỳ họp mới để bắt đầu.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionMain: 'Thông tin kỳ họp',
    nhiemKy: 'Nhiệm kỳ',
    donVi: 'Đơn vị (xã/phường)',
    donViPlaceholder: 'Để trống = MTTQ tỉnh',
    kyThu: 'Kỳ thứ',
    ngayHop: 'Ngày họp',
    noiDungKyHop: 'Nội dung kỳ họp',
    taiLieuHop: 'Tài liệu họp',
    ghiChu: 'Ghi chú',
    createSubtitle: 'Thêm kỳ họp mới',
    editSubtitle: 'Sửa kỳ họp',
  },
  detail: {
    title: 'Chi tiết kỳ họp',
    sectionMain: 'Thông tin',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    tabInfo: 'Thông tin',
    tabDiemDanh: 'Điểm danh',
    sectionDiemDanhSummary: 'Điểm danh (tóm tắt)',
  },
  diemDanh: {
    coMat: 'Có mặt',
    vangMat: 'Vắng mặt',
    chuaDiemDanh: 'Chưa điểm danh',
    emptyUyVien: 'Nhiệm kỳ này chưa có ủy viên.',
    saveFailed: 'Lưu điểm danh thất bại.',
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    sectionTitle: 'Điểm danh ủy viên',
    uyVienCol: 'Ủy viên',
    trangThaiCol: 'Trạng thái',
    noViewPermission: 'Bạn không có quyền xem điểm danh.',
    readOnlyHint: 'Chỉ xem — không có quyền chỉnh sửa.',
  },
} as const;
