/** Nhân viên */
export const employee = {
  "noViewPermission": "Bạn không có quyền xem module Nhân viên.",
  "title": "Nhân viên",
  "rowActions": {
    "more": "Thao tác khác"
  },
  "unassigned": "Chưa gán",
  "deleteConfirmTitle": "Xóa nhân viên?",
  "deleteConfirmMessage": "Bạn có chắc muốn xóa nhân viên",
  "deleteConfirmNote": "Bạn có thể hoàn tác trong vài giây.",
  "statusChangeTitle": "Cập nhật trạng thái",
  "statusChangeMessage": "Chọn trạng thái mới cho nhân viên",
  "bulkDeleteTitle": "Xóa nhiều nhân viên",
  "bulkDeleteMessage": "Bạn đang chọn xóa {{count}} hồ sơ nhân sự. Bạn có thể hoàn tác trong vài giây.",
  "bulkStatusTitle": "Cập nhật trạng thái hàng loạt",
  "bulkStatusMessage": "Chuyển trạng thái {{count}} nhân viên sang",
  "exportFileName": "Danh_Sach_Nhan_Vien",
  "noExportData": "Không có dữ liệu để xuất",
  "statusActive": "Hoạt động",
  "statusLocked": "Khóa",
  "form": {
    "editTitle": "Chỉnh sửa Hồ sơ",
    "createTitle": "Thêm Nhân viên mới",
    "editSubtitle": "ID:",
    "createSubtitle": "Thiết lập thông tin nhân sự mới vào hệ thống",
    "avatar": "Ảnh đại diện",
    "avatarHint": "PNG, JPG · Tối đa 2MB",
    "username": "Tên tài khoản",
    "usernamePlaceholder": "vd: nguyenvana",
    "authEmailHint": "Email Auth: {{email}} · Mật khẩu mặc định: 123456",
    "authEmailHintEmpty": "Email Auth sẽ là <ten_tai_khoan>@gmail.com · Mật khẩu mặc định: 123456",
    "statusSwitchActiveHint": "Tài khoản đang được phép đăng nhập.",
    "statusSwitchLockedHint": "Tài khoản bị khoá, không đăng nhập được.",
    "identity": "Định danh",
    "unit": "Bộ phận",
    "unitPlaceholder": "Chọn bộ phận...",
    "fullName": "Họ và tên",
    "fullNamePlaceholder": "Nguyễn Văn A",
    "workInfo": "Thông tin công việc",
    "position": "Chức vụ",
    "positionPlaceholder": "Chọn chức vụ...",
    "donViXaPhuong": "Xã/phường (đơn vị)",
    "donViXaPhuongPlaceholder": "Chọn xã/phường trong danh mục Tỉnh thành — Xã phường…",
    "donViXaPhuongSearch": "Tìm xã, phường, tỉnh…",
    "department": "Phòng ban",
    "departmentPlaceholder": "Chọn phòng ban..."
  },
  "detail": {
    "title": "Hồ sơ nhân viên",
    "identity": "Thông tin định danh",
    "changeStatus": "Đổi trạng thái",
    "fullName": "Họ tên",
    "systemInfo": "Thông tin hệ thống",
    "createdDate": "Ngày tạo",
    "lastUpdated": "Cập nhật lần cuối"
  },
  "toolbar": {
    "department": "Phòng ban",
    "position": "Chức vụ",
    "status": "Trạng thái"
  },
  "validation": {
    "usernameMin": "Tên tài khoản phải có ít nhất 2 ký tự",
    "usernameFormat": "Tên tài khoản chỉ chứa chữ, số, dấu chấm, gạch dưới hoặc gạch ngang",
    "fullNameMin": "Họ tên phải có ít nhất 2 ký tự",
    "positionRequired": "Vui lòng chọn chức vụ",
    "departmentRequired": "Vui lòng chọn phòng ban",
    "donViRequired": "Chức vụ cấp \"Xã phường\" bắt buộc chọn xã/phường (đơn vị)"
  },
  "toast": {
    "createSuccess": "Thêm nhân viên thành công",
    "updateSuccess": "Cập nhật thông tin thành công",
    "statusUpdateSuccess": "Đã cập nhật trạng thái {{count}} nhân viên",
    "deleteSuccess": "Đã xóa thành công {{count}} nhân viên",
    "deleteCount": "Đã xóa {{count}} nhân viên",
    "undo": "Hoàn tác",
    "undoSuccess": "Đã hoàn tác xóa",
    "undoFailed": "Hoàn tác KHÔNG thành công — nhân viên vẫn đang bị xóa. Lý do: {{reason}}",
    "deleteFailed": "Xóa nhân viên không thành công. Lý do: {{reason}}",
    "authPasswordReset": "Đã đặt lại mật khẩu đăng nhập",
    "generatedPasswordTitle": "Mật khẩu đăng nhập mới — hãy sao chép và đưa cho người dùng"
  },
  "resetPassword": {
    "action": "Đổi mật khẩu",
    "title": "Đổi mật khẩu đăng nhập",
    "subtitle": "Đặt mật khẩu mới cho tài khoản",
    "warning": "Mật khẩu cũ bị ghi đè ngay. Người dùng đang đăng nhập vẫn giữ phiên hiện tại cho tới khi đăng xuất.",
    "newPassword": "Mật khẩu mới",
    "confirmPassword": "Nhập lại mật khẩu mới",
    "placeholder": "Ít nhất 6 ký tự",
    "hint": "Tối thiểu 6 ký tự, không có khoảng trắng ở đầu/cuối. Hãy bàn giao trực tiếp cho người dùng.",
    "showPassword": "Hiện mật khẩu",
    "hidePassword": "Ẩn mật khẩu",
    "errorTrong": "Chưa nhập mật khẩu mới",
    "errorQuaNgan": "Mật khẩu phải có ít nhất 6 ký tự",
    "errorKhongKhop": "Hai lần nhập mật khẩu không giống nhau",
    "errorCoKhoangTrang": "Mật khẩu không được có khoảng trắng ở đầu hoặc cuối",
    "errorNoUsername": "Nhân viên chưa có tên tài khoản đăng nhập",
    "toastSuccess": "Đã đổi mật khẩu cho tài khoản {{username}}",
    "toastCreated": "Tài khoản {{username}} chưa có trên hệ thống đăng nhập — đã tạo mới và đặt mật khẩu vừa nhập",
    "toastFallback": "Máy chủ từ chối mật khẩu vừa nhập và đã sinh mật khẩu khác — hãy sao chép ngay",
    "toastFailed": "Đổi mật khẩu không thành công. Lý do: {{reason}}"
  },
  "authConflict": {
    "title": "Tài khoản đăng nhập đã tồn tại",
    "desc": "Email {{email}} đã có sẵn trên hệ thống. Bạn muốn xử lý thế nào?",
    "optionResetTitle": "Đặt lại mật khẩu về 123456",
    "optionResetDesc": "Mật khẩu hiện tại sẽ bị ghi đè bằng 123456 và liên kết với hồ sơ nhân viên này.",
    "optionKeepTitle": "Giữ mật khẩu hiện tại",
    "optionKeepDesc": "Không thay đổi mật khẩu; chỉ liên kết tài khoản Auth có sẵn với hồ sơ nhân viên này."
  },
  "service": {
    "notFound": "Nhân viên không tồn tại"
  },
  "store": {
    "usernameCol": "Tên tài khoản",
    "unitCol": "Bộ phận",
    "nameCol": "Họ và tên",
    "positionCol": "Chức vụ",
    "statusCol": "Trạng thái",
    "departmentCol": "Phòng ban",
    "donViCol": "Đơn vị"
  },
  "import": {
    "templateFileName": "mau-nhap-nhan-vien",
    "colTenTaiKhoan": "Tên tài khoản",
    "colHoVaTen": "Họ và tên",
    "colPhongBan": "Phòng ban",
    "colBoPhan": "Bộ phận",
    "colChucVu": "Chức vụ",
    "colCapQuanLy": "Cấp quản lý",
    "colToChuc": "Tổ chức",
    "colDonVi": "Đơn vị (xã/phường)",
    "colTrangThai": "Trạng thái",
    "rowPrefix": "Dòng {{row}}: ",
    "errTaiKhoanEmpty": "chưa điền Tên tài khoản (dùng để đăng nhập).",
    "errTaiKhoanTrungHeThong": "tên tài khoản « {{ten}} » đã có người dùng, hãy đặt tên khác.",
    "errTaiKhoanTrungFile": "tên tài khoản « {{ten}} » đã xuất hiện ở dòng {{row}} trong cùng file.",
    "errHoTenEmpty": "chưa điền Họ và tên.",
    "errPhongBanEmpty": "chưa điền Phòng ban.",
    "errPhongBanNotFound": "không tìm thấy phòng ban « {{ten}} ». Xem sheet « Phòng ban » trong file mẫu để điền đúng tên.",
    "errBoPhanNotFound": "không tìm thấy bộ phận « {{ten}} ». Bộ phận cũng lấy từ sheet « Phòng ban », hoặc để trống.",
    "errChucVuEmpty": "chưa điền Chức vụ.",
    "errChucVuNotFound": "không tìm thấy chức vụ « {{ten}} ». Xem sheet « Chức vụ » trong file mẫu để điền đúng tên.",
    "errCapQuanLy": "Cấp quản lý « {{gia_tri}} » không hợp lệ. Chỉ điền « Tỉnh » hoặc « Xã phường » (nhiều giá trị cách nhau dấu phẩy).",
    "errToChucNotFound": "không tìm thấy tổ chức « {{ten}} ». Xem sheet « Tổ chức » trong file mẫu để điền đúng tên.",
    "errDonViNotFound": "không tìm thấy xã/phường « {{ten}} ». Xem sheet « Xã phường » trong file mẫu để điền đúng tên.",
    "errDonViRequired": "Cấp quản lý là « Xã phường » thì bắt buộc phải điền cột Đơn vị (xã/phường).",
    "errTrangThai": "Trạng thái « {{gia_tri}} » không hợp lệ. Chỉ điền « Hoạt động » hoặc « Khóa », hoặc để trống.",
    "errTooManyRows": "File có {{count}} dòng, vượt mức {{max}} dòng cho một lần nhập. Hãy tách file nhỏ hơn rồi nhập từng lần.",
    "errSummary": "Tổng cộng {{count}} dòng lỗi. Bấm « Tải file dòng lỗi » bên dưới để xem đầy đủ và sửa.",
    "errTaoTaiKhoanDangNhap": "không tạo được tài khoản đăng nhập cho « {{ten}} »: {{message}}",
    "errAuthTonTai": "địa chỉ đăng nhập của tài khoản « {{ten}} » đã tồn tại trên hệ thống đăng nhập. Hãy đặt tên tài khoản khác, hoặc nhờ quản trị viên xử lý tài khoản cũ rồi nhập lại.",
    "toastSuccess": "Đã nhập {{count}} nhân viên từ Excel. Mật khẩu do hệ thống sinh — vào từng hồ sơ để đặt lại và bàn giao.",
    "sheetHuongDan": "Hướng dẫn",
    "sheetPhongBan": "Phòng ban",
    "sheetChucVu": "Chức vụ",
    "sheetToChuc": "Tổ chức",
    "sheetXaPhuong": "Xã phường",
    "huongDanColKey": "Cột",
    "huongDanColVal": "Cách điền",
    "refColId": "ID",
    "refColTen": "Tên",
    "hd1k": "Tên tài khoản",
    "hd1v": "Bắt buộc. Chỉ chữ không dấu, số, dấu chấm, gạch dưới, gạch ngang. Đây là tên đăng nhập, không đặt trùng.",
    "hd2k": "Họ và tên",
    "hd2v": "Bắt buộc. Họ tên đầy đủ, có dấu.",
    "hd3k": "Phòng ban / Bộ phận / Chức vụ",
    "hd3v": "Điền ĐÚNG tên như trong các sheet tra cứu kèm theo, hoặc điền số ID. Bộ phận có thể để trống.",
    "hd4k": "Cấp quản lý",
    "hd4v": "« Tỉnh » hoặc « Xã phường ». Được điền cả hai, cách nhau dấu phẩy. Để trống nếu không phân cấp.",
    "hd5k": "Tổ chức",
    "hd5v": "Một hoặc nhiều tổ chức, cách nhau dấu phẩy. Xem sheet « Tổ chức ».",
    "hd6k": "Đơn vị (xã/phường)",
    "hd6v": "BẮT BUỘC khi Cấp quản lý có « Xã phường ». Xem sheet « Xã phường ».",
    "hd7k": "Trạng thái",
    "hd7v": "« Hoạt động » hoặc « Khóa ». Để trống = Hoạt động.",
    "hd8k": "Mật khẩu",
    "hd8v": "Không có cột mật khẩu. Hệ thống tự sinh mật khẩu cho từng tài khoản; vào hồ sơ nhân viên để đặt lại và bàn giao."
  }
} as const;
