/** Module Tiếp nhận — khoản tài trợ của nhà tài trợ cho chương trình vận động. */
export const matTranTiepNhan = {
  noViewPermission: 'Bạn không có quyền xem danh sách tiếp nhận.',
  empty: 'Chưa có khoản tiếp nhận nào',
  emptyHint: 'Ghi nhận tiền, hiện vật, giấy tờ có giá nhà tài trợ ủng hộ cho chương trình vận động.',
  listLoadErrorHint: 'Không tải được danh sách tiếp nhận. Thử lại sau ít phút.',
  deleteTitle: 'Xoá khoản tiếp nhận?',
  deleteMessage: 'Khoản tiếp nhận và liên kết phiếu kho sẽ bị xoá. Phiếu nhập kho vẫn giữ nguyên.',
  bulkDeleteTitle: 'Xoá nhiều khoản tiếp nhận?',
  bulkDeleteMessage: 'Sẽ xoá {{count}} khoản tiếp nhận.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'tiep-nhan',
  notFound: 'Không tìm thấy khoản tiếp nhận (hoặc nằm ngoài phạm vi xem).',
  toast: {
    create: 'Đã ghi nhận khoản tiếp nhận.',
    update: 'Đã cập nhật khoản tiếp nhận.',
    delete: 'Đã xoá {{count}} khoản tiếp nhận.',
    trangThai: 'Đã chuyển trạng thái.',
  },
  validation: {
    nhaTaiTroRequired: 'Chọn nhà tài trợ.',
    chuongTrinhRequired: 'Chọn chương trình vận động.',
    ngayRequired: 'Nhập ngày tiếp nhận.',
    soTienInvalid: 'Số tiền không hợp lệ.',
    hinhThucRequired: 'Có số tiền thì phải chọn hình thức (chuyển khoản / tiền mặt).',
    tongGiaTriRong: 'Khoản tiếp nhận phải có giá trị: nhập số tiền, giấy tờ có giá, hiện vật khác, hoặc gắn phiếu nhập kho.',
    moTaKhiCoGiaTri: 'Có giá trị thì ghi rõ nội dung.',
    phuLucMax: 'Phụ lục tối đa {{max}} dòng.',
  },
  store: {
    soPhieuCol: 'Số phiếu',
    ngayCol: 'Ngày tiếp nhận',
    nhaTaiTroCol: 'Nhà tài trợ',
    chuongTrinhCol: 'Chương trình vận động',
    donViTiepNhanCol: 'Đơn vị tiếp nhận',
    hinhThucCol: 'Hình thức',
    soTienCol: 'Số tiền',
    giayToCoGiaCol: 'Giấy tờ có giá',
    hienVatKhacCol: 'Hiện vật khác',
    phieuKhoCol: 'Hàng qua kho',
    tongGiaTriCol: 'Tổng giá trị',
    trangThaiCol: 'Trạng thái',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Ghi nhận khoản tài trợ',
    editSubtitle: 'Sửa khoản tiếp nhận',
    sectionChung: 'Nhà tài trợ & chương trình',
    sectionTien: 'Bằng tiền',
    sectionHienVat: 'Hiện vật',
    sectionGiayTo: 'Giấy tờ có giá',
    sectionMucDich: 'Mục đích tài trợ',
    sectionPhuLuc: 'Phụ lục — danh sách người được tài trợ',
    sectionKhac: 'Lập biên bản & ghi chú',
    nhaTaiTroPlaceholder: 'Chọn từ danh mục Nhà tài trợ',
    chuongTrinhHint: 'Chỉ hiện chương trình đang triển khai trong phạm vi đơn vị mình.',
    chuongTrinhTrong: 'Chưa có chương trình vận động nào đang triển khai trong phạm vi của bạn.',
    ngay: 'Ngày tiếp nhận',
    hinhThuc: 'Hình thức',
    soTien: 'Số tiền',
    phieuKhoLabel: 'Phiếu nhập kho của nhà tài trợ',
    phieuKhoHint: 'Hàng đã nhập kho chỉ cần gắn phiếu — giá trị tự cộng, không nhập lại.',
    phieuKhoChonNhaTaiTro: 'Chọn nhà tài trợ để thấy các phiếu nhập kho của họ.',
    phieuKhoTrong: 'Nhà tài trợ này chưa có phiếu "Nhập từ ngoài" nào.',
    phieuKhoDaGan: 'Đã gắn ở {{soPhieu}}',
    phieuKhoTong: 'Giá trị hàng qua kho: {{tien}}',
    hienVatKhacMoTa: 'Hiện vật khác (không qua kho)',
    hienVatKhacMoTaPlaceholder: 'VD: 50 suất quà trao trực tiếp tại xã',
    hienVatKhacGiaTri: 'Quy ra trị giá',
    giayToMoTa: 'Giấy tờ có giá',
    giayToMoTaPlaceholder: 'VD: Sổ tiết kiệm, trái phiếu…',
    giayToGiaTri: 'Quy ra trị giá',
    tongGiaTri: 'Tổng giá trị khoản tiếp nhận',
    phuLucThem: 'Thêm dòng',
    phuLucHoTen: 'Họ tên người ký xác nhận',
    phuLucDiaChi: 'Địa chỉ',
    phuLucQuanHe: 'Người được tài trợ / quan hệ',
    phuLucNoiDung: 'Nội dung, giá trị nhận',
    phuLucHint: 'Chỉ cần khi tài trợ cho người bệnh hoặc cá nhân bị thiên tai, dịch bệnh. Để trống thì bản in có sẵn 10 dòng viết tay.',
    diaDiemLap: 'Nơi lập biên bản',
    ghiChu: 'Ghi chú',
  },
  detail: {
    title: 'Chi tiết tiếp nhận',
    sectionChung: 'Thông tin chung',
    sectionGiaTri: 'Giá trị tài trợ',
    sectionPhieuKho: 'Phiếu nhập kho đã gắn',
    sectionMucDich: 'Mục đích tài trợ',
    sectionPhuLuc: 'Phụ lục người được tài trợ',
    phuLucTrong: 'Chưa nhập — bản in để 10 dòng viết tay.',
    phieuKhoTrong: 'Không gắn phiếu kho nào.',
    mucDichTrong: 'Chưa chọn mục đích.',
    actionPrint: 'In biên bản xác nhận',
    actionTrangThai: 'Chuyển trạng thái',
  },
  statusChange: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đăng ký ⇄ Đã bàn giao',
    lyDo: 'Lý do / ghi chú',
    save: 'Lưu trạng thái',
  },
  inBienBan: {
    tenBienBan: 'Biên bản xác nhận khoản tài trợ',
    loaiKhongHopLe: 'Loại giấy in không hợp lệ.',
  },
};
