export const matTranHangHoa = {
  noViewPermission: 'Bạn không có quyền xem module Hàng hóa.',
  tabDanhMuc: 'Danh mục',
  tabHangHoa: 'Hàng hóa',
  filterDanhMucPlaceholder: 'Danh mục',
  filterDanhMucAll: 'Tất cả danh mục',
  filterMoTaChipPlaceholder: 'Mô tả',
  filterMoTaHas: 'Có mô tả',
  filterMoTaEmpty: 'Không mô tả',
  deleteTitle: 'Xóa danh mục?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều danh mục?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  deleteHangTitle: 'Xóa hàng hóa?',
  deleteHangMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteHangTitle: 'Xóa nhiều hàng?',
  bulkDeleteHangMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileNameDanhMuc: 'danh-muc-hang-hoa',
  exportFileNameHangHoa: 'danh-sach-hang-hoa',
  toast: {
    createDanhMuc: 'Đã thêm danh mục.',
    updateDanhMuc: 'Đã cập nhật danh mục.',
    deleteDanhMuc: 'Đã xóa {{count}} danh mục.',
    createHang: 'Đã thêm hàng hóa.',
    updateHang: 'Đã cập nhật hàng hóa.',
    deleteHang: 'Đã xóa {{count}} hàng hóa.',
  },
  service: {
    notFoundDanhMuc: 'Không tìm thấy danh mục.',
    notFoundHang: 'Không tìm thấy hàng hóa.',
    deleteDanhMucBlocked: 'Không thể xóa danh mục đang có hàng hóa. Hãy xóa hoặc chuyển hàng sang danh mục khác, hoặc đặt trạng thái Ngừng hoạt động.',
  },
  validation: {
    tenDanhMucRequired: 'Nhập tên danh mục.',
    tenHangRequired: 'Nhập tên hàng hóa.',
    donViTinhRequired: 'Nhập đơn vị tính.',
    danhMucRequired: 'Chọn danh mục.',
  },
  store: {
    thuTu: 'Thứ tự',
    tenDanhMuc: 'Tên danh mục',
    tenHangHoa: 'Tên hàng',
    tenNhom: 'Danh mục',
    donViTinh: 'Đơn vị tính',
    quyCach: 'Quy cách',
    moTa: 'Mô tả',
    trangThai: 'Trạng thái',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật',
  },
  emptyDanhMuc: 'Chưa có danh mục',
  emptyHang: 'Chưa có hàng hóa',
  addHangNeedDanhMuc: 'Vui lòng thêm ít nhất một danh mục trước khi thêm hàng hóa.',
  formDanhMuc: {
    section: 'Thông tin danh mục',
    createSubtitle: 'Thêm danh mục nhóm hàng',
    editSubtitle: 'Sửa danh mục',
    thuTuAutoHint: 'Thứ tự gợi ý: tiếp theo trong danh sách danh mục.',
  },
  formHang: {
    section: 'Thông tin hàng hóa',
    createSubtitle: 'Thêm mặt hàng cứu trợ',
    editSubtitle: 'Sửa hàng hóa',
    danhMuc: 'Danh mục',
    donViHint: 'Chọn từ danh sách hoặc gõ trong ô tìm rồi chọn « Dùng đơn vị… » để thêm ĐVT mới.',
    donViCreatableAction: 'Dùng đơn vị « {{unit}} »',
    donViSearchPlaceholder: 'Tìm hoặc nhập đơn vị…',
    thuTuAutoHint: 'Thứ tự gợi ý: tiếp theo trong danh mục (đổi danh mục sẽ cập nhật lại).',
  },
  detailDanhMuc: {
    title: 'Chi tiết danh mục',
    section: 'Thông tin',
    system: 'Thông tin hệ thống',
    sectionHangHoa: 'Hàng hóa trong danh mục',
    noHangHoa: 'Chưa có hàng hóa',
    noHangHoaHint: 'Thêm hàng để ghi nhận vật tư cứu trợ thuộc danh mục này.',
  },
  detailHang: {
    title: 'Chi tiết hàng hóa',
    section: 'Thông tin',
    system: 'Thông tin hệ thống',
  },
};
