export const matTranHangHoa = {
  noViewPermission: 'Bạn không có quyền xem module Hàng hóa.',
  tabDanhMuc: 'Danh mục',
  tabHangHoa: 'Hàng hóa',
  filterDanhMucPlaceholder: 'Danh mục',
  filterDanhMucAll: 'Tất cả danh mục',
  filterMoTaChipPlaceholder: 'Mô tả',
  filterMoTaHas: 'Có mô tả',
  filterMoTaEmpty: 'Không mô tả',
  filterTrangThaiPlaceholder: 'Trạng thái',
  deleteTitle: 'Xóa danh mục?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều danh mục?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  deleteHangTitle: 'Xóa hàng hóa?',
  deleteHangMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteHangTitle: 'Xóa nhiều hàng?',
  bulkDeleteHangMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileNameDanhMuc: 'danh-muc-hang-hoa',
  exportFileNameHangHoa: 'danh-sach-hang-hoa',
  toast: {
    createDanhMuc: 'Đã thêm danh mục.',
    updateDanhMuc: 'Đã cập nhật danh mục.',
    deleteDanhMuc: 'Đã xóa {{count}} danh mục.',
    createHang: 'Đã thêm hàng hóa.',
    updateHang: 'Đã cập nhật hàng hóa.',
    deleteHang: 'Đã xóa {{count}} hàng hóa.',
  },
  service: {
    notFoundDanhMuc: 'Không tìm thấy danh mục.',
    notFoundHang: 'Không tìm thấy hàng hóa.',
    deleteDanhMucBlocked: 'Không thể xóa danh mục đang có hàng hóa. Hãy xóa hoặc chuyển hàng sang danh mục khác, hoặc đặt trạng thái Ngừng hoạt động.',
  },
  validation: {
    tenDanhMucRequired: 'Nhập tên danh mục.',
    tenHangRequired: 'Nhập tên hàng hóa.',
    donViTinhRequired: 'Nhập đơn vị tính.',
    danhMucRequired: 'Chọn danh mục.',
  },
  store: {
    thuTu: 'Thứ tự',
    tenDanhMuc: 'Tên danh mục',
    tenHangHoa: 'Tên hàng',
    tenNhom: 'Danh mục',
    donViTinh: 'Đơn vị tính',
    quyCach: 'Quy cách',
    moTa: 'Mô tả',
    trangThai: 'Trạng thái',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật',
  },
  emptyDanhMuc: 'Chưa có danh mục',
  emptyHang: 'Chưa có hàng hóa',
  addHangNeedDanhMuc: 'Vui lòng thêm ít nhất một danh mục trước khi thêm hàng hóa.',
  formDanhMuc: {
    section: 'Thông tin danh mục',
    createSubtitle: 'Thêm danh mục nhóm hàng',
    editSubtitle: 'Sửa danh mục',
    thuTuAutoHint: 'Thứ tự gợi ý: tiếp theo trong danh sách danh mục.',
  },
  formHang: {
    section: 'Thông tin hàng hóa',
    createSubtitle: 'Thêm mặt hàng cứu trợ',
    editSubtitle: 'Sửa hàng hóa',
    danhMuc: 'Danh mục',
    donViHint: 'Chọn từ danh sách hoặc gõ trong ô tìm rồi chọn « Dùng đơn vị… » để thêm ĐVT mới.',
    donViCreatableAction: 'Dùng đơn vị « {{unit}} »',
    donViSearchPlaceholder: 'Tìm hoặc nhập đơn vị…',
    thuTuAutoHint: 'Thứ tự gợi ý: tiếp theo trong danh mục (đổi danh mục sẽ cập nhật lại).',
  },
  detailDanhMuc: {
    title: 'Chi tiết danh mục',
    section: 'Thông tin',
    system: 'Thông tin hệ thống',
    sectionHangHoa: 'Hàng hóa trong danh mục',
    noHangHoa: 'Chưa có hàng hóa',
    noHangHoaHint: 'Thêm hàng để ghi nhận vật tư cứu trợ thuộc danh mục này.',
  },
  detailHang: {
    title: 'Chi tiết hàng hóa',
    section: 'Thông tin',
    system: 'Thông tin hệ thống',
  },
  import: {
    templateFileNameDanhMuc: 'mau-nhap-danh-muc-hang-hoa',
    templateFileNameHangHoa: 'mau-nhap-hang-hoa',
    colTenDanhMuc: 'Tên danh mục',
    colDanhMuc: 'Danh mục',
    colTenHangHoa: 'Tên hàng hóa',
    colDonViTinh: 'Đơn vị tính',
    colQuyCach: 'Quy cách',
    colMoTa: 'Mô tả',
    colThuTu: 'Thứ tự',
    colTrangThai: 'Trạng thái',
    rowPrefix: 'Dòng {{row}}: ',
    errTenDanhMucEmpty: 'chưa điền Tên danh mục.',
    errDanhMucTrungHeThong: 'danh mục « {{ten}} » đã có trong hệ thống, không thêm lại.',
    errDanhMucTrungFile: 'tên danh mục « {{ten}} » đã xuất hiện ở dòng {{row}} trong cùng file.',
    errDanhMucEmpty: 'chưa điền Danh mục của hàng hóa.',
    errDanhMucNotFound:
      'không tìm thấy danh mục « {{ten}} ». Xem sheet « Danh mục » trong file mẫu để điền đúng tên, hoặc thêm danh mục trước rồi nhập lại.',
    errTenHangEmpty: 'chưa điền Tên hàng hóa.',
    errDonViTinhEmpty: 'chưa điền Đơn vị tính (kg, thùng, bao…).',
    errHangTrungHeThong: 'hàng « {{ten}} » đã có trong danh mục « {{danh_muc}} », không thêm lại.',
    errHangTrungFile: 'hàng « {{ten}} » đã xuất hiện ở dòng {{row}} trong cùng file.',
    errTrangThai:
      'Trạng thái « {{gia_tri}} » không hợp lệ. Chỉ điền « Đang hoạt động » hoặc « Ngừng hoạt động », hoặc để trống.',
    errThuTu: 'Thứ tự « {{gia_tri}} » không hợp lệ. Điền số nguyên từ 0 trở lên, hoặc để trống để hệ thống tự đánh số.',
    errTooManyRows:
      'File có {{count}} dòng, vượt mức {{max}} dòng cho một lần nhập. Hãy tách file nhỏ hơn rồi nhập từng lần.',
    errSummary: 'Tổng cộng {{count}} dòng lỗi. Bấm « Tải file dòng lỗi » bên dưới để xem đầy đủ và sửa.',
    toastSuccessDanhMuc: 'Đã nhập {{count}} danh mục từ Excel.',
    toastSuccessHangHoa: 'Đã nhập {{count}} hàng hóa từ Excel.',
    sheetHuongDan: 'Hướng dẫn',
    sheetDanhMuc: 'Danh mục',
    huongDanColKey: 'Cột',
    huongDanColVal: 'Cách điền',
    refColId: 'ID',
    refColTen: 'Tên danh mục',
    hdDanhMuc1k: 'Tên danh mục',
    hdDanhMuc1v: 'Bắt buộc. Trùng tên đã có trong hệ thống sẽ bị báo lỗi, không ghi đè.',
    hdDanhMuc2k: 'Mô tả',
    hdDanhMuc2v: 'Không bắt buộc.',
    hdDanhMuc3k: 'Thứ tự',
    hdDanhMuc3v: 'Số nguyên ≥ 0. Để trống thì hệ thống tự đánh số tiếp theo.',
    hdDanhMuc4k: 'Trạng thái',
    hdDanhMuc4v: '« Đang hoạt động » hoặc « Ngừng hoạt động ». Để trống = Đang hoạt động.',
    hdHang1k: 'Danh mục',
    hdHang1v: 'Bắt buộc. Điền ĐÚNG tên danh mục (xem sheet « Danh mục ») hoặc số ID của danh mục.',
    hdHang2k: 'Tên hàng hóa',
    hdHang2v: 'Bắt buộc. Trùng tên trong cùng danh mục sẽ bị báo lỗi, không ghi đè.',
    hdHang3k: 'Đơn vị tính',
    hdHang3v: 'Bắt buộc. Ví dụ: kg, thùng, bao, cái, lít.',
    hdHang4k: 'Quy cách / Mô tả',
    hdHang4v: 'Không bắt buộc.',
    hdHang5k: 'Thứ tự',
    hdHang5v: 'Số nguyên ≥ 0. Để trống thì hệ thống tự đánh số tiếp trong danh mục.',
    hdHang6k: 'Trạng thái',
    hdHang6v: '« Đang hoạt động » hoặc « Ngừng hoạt động ». Để trống = Đang hoạt động.',
  },
};
