export const nhaDaiDoanKet = {
  tabs: {
    danhSach: 'Danh sách',
    thongKe: 'Thống kê',
  },
  noViewPermission: 'Bạn không có quyền xem module Nhà đại đoàn kết.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập nhà thuộc xã/phường của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có hồ sơ nhà đại đoàn kết',
  exportFileName: 'Nha_Dai_Doan_Ket',
  deleteTitle: 'Xóa hồ sơ',
  deleteMessage: 'Bạn có chắc muốn xóa hồ sơ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều hồ sơ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} hồ sơ đã chọn? Hành động không hoàn tác.',
  detailTitle: 'Chi tiết nhà đại đoàn kết',
  detail: {
    systemInfo: 'Thông tin hệ thống',
    ngayTrangThaiHint: 'Máy chủ tự ghi khi trạng thái thay đổi.',
    actionChangeStatus: 'Chuyển trạng thái',
    actionEdit: 'Sửa hồ sơ',
    actionDelete: 'Xóa hồ sơ',
    moHoNgheo: 'Mở hồ sơ hộ nghèo',
    chuaGanHo: 'Chưa gắn hộ — sửa hồ sơ để chọn hộ',
  },
  printPreview: {
    actionPrint: 'In biên bản',
    chonPhieuTitle: 'Chọn biên bản cần in',
    phieuKhaoSat: 'Biên bản khảo sát',
    phieuHoanThanh: 'Biên bản kiểm tra hoàn thành',
    phieuBanGiao: 'Biên bản bàn giao',
    moTaKhaoSat: 'Phiếu khảo sát hộ khó khăn về nhà ở',
    moTaHoanThanh: 'Kiểm tra việc hoàn thành xây dựng (sửa chữa) nhà ở',
    moTaBanGiao: 'Bàn giao tiền mặt hỗ trợ xây mới (sửa chữa) nhà ở',
    notFound: 'Không tìm thấy hồ sơ nhà đại đoàn kết.',
    loaiPhieuKhongHopLe: 'Loại biên bản không hợp lệ.',
    printPopupBlocked: 'Trình duyệt đã chặn cửa sổ in. Hãy cho phép cửa sổ bật lên rồi thử lại.',
  },
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái hồ sơ và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
    noApproveHint:
      'Bạn không có quyền Duyệt nên không chọn được "Đã phê duyệt". Các bước còn lại vẫn đổi được.',
  },
  store: {
    namCol: 'Năm',
    noiDungCol: 'Nội dung hỗ trợ',
    nguonCol: 'Nguồn',
    nguonHoTroCol: 'Nguồn hỗ trợ',
    chuHoCol: 'Họ và tên chủ hộ',
    xaPhuongCol: 'Xã phường',
    khoiXomCol: 'Khối xóm',
    doiTuongCol: 'Đối tượng',
    loaiHinhCol: 'Loại hình hỗ trợ',
    soTienCol: 'Số tiền',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Ngày cập nhật trạng thái',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm hồ sơ nhà đại đoàn kết',
    editSubtitle: 'Cập nhật hồ sơ',
    sectionHoDan: 'Hộ gia đình',
    sectionHoTro: 'Nội dung & nguồn hỗ trợ',
    sectionTrangThai: 'Trạng thái',
    soTienPlaceholder: 'Để trống nếu chưa chốt mức hỗ trợ',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
    hoNgheoLabel: 'Hộ nghèo',
    hoNgheoPlaceholder: 'Tìm theo tên hoặc số căn cước…',
    hoNgheoHint: 'Họ tên, xã phường, khối xóm, đối tượng lấy theo hồ sơ hộ. Chưa có hộ thì thêm ở Thông tin đối tượng hỗ trợ trước.',
    sectionKhaoSat: 'Biên bản khảo sát',
    sectionHoanThanh: 'Biên bản kiểm tra hoàn thành',
    sectionBanGiao: 'Biên bản bàn giao',
    chonPlaceholder: 'Chọn',
    nguoiPlaceholder: 'Chọn cán bộ hoặc gõ tên',
    nguoiSearchPlaceholder: 'Tìm cán bộ hoặc gõ tên người khác…',
    nguoiCreatable: 'Dùng tên « {{ten}} »',
    chucVuLabel: 'Chức vụ',
    themDaiDienThon: 'Thêm đại diện thôn/xóm',
    themNguonKhac: 'Thêm nguồn khác',
    xoaDong: 'Xóa dòng',
    tongGiaTriHint: 'Gồm cả phần Chương trình hỗ trợ (ô Số tiền) và các nguồn khác bên dưới.',
    soQuyetDinhPlaceholder: 'VD: 12/QĐ-BVĐ',
  },
  /** Nhãn các ô biên bản — dùng chung cho form và màn chi tiết. */
  bienBan: {
    ngayKhaoSat: 'Ngày khảo sát',
    nhuCauHoTro: 'Nhu cầu cần hỗ trợ',
    hienTrangNha: 'Hiện trạng nhà ở',
    hoanCanhGiaDinh: 'Hoàn cảnh gia đình',
    ghiChuKhaoSat: 'Ghi chú khảo sát',
    ngayKiemTra: 'Ngày kiểm tra hoàn thành',
    dienTichSan: 'Diện tích sàn (m²)',
    thanhPhanKiemTra: 'Thành phần kiểm tra',
    daiDienBcd: 'Đại diện Ban Chỉ đạo xã/phường',
    daiDienUbnd: 'Đại diện UBND xã/phường',
    daiDienUbndPlaceholder: 'Nhập họ tên đại diện UBND',
    daiDienMttq: 'Đại diện MTTQ xã/phường',
    daiDienThonN: 'Đại diện thôn/xóm {{n}}',
    phanNen: 'Phần nền',
    phanMai: 'Phần mái',
    phanKhungTuong: 'Phần khung, tường bao',
    tongGiaTri: 'Tổng giá trị xây dựng/sửa chữa',
    nguonKhacTenN: 'Nguồn khác {{n}}',
    ngayBanGiao: 'Ngày bàn giao',
    diaDiemBanGiao: 'Địa điểm bàn giao',
    benGiaoTien: 'Đại diện bên giao tiền',
    benLamChung: 'Bên làm chứng (cán bộ thôn/xóm)',
    soQuyetDinh: 'Số quyết định hỗ trợ',
    ngayQuyetDinh: 'Ngày quyết định',
  },
  toast: {
    create: 'Đã thêm hồ sơ',
    update: 'Đã cập nhật hồ sơ',
    delete: 'Đã xóa {{count}} hồ sơ',
    statusChange: 'Đã chuyển trạng thái hồ sơ',
  },
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập.',
    notFound: 'Không tìm thấy hồ sơ',
  },
  validation: {
    noiDungRequired: 'Nhập nội dung hỗ trợ',
    chuHoRequired: 'Nhập họ tên chủ hộ',
    hoNgheoRequired: 'Chọn hộ trong Thông tin đối tượng hỗ trợ',
    namInvalid: 'Năm phải từ 2000 đến 2100',
    nguonInvalid: 'Chọn nguồn hợp lệ',
    nguonHoTroInvalid: 'Chọn nguồn hỗ trợ hợp lệ',
    doiTuongInvalid: 'Chọn đối tượng hợp lệ',
    loaiHinhInvalid: 'Chọn loại hình hỗ trợ hợp lệ',
    trangThaiInvalid: 'Chọn trạng thái hợp lệ',
    soTienInvalid: 'Số tiền không hợp lệ',
    soTienMin: 'Số tiền không được âm',
    ngayInvalid: 'Ngày không hợp lệ',
    dienTichInvalid: 'Diện tích phải là số không âm',
  },
};
