export const nhaDaiDoanKet = {
  tabs: {
    danhSach: 'Danh sách',
    thongKe: 'Thống kê',
  },
  noViewPermission: 'Bạn không có quyền xem module Nhà đại đoàn kết.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập nhà thuộc xã/phường của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có hồ sơ nhà đại đoàn kết',
  exportFileName: 'Nha_Dai_Doan_Ket',
  deleteTitle: 'Xóa hồ sơ',
  deleteMessage: 'Bạn có chắc muốn xóa hồ sơ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều hồ sơ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} hồ sơ đã chọn? Hành động không hoàn tác.',
  detailTitle: 'Chi tiết nhà đại đoàn kết',
  detail: {
    systemInfo: 'Thông tin hệ thống',
    ngayTrangThaiHint: 'Máy chủ tự ghi khi trạng thái thay đổi.',
    actionChangeStatus: 'Chuyển trạng thái',
    actionEdit: 'Sửa hồ sơ',
    actionDelete: 'Xóa hồ sơ',
    moHoNgheo: 'Mở hồ sơ hộ nghèo',
    chuaGanHo: 'Chưa gắn hộ — sửa hồ sơ để chọn hộ',
  },
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái hồ sơ và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
    noApproveHint:
      'Bạn không có quyền Duyệt nên không chọn được "Đã phê duyệt". Các bước còn lại vẫn đổi được.',
  },
  store: {
    namCol: 'Năm',
    noiDungCol: 'Nội dung hỗ trợ',
    nguonCol: 'Nguồn',
    nguonHoTroCol: 'Nguồn hỗ trợ',
    chuHoCol: 'Họ và tên chủ hộ',
    xaPhuongCol: 'Xã phường',
    khoiXomCol: 'Khối xóm',
    doiTuongCol: 'Đối tượng',
    loaiHinhCol: 'Loại hình hỗ trợ',
    soTienCol: 'Số tiền',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Ngày cập nhật trạng thái',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm hồ sơ nhà đại đoàn kết',
    editSubtitle: 'Cập nhật hồ sơ',
    sectionHoDan: 'Hộ gia đình',
    sectionHoTro: 'Nội dung & nguồn hỗ trợ',
    sectionTrangThai: 'Trạng thái',
    soTienPlaceholder: 'Để trống nếu chưa chốt mức hỗ trợ',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
    hoNgheoLabel: 'Hộ nghèo',
    hoNgheoPlaceholder: 'Tìm theo tên hoặc số căn cước…',
    hoNgheoHint: 'Họ tên, xã phường, khối xóm, đối tượng lấy theo hồ sơ hộ. Chưa có hộ thì thêm ở Thông tin hộ nghèo trước.',
  },
  toast: {
    create: 'Đã thêm hồ sơ',
    update: 'Đã cập nhật hồ sơ',
    delete: 'Đã xóa {{count}} hồ sơ',
    statusChange: 'Đã chuyển trạng thái hồ sơ',
  },
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập.',
    notFound: 'Không tìm thấy hồ sơ',
  },
  validation: {
    noiDungRequired: 'Nhập nội dung hỗ trợ',
    chuHoRequired: 'Nhập họ tên chủ hộ',
    hoNgheoRequired: 'Chọn hộ trong Thông tin hộ nghèo',
    namInvalid: 'Năm phải từ 2000 đến 2100',
    nguonInvalid: 'Chọn nguồn hợp lệ',
    nguonHoTroInvalid: 'Chọn nguồn hỗ trợ hợp lệ',
    doiTuongInvalid: 'Chọn đối tượng hợp lệ',
    loaiHinhInvalid: 'Chọn loại hình hỗ trợ hợp lệ',
    trangThaiInvalid: 'Chọn trạng thái hợp lệ',
    soTienInvalid: 'Số tiền không hợp lệ',
    soTienMin: 'Số tiền không được âm',
  },
};
