import type { MttqCanBo } from './core/types';

/** Dữ liệu mẫu khi chạy không có Supabase (MockRepository). */
export const MTTQ_CAN_BO_MOCK_DATA: MttqCanBo[] = [
  {
    id: '90001',
    to_chuc_ids: [],
    ho_ten: 'Nguyễn Văn A',
    ngay_sinh: '1985-03-15',
    gioi_tinh: 'Nam',
    dan_toc_id: null,
    ton_giao: 'Không',
    dia_chi: 'Thành phố Vinh',
    dang_vien: true,
    trinh_do_id: null,
    ly_luan_chinh_tri_id: null,
    dien_thoai: '0912345678',
    chuc_vu_id: null,
    phong_ban_id: null,
    don_vi_id: null,
    ngay_tham_gia_to_chuc: '2010-01-01',
    trang_thai_id: null,
    ngay_nhap_trang_thai: '2024-07-31',
    van_hoa: '12/12',
    ngay_vao_dang: null,
    que_quan: null,
    noi_o_hien_nay: null,
    id_nguoi_tao: '1',
    tg_tao: new Date().toISOString(),
    tg_cap_nhat: new Date().toISOString(),
    ten_to_chuc_arr: [],
    ten_dan_toc: null,
    ten_trinh_do: null,
    ten_ly_luan_chinh_tri: null,
    ten_chuc_vu: null,
    ten_phong_ban: null,
    ten_bo_phan: null,
    ten_don_vi: null,
    ten_trang_thai: null,
    ho_va_ten_nguoi_tao: 'Quản trị',
    ten_tai_khoan_nguoi_tao: 'admin',
  },
  {
    id: '90002',
    to_chuc_ids: [],
    ho_ten: 'Trần Thị B',
    ngay_sinh: '1992-07-22',
    gioi_tinh: 'Nữ',
    dan_toc_id: null,
    ton_giao: 'Có',
    dia_chi: null,
    dang_vien: false,
    trinh_do_id: null,
    ly_luan_chinh_tri_id: null,
    dien_thoai: null,
    chuc_vu_id: null,
    phong_ban_id: null,
    don_vi_id: null,
    ngay_tham_gia_to_chuc: null,
    trang_thai_id: null,
    ngay_nhap_trang_thai: null,
    van_hoa: null,
    ngay_vao_dang: null,
    que_quan: null,
    noi_o_hien_nay: null,
    id_nguoi_tao: '1',
    tg_tao: new Date().toISOString(),
    tg_cap_nhat: new Date().toISOString(),
    ten_to_chuc_arr: [],
    ten_dan_toc: null,
    ten_trinh_do: null,
    ten_ly_luan_chinh_tri: null,
    ten_chuc_vu: null,
    ten_phong_ban: null,
    ten_bo_phan: null,
    ten_don_vi: null,
    ten_trang_thai: null,
    ho_va_ten_nguoi_tao: 'Quản trị',
    ten_tai_khoan_nguoi_tao: 'admin',
  },
];
