import type { MttqCanBo } from './core/types';

/** Dữ liệu mẫu khi chạy không có Supabase (MockRepository). */
export const MTTQ_CAN_BO_MOCK_DATA: MttqCanBo[] = [
  {
    id: '90001',
    cap_quan_ly_id: null,
    to_chuc_id: null,
    ho_ten: 'Nguyễn Văn A',
    ngay_sinh: '1985-03-15',
    gioi_tinh: 'Nam',
    dan_toc_id: null,
    ton_giao: null,
    dia_chi: 'Thành phố Vinh',
    dang_vien: true,
    trinh_do_id: null,
    ly_luan_chinh_tri_id: null,
    dien_thoai: '0912345678',
    chuc_vu_id: null,
    ngay_tham_gia_to_chuc: '2010-01-01',
    trang_thai_id: null,
    ngay_nhap_trang_thai: null,
    id_nguoi_tao: '1',
    tg_tao: new Date().toISOString(),
    tg_cap_nhat: new Date().toISOString(),
    ten_cap_quan_ly: null,
    ten_to_chuc: null,
    ten_dan_toc: null,
    ten_trinh_do: null,
    ten_ly_luan_chinh_tri: null,
    ten_chuc_vu: null,
    ten_trang_thai: null,
    ho_va_ten_nguoi_tao: 'Quản trị',
    ten_tai_khoan_nguoi_tao: 'admin',
  },
  {
    id: '90002',
    cap_quan_ly_id: null,
    to_chuc_id: null,
    ho_ten: 'Trần Thị B',
    ngay_sinh: '1992-07-22',
    gioi_tinh: 'Nữ',
    dan_toc_id: null,
    ton_giao: 'Phật giáo',
    dia_chi: null,
    dang_vien: false,
    trinh_do_id: null,
    ly_luan_chinh_tri_id: null,
    dien_thoai: null,
    chuc_vu_id: null,
    ngay_tham_gia_to_chuc: null,
    trang_thai_id: null,
    ngay_nhap_trang_thai: null,
    id_nguoi_tao: '1',
    tg_tao: new Date().toISOString(),
    tg_cap_nhat: new Date().toISOString(),
    ten_cap_quan_ly: null,
    ten_to_chuc: null,
    ten_dan_toc: null,
    ten_trinh_do: null,
    ten_ly_luan_chinh_tri: null,
    ten_chuc_vu: null,
    ten_trang_thai: null,
    ho_va_ten_nguoi_tao: 'Quản trị',
    ten_tai_khoan_nguoi_tao: 'admin',
  },
];
