/** Chuỗi module Danh sách cán bộ MTTQ — flatten vào STRINGS với prefix `matTranCanBo` */
export const matTranCanBo = {
  store: {
    hoTenCol: 'Họ tên',
    ngaySinhCol: 'Ngày sinh',
    tuoiCol: 'Tuổi',
    gioiTinhCol: 'Giới tính',
    trangThaiCol: 'Trạng thái',
    chucVuCol: 'Chức vụ',
    toChucCol: 'Tổ chức',
    dienThoaiCol: 'Điện thoại',
    dangVienCol: 'Đảng viên',
    capQuanLyCol: 'Cấp quản lý',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    sectionNhanThan: 'Nhân thân',
    sectionToChuc: 'Tổ chức',
    sectionHocVan: 'Học vấn & chính trị',
    sectionLienHe: 'Liên hệ',
    sectionTrangThai: 'Trạng thái',
    hoTen: 'Họ tên',
    ngaySinh: 'Ngày sinh',
    gioiTinh: 'Giới tính',
    danToc: 'Dân tộc',
    tonGiao: 'Tôn giáo',
    dangVien: 'Đảng viên',
    capQuanLy: 'Cấp quản lý',
    toChuc: 'Tổ chức',
    chucVu: 'Chức vụ',
    ngayThamGiaToChuc: 'Ngày tham gia tổ chức',
    trinhDo: 'Trình độ',
    lyLuanChinhTri: 'Lý luận chính trị',
    diaChi: 'Địa chỉ cơ quan / nơi cư trú',
    dienThoai: 'Điện thoại',
    trangThai: 'Trạng thái',
    ngayNhapTrangThai: 'Ngày nhập trạng thái',
    createSubtitle: 'Thêm cán bộ mới',
    editSubtitle: 'Cập nhật hồ sơ cán bộ',
  },
  display: {
    /** {{years}} = số tuổi */
    ageYears: '{{years}} tuổi',
  },
  detail: {
    title: 'Chi tiết cán bộ',
    subtitle: 'Hồ sơ theo thiết lập MTTQ',
    sectionNhanThan: 'Nhân thân',
    sectionToChuc: 'Tổ chức',
    sectionHocVan: 'Học vấn & chính trị',
    sectionLienHe: 'Liên hệ',
    sectionTrangThai: 'Trạng thái',
    sectionHeThong: 'Hệ thống',
    sectionKhenThuong: 'Khen thưởng liên quan',
    khenThuongHint: 'Các quyết định có dòng chi tiết gắn cán bộ này.',
    khenThuongEmpty: 'Chưa có dòng khen thưởng nào gắn cán bộ.',
    khenThuongOpenModule: 'Mở danh sách khen thưởng',
    khenThuongOpenRow: 'Mở quyết định',
    khenThuongActionsCol: 'Thao tác',
    dangVienYes: 'Có',
    dangVienNo: 'Không',
    creator: 'Người tạo',
    createdAt: 'Thời điểm tạo',
    updatedAt: 'Cập nhật lần cuối',
  },
  deleteTitle: 'Xóa cán bộ',
  deleteMessage: 'Bạn có chắc muốn xóa hồ sơ cán bộ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều cán bộ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} hồ sơ đã chọn? Hành động không hoàn tác.',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'Danh_Sach_Can_Bo_MTTQ',
  toast: {
    create: 'Đã thêm cán bộ',
    update: 'Đã cập nhật cán bộ',
    delete: 'Đã xóa {{count}} hồ sơ',
  },
  service: {
    notFound: 'Không tìm thấy cán bộ',
    noEmployeeProfile:
      'Tài khoản chưa gắn hồ sơ nhân viên. Liên hệ quản trị để được gán trước khi thêm cán bộ.',
  },
  validation: {
    hoTenRequired: 'Nhập họ tên',
    gioiTinhRequired: 'Chọn giới tính',
    dateInvalid: 'Ngày không hợp lệ',
  },
  emptyTitle: 'Chưa có cán bộ',
  emptyHint: 'Thêm hồ sơ mới hoặc điều chỉnh bộ lọc.',
  noViewPermission: 'Bạn không có quyền xem module Danh sách cán bộ.',
  searchPlaceholder: 'Tìm theo họ tên, tổ chức, chức vụ, trạng thái…',
  noEmployeeBanner:
    'Tài khoản chưa gắn hồ sơ nhân viên: không thể tạo mới cán bộ cho đến khi được gán nhân viên. Liên hệ quản trị.',
} as const;
