/** Chuỗi module Danh sách cán bộ MTTQ — flatten vào STRINGS với prefix `matTranCanBo` */
export const matTranCanBo = {
  store: {
    hoTenCol: 'Họ tên',
    ngaySinhCol: 'Ngày sinh',
    tuoiCol: 'Tuổi',
    gioiTinhCol: 'Giới tính',
    trangThaiCol: 'Trạng thái',
    chucVuCol: 'Chức vụ',
    capQuanLyCol: 'Cấp quản lý',
    toChucCol: 'Tổ chức',
    phongBanCol: 'Phòng ban',
    dienThoaiCol: 'Điện thoại',
    dangVienCol: 'Đảng viên',
    donViCol: 'Đơn vị (xã/phường)',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    sectionNhanThan: 'Nhân thân',
    sectionToChuc: 'Tổ chức',
    sectionHocVan: 'Học vấn & chính trị',
    sectionLienHe: 'Liên hệ',
    sectionTrangThai: 'Trạng thái',
    hoTen: 'Họ tên',
    ngaySinh: 'Ngày sinh',
    gioiTinh: 'Giới tính',
    danToc: 'Dân tộc',
    tonGiao: 'Tôn giáo',
    dangVien: 'Đảng viên',
    toChuc: 'Tổ chức',
    phongBan: 'Phòng ban',
    chucVu: 'Chức vụ',
    capQuanLy: 'Cấp quản lý (theo chức vụ)',
    capQuanLyHint: 'Tự điền từ chức vụ đã chọn (Tỉnh / Xã phường).',
    capQuanLyChuaGan: 'Chưa gán / không áp dụng',
    donVi: 'Đơn vị (xã/phường)',
    donViHint: 'Bắt buộc khi chức vụ có cấp quản lý « Xã phường ».',
    ngayThamGiaToChuc: 'Ngày tham gia tổ chức',
    trinhDo: 'Trình độ',
    lyLuanChinhTri: 'Lý luận chính trị',
    diaChi: 'Địa chỉ cơ quan / nơi cư trú',
    dienThoai: 'Điện thoại',
    trangThai: 'Trạng thái',
    ngayNhapTrangThai: 'Ngày nhập trạng thái',
    vanHoa: 'Văn hóa',
    ngayVaoDang: 'Ngày vào Đảng',
    queQuan: 'Quê quán',
    noiOHienNay: 'Nơi ở hiện nay',
    createSubtitle: 'Thêm cán bộ mới',
    editSubtitle: 'Cập nhật hồ sơ cán bộ',
  },
  display: {
    /** {{years}} = số tuổi */
    ageYears: '{{years}} tuổi',
  },
  detail: {
    title: 'Chi tiết cán bộ',
    subtitle: 'Hồ sơ theo thiết lập MTTQ',
    sectionNhanThan: 'Nhân thân',
    sectionToChuc: 'Tổ chức',
    sectionHocVan: 'Học vấn & chính trị',
    sectionLienHe: 'Liên hệ',
    sectionTrangThai: 'Trạng thái',
    sectionHeThong: 'Hệ thống',
    sectionKhenThuong: 'Khen thưởng',
    khenThuongChildRecordsSuffix: 'dòng',
    khenThuongHint: 'Các quyết định có dòng chi tiết gắn cán bộ này.',
    khenThuongEmpty: 'Chưa có dòng khen thưởng nào gắn cán bộ.',
    khenThuongOpenModule: 'Mở khen thưởng',
    khenThuongOpenRow: 'Mở quyết định',
    khenThuongActionsCol: 'Thao tác',
    sectionTangLuong: 'Lịch sử tăng lương',
    tangLuongChildRecordsSuffix: 'bản ghi',
    tangLuongHint: 'Các lần nâng lương đã ghi nhận cho cán bộ này.',
    tangLuongEmpty: 'Chưa có lịch sử tăng lương.',
    tangLuongOpenModule: 'Xem tất cả',
    tangLuongOpenRow: 'Mở chi tiết',
    tangLuongActionsCol: 'Thao tác',
    tangLuongCurrentGrade: 'Ngạch/bậc hiện tại (theo lịch sử gần nhất)',
    sectionTapHuan: 'Tập huấn',
    tapHuanChildRecordsSuffix: 'lớp',
    tapHuanHint: 'Các lớp tập huấn có danh sách tham gia gồm cán bộ này.',
    tapHuanEmpty: 'Chưa có lớp tập huấn nào ghi nhận cán bộ.',
    tapHuanOpenModule: 'Mở tập huấn',
    tapHuanOpenRow: 'Mở lớp',
    tapHuanActionsCol: 'Thao tác',
    dangVienYes: 'Có',
    dangVienNo: 'Không',
    creator: 'Người tạo',
    createdAt: 'Thời điểm tạo',
    updatedAt: 'Cập nhật lần cuối',
  },
  deleteTitle: 'Xóa cán bộ',
  deleteMessage: 'Bạn có chắc muốn xóa hồ sơ cán bộ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều cán bộ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} hồ sơ đã chọn? Hành động không hoàn tác.',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'Danh_Sach_Can_Bo_MTTQ',
  toast: {
    create: 'Đã thêm cán bộ',
    update: 'Đã cập nhật cán bộ',
    delete: 'Đã xóa {{count}} hồ sơ',
  },
  service: {
    notFound: 'Không tìm thấy cán bộ',
    noEmployeeProfile:
      'Tài khoản chưa gắn hồ sơ nhân viên. Liên hệ quản trị để được gán trước khi thêm cán bộ.',
  },
  validation: {
    hoTenRequired: 'Nhập họ tên',
    gioiTinhRequired: 'Chọn giới tính',
    dateInvalid: 'Ngày không hợp lệ',
    ngaySinhRequired: 'Chọn ngày sinh',
    danTocRequired: 'Chọn dân tộc',
    tonGiaoRequired: 'Nhập tôn giáo (có thể ghi « Không » nếu không theo)',
    diaChiRequired: 'Nhập địa chỉ',
    dienThoaiRequired: 'Nhập số điện thoại',
    toChucRequired: 'Chọn tổ chức',
    phongBanRequired: 'Chọn phòng ban',
    chucVuPhongBanMismatch: 'Chức vụ không thuộc phòng ban đã chọn (kể cả chức vụ gắn bộ phận con).',
    donViRequired: 'Chọn xã/phường (bắt buộc với chức vụ cấp xã phường).',
    chucVuRequired: 'Chọn chức vụ',
    ngayThamGiaRequired: 'Chọn ngày tham gia tổ chức',
    trinhDoRequired: 'Chọn trình độ',
    lyLuanRequired: 'Chọn lý luận chính trị',
    trangThaiRequired: 'Chọn trạng thái',
    ngayNhapTrangThaiRequired: 'Chọn ngày nhập trạng thái',
  },
  emptyTitle: 'Chưa có cán bộ',
  emptyHint: 'Thêm hồ sơ mới hoặc điều chỉnh bộ lọc.',
  noViewPermission: 'Bạn không có quyền xem module Danh sách cán bộ.',
  /** Nút đầu dropdown chọn cán bộ ở module khác (khen thưởng, tập huấn, …). */
  comboboxAddNew: 'Thêm cán bộ mới',
  searchPlaceholder: 'Tìm theo họ tên, tổ chức, chức vụ, trạng thái…',
  noEmployeeBanner:
    'Tài khoản chưa gắn hồ sơ nhân viên: không thể tạo mới cán bộ cho đến khi được gán nhân viên. Liên hệ quản trị.',
  import: {
    templateFileName: 'Import_Can_Bo_MTTQ',
    sheetHuongDan: 'Huong_dan',
    sheetToChuc: 'To_chuc',
    sheetDanToc: 'Dan_toc',
    sheetTrinhDo: 'Trinh_do',
    sheetLyLuan: 'Ly_luan_CT',
    sheetTrangThai: 'Trang_thai',
    sheetPhongBan: 'Phong_ban',
    sheetChucVu: 'Chuc_vu',
    sheetXaPhuong: 'Xa_phuong',
    huongDanColKey: 'Mục',
    huongDanColVal: 'Hướng dẫn',
    huongR1k: 'Sheet dữ liệu',
    huongR1v: 'Chỉ điền các dòng trên sheet « Template » (sheet đầu tiên). Khi tải lên, file phải giữ sheet Template ở vị trí đầu.',
    huongR2k: 'Khóa ngoại (UUID)',
    huongR2v:
      'Cột có ghi (UUID) nên điền đúng id trong các sheet tham chiếu. Có thể điền theo tên hiển thị nếu trùng khớp duy nhất.',
    huongR3k: 'Đơn vị (xã/phường)',
    huongR3v: 'Bắt buộc khi chức vụ có cấp quản lý « Xã phường »; các trường hợp khác để trống.',
    huongR4k: 'Ngày tháng',
    huongR4v: 'Định dạng yyyy-mm-dd, dd/mm/yyyy, hoặc ô ngày Excel (serial).',
    huongR5k: 'Đảng viên',
    huongR5v: 'Có / Không, true/false, 1/0.',
    refColId: 'id',
    refColTen: 'ten',
    refColCapQuanLy: 'cap_quan_ly',
    refColPhongBanId: 'phong_ban_id',
    refColTenPhongBan: 'ten_phong_ban',
    refColChaId: 'cha_id',
    refColTenPhongCha: 'ten_phong_cha',
    refColTrangThai: 'trang_thai',
    refColIdTinh: 'id_tinh_thanh',
    refColTenTinh: 'ten_tinh',
    colPhongBan: 'id_phong_ban (UUID — sheet Phong_ban)',
    colToChuc: 'to_chuc_id (UUID — sheet To_chuc)',
    colHoTen: 'ho_ten',
    colNgaySinh: 'ngay_sinh',
    colGioiTinh: 'gioi_tinh',
    colDanToc: 'dan_toc_id (UUID — sheet Dan_toc)',
    colTonGiao: 'ton_giao',
    colDiaChi: 'dia_chi',
    colDangVien: 'dang_vien',
    colTrinhDo: 'trinh_do_id (UUID — sheet Trinh_do)',
    colLyLuan: 'ly_luan_chinh_tri_id (UUID — sheet Ly_luan_CT)',
    colDienThoai: 'dien_thoai',
    colChucVu: 'chuc_vu_id (UUID — sheet Chuc_vu)',
    colDonVi: 'don_vi_id (UUID — sheet Xa_phuong)',
    colNgayThamGia: 'ngay_tham_gia_to_chuc',
    colTrangThai: 'trang_thai_id (UUID — sheet Trang_thai)',
    colNgayNhapTT: 'ngay_nhap_trang_thai',
    colVanHoa: 'van_hoa',
    colNgayVaoDang: 'ngay_vao_dang',
    colQueQuan: 'que_quan',
    colNoiOHienNay: 'noi_o_hien_nay',
    rowPrefix: 'Dòng {{row}}: ',
    toastSuccess: 'Đã import {{count}} hồ sơ cán bộ.',
    errorThietLapEmpty: 'Thiếu hoặc không khớp mã thiết lập (id/tên).',
    errorThietLapResolve: 'Không tìm thấy bản ghi thiết lập theo id hoặc tên.',
    errorPhongBanEmpty: 'Thiếu phòng ban (id_phong_ban).',
    errorPhongBanResolve: 'Không tìm thấy phòng ban theo id hoặc tên.',
    errorChucVuEmpty: 'Thiếu chức vụ (chuc_vu_id).',
    errorChucVuResolve: 'Không tìm thấy chức vụ theo id hoặc tên.',
    errorHoTenEmpty: 'Thiếu họ tên.',
    errorNgaySinh: 'Ngày sinh không hợp lệ hoặc trống.',
    errorNgayThamGia: 'Ngày tham gia tổ chức không hợp lệ hoặc trống.',
    errorNgayNhapTT: 'Ngày nhập trạng thái không hợp lệ hoặc trống.',
    errorCreate: 'Lỗi khi tạo bản ghi.',
  },
} as const;
