/** Chuỗi module Danh sách bài viết — flatten vào STRINGS với prefix `articleList` */
export const articleList = {
  tabAll: 'Tất cả',
  tabMine: 'Của tôi',
  store: {
    nameCol: 'Tên bài',
    theLoaiCol: 'Thể loại',
    donGiaCol: 'Đơn giá',
    ngayDangCol: 'Ngày đăng',
    nguonDangCol: 'Nguồn đăng',
    trangDangCol: 'Trang đăng',
    linkCol: 'Liên kết',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    tenBai: 'Tên bài',
    theLoai: 'Thể loại',
    donGia: 'Đơn giá (VNĐ)',
    donGiaLockedHint:
      'Đơn giá lấy theo thể loại. Chỉ cấp lãnh đạo (cấp bậc 1) hoặc quản trị module mới chỉnh tay được.',
    ngayDang: 'Ngày đăng',
    nguonDang: 'Nguồn đăng',
    trangDang: 'Trang đăng',
    link: 'Liên kết bài viết',
    createSubtitle: 'Thêm bài viết mới',
    editSubtitle: 'Cập nhật bài viết',
  },
  detail: {
    title: 'Chi tiết bài viết',
    subtitle: 'Bài viết đã đăng',
    sectionInfo: 'Thông tin bài viết',
    openLink: 'Mở liên kết',
  },
  deleteTitle: 'Xóa bài viết',
  deleteMessage: 'Bạn có chắc muốn xóa bài viết này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều bài viết',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} bài viết đã chọn? Hành động không hoàn tác.',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'Danh_Sach_Bai_Viet',
  toast: {
    create: 'Đã thêm bài viết',
    update: 'Đã cập nhật bài viết',
    delete: 'Đã xóa {{count}} bài viết',
  },
  service: {
    notFound: 'Không tìm thấy bài viết',
    noEmployeeProfile: 'Tài khoản chưa gắn hồ sơ nhân viên. Liên hệ quản trị để được gán trước khi thêm bài.',
  },
  validation: {
    tenBaiRequired: 'Nhập tên bài',
    tenBaiDuplicate: 'Tên bài này đã tồn tại, đặt tên khác',
    theLoaiRequired: 'Chọn thể loại',
    donGiaMin: 'Đơn giá không âm',
    donGiaKhongDoc: 'Đơn giá chưa đọc được. Chỉ nhập số, ví dụ 500.000',
    ngayDangRequired: 'Chọn ngày đăng',
    nguonDangRequired: 'Chọn nguồn đăng',
    trangDangRequired: 'Chọn trang đăng',
    linkRequired: 'Nhập liên kết',
    linkUrl: 'Liên kết phải là URL hợp lệ (https://...)',
    linkDuplicate: 'Liên kết này đã được dùng cho bài viết khác',
  },
  import: {
    rowPrefix: 'Dòng {{row}}: ',
    errTooManyRows: 'File có {{count}} dòng, vượt mức tối đa {{max}} dòng mỗi lần nhập. Hãy chia nhỏ file.',
    errTenBaiTrong: 'thiếu tên bài.',
    errTheLoai: 'không tìm thấy thể loại “{{gia_tri}}”. Xem sheet Thể loại trong file mẫu.',
    errNguonDang: 'không tìm thấy nguồn đăng “{{gia_tri}}”. Xem sheet Nguồn đăng trong file mẫu.',
    errTrangDang: 'không tìm thấy trang đăng “{{gia_tri}}”. Xem sheet Trang đăng trong file mẫu.',
    errNgayDang: 'ngày đăng “{{gia_tri}}” không đọc được. Dùng dạng 31/12/2026 hoặc 2026-12-31.',
    errDonGia: 'đơn giá “{{gia_tri}}” không đọc được. Chỉ nhập số, ví dụ 500.000',
    errNguoiTao: 'không tìm thấy nhân viên “{{gia_tri}}”. Nhập tên tài khoản hoặc họ tên đúng như trong hệ thống.',
    errKhongCoNguoiTao: 'tài khoản đang dùng chưa gắn hồ sơ nhân viên nên không xác định được người tạo.',
    errTrungLinkTrongFile: 'trùng liên kết với dòng {{row}} trong chính file này.',
    errTrungTenTrongFile: 'trùng tên bài với dòng {{row}} trong chính file này.',
    errTrungBanGhiDich: 'cùng trỏ tới một bài đã có với dòng {{row}}. Mỗi bài chỉ được một dòng ghi đè.',
    errTrungKhoaKhac: 'đụng một bài đã có ở cột không được chọn làm tham chiếu. Tick thêm cột tham chiếu rồi nhập lại.',
    skipDaTonTai: 'bài này đã có trong hệ thống nên được bỏ qua.',
    skipChuaTonTai: 'chưa có bài nào khớp nên không cập nhật được.',
    errSummary: 'Có tất cả {{count}} dòng lỗi, dưới đây là 10 dòng đầu.',
    noteBoQuaCotNguoiTao: 'Cột “Người tạo” trong file bị bỏ qua: bạn không có quyền gán bài cho người khác. Mọi bài sẽ ghi tên bạn.',
    noteBoQuaCotDonGia: 'Cột “Đơn giá” trong file bị bỏ qua: bạn không có quyền sửa đơn giá. Hệ thống lấy đơn giá mặc định của thể loại.',
    noteBoQuaGhiDe: 'Bạn không có quyền sửa bài viết nên chỉ nhập được bài mới.',
    colTenBai: 'Tên bài',
    colTheLoai: 'Thể loại',
    colNgayDang: 'Ngày đăng',
    colDonGia: 'Đơn giá',
    colNguonDang: 'Nguồn đăng',
    colTrangDang: 'Trang đăng',
    colLink: 'Liên kết',
    colNguoiTao: 'Người tạo',
    templateFileName: 'mau-nhap-bai-viet',
    sheetHuongDan: 'Huong dan',
    sheetTheLoai: 'The loai',
    sheetNguonDang: 'Nguon dang',
    sheetTrangDang: 'Trang dang',
    sheetNhanVien: 'Nhan vien',
    sheetColId: 'Mã',
    sheetColTen: 'Tên',
    sheetColDonGia: 'Đơn giá mặc định',
    sheetColTaiKhoan: 'Tên tài khoản',
    sheetHuongDanCot: 'Nội dung',
    huongDan1: 'Mỗi dòng ở sheet Template là một bài viết. Chỉ sheet ĐẦU TIÊN được đọc.',
    huongDan2: 'Thể loại / Nguồn đăng / Trang đăng: điền TÊN hoặc MÃ lấy từ các sheet tra cứu kèm theo. Tên không cần đúng dấu.',
    huongDan3: 'Ngày đăng: 31/12/2026 hoặc 2026-12-31, hoặc để Excel định dạng ngày.',
    huongDan4: 'Liên kết bắt buộc và phải là URL đầy đủ (https://...). Đây cũng là cột tham chiếu mặc định khi ghi đè.',
    huongDan5: 'Người tạo: bỏ trống thì bài ghi tên bạn. Chỉ quản trị mới nhập được người khác.',
    huongDan6: 'Tối đa {{max}} dòng mỗi lần nhập.',
    toastDone: 'Đã nhập {{created}} bài mới, ghi đè {{updated}} bài.',
  },
  emptyTitle: 'Chưa có bài viết',
  emptyHint: 'Thêm bài viết mới hoặc điều chỉnh bộ lọc.',
  noViewPermission: 'Bạn không có quyền xem module Danh sách bài viết.',
  noViewRowPermission: 'Bạn không có quyền xem bài viết này.',
} as const;
