/** Chuỗi module Danh sách bài viết — flatten vào STRINGS với prefix `articleList` */
export const articleList = {
  tabAll: 'Tất cả',
  tabMine: 'Của tôi',
  store: {
    nameCol: 'Tên bài',
    theLoaiCol: 'Thể loại',
    donGiaCol: 'Đơn giá',
    ngayDangCol: 'Ngày đăng',
    nguonDangCol: 'Nguồn đăng',
    trangDangCol: 'Trang đăng',
    linkCol: 'Liên kết',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    tenBai: 'Tên bài',
    theLoai: 'Thể loại',
    donGia: 'Đơn giá (VNĐ)',
    donGiaLockedHint:
      'Đơn giá lấy theo thể loại. Chỉ cấp lãnh đạo (cấp bậc 1) hoặc quản trị module mới chỉnh tay được.',
    ngayDang: 'Ngày đăng',
    nguonDang: 'Nguồn đăng',
    trangDang: 'Trang đăng',
    link: 'Liên kết bài viết',
    createSubtitle: 'Thêm bài viết mới',
    editSubtitle: 'Cập nhật bài viết',
  },
  detail: {
    title: 'Chi tiết bài viết',
    subtitle: 'Bài viết đã đăng',
    sectionInfo: 'Thông tin bài viết',
    openLink: 'Mở liên kết',
  },
  deleteTitle: 'Xóa bài viết',
  deleteMessage: 'Bạn có chắc muốn xóa bài viết này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều bài viết',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} bài viết đã chọn? Hành động không hoàn tác.',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'Danh_Sach_Bai_Viet',
  toast: {
    create: 'Đã thêm bài viết',
    update: 'Đã cập nhật bài viết',
    delete: 'Đã xóa {{count}} bài viết',
  },
  service: {
    notFound: 'Không tìm thấy bài viết',
    noEmployeeProfile: 'Tài khoản chưa gắn hồ sơ nhân viên. Liên hệ quản trị để được gán trước khi thêm bài.',
  },
  validation: {
    tenBaiRequired: 'Nhập tên bài',
    theLoaiRequired: 'Chọn thể loại',
    donGiaMin: 'Đơn giá không âm',
    ngayDangRequired: 'Chọn ngày đăng',
    nguonDangRequired: 'Chọn nguồn đăng',
    trangDangRequired: 'Chọn trang đăng',
    linkRequired: 'Nhập liên kết',
    linkUrl: 'Liên kết phải là URL hợp lệ (https://...)',
  },
  emptyTitle: 'Chưa có bài viết',
  emptyHint: 'Thêm bài viết mới hoặc điều chỉnh bộ lọc.',
  noViewPermission: 'Bạn không có quyền xem module Danh sách bài viết.',
} as const;
