/** Thống kê kiểm tra, GS và PBXH */
export const pbxhThongKe = {
  title: 'Thống kê kiểm tra, GS và PBXH',
  noViewPermission: 'Bạn không có quyền xem Thống kê kiểm tra, GS và PBXH.',
  noDetailPermission: 'Bạn không có quyền xem chi tiết hoạt động phản biện xã hội.',
  loading: 'Đang tải thống kê…',
  noData: 'Không có dữ liệu trong khoảng và bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng thời gian hoặc bỏ bớt bộ lọc.',
  noExportData: 'Không có dữ liệu để xuất',
  dateRangeLabel: 'Khoảng thời gian',
  exportFileName: 'Bao_Cao_Phan_Bien_Xa_Hoi',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  stats: {
    exportReport: 'Xuất báo cáo',
    exportData: 'Export dữ liệu',
    exportSuccess: 'Xuất báo cáo Excel thành công',
    exportSuccessDesc: 'Báo cáo đã được tải về.',
    exportError: 'Xuất báo cáo thất bại',
    clearFilters: 'Xóa bộ lọc',
    filterCapThucHien: 'Cấp thực hiện',
    filterLoaiHinh: 'Loại hình',
    filterTinhTrang: 'Tình trạng',
    filterDonViChuTri: 'Đơn vị chủ trì',
    filterTienDo: 'Tiến độ',
    filterTienDoQuaHan: 'Quá hạn',
    filterTienDoSapDenHan: 'Sắp đến hạn',
    filterTienDoConHan: 'Còn hạn',
    filterTienDoKhongCoHan: 'Không có hạn',
    donViChuaGan: 'Chưa gán',
    kpiTotal: 'Tổng hoạt động',
    kpiDangThucHien: 'Đang thực hiện',
    kpiHoanThanh: 'Đã hoàn thành',
    kpiKeHoachDuKien: 'Đã lập KH / Dự kiến',
    kpiQuaHan: 'Quá hạn',
    kpiAvgPhanTram: 'TB % hoàn thành',
    chartTinhTrang: 'Theo tình trạng',
    chartLoaiHinh: 'Theo loại hình',
    chartCapThucHien: 'Theo cấp thực hiện',
    chartTopDonViChuTri: 'Top đơn vị chủ trì',
    chartTrend: 'Xu hướng theo thời gian',
    tableDonViChuTri: 'Thống kê theo đơn vị chủ trì',
    tableMatrix: 'Loại hình × tình trạng',
    tableLookupTitle: 'Tra cứu',
    tableColNoiDung: 'Nội dung',
    tableColLoaiHinh: 'Loại hình',
    tableColTinhTrang: 'Tình trạng',
    tableColDonViChuTri: 'Đơn vị chủ trì',
    tableColTienDo: 'Tiến độ',
    tableColPhanTram: '% HT',
    tableColNgayKetThuc: 'Kết thúc',
    tableColDonVi: 'Đơn vị chủ trì',
    tableColTotal: 'Tổng',
    tableColDangTh: 'Đang TH',
    tableColHoanThanh: 'Hoàn thành',
    tableColAvgPhanTram: 'TB % HT',
    tableTwoColLabel: 'Nhóm',
    tableTwoColValue: 'Số lượng',
    tableMatrixCol: 'Phân loại',
    preset: {
      thisWeek: 'Tuần này',
      thisMonth: 'Tháng này',
      thisQuarter: 'Quý này',
      thisYear: 'Năm nay',
      custom: 'Tùy chọn',
    },
  },
  report: {
    title: 'Báo cáo thống kê kiểm tra, GS và PBXH',
    period: 'Khoảng thời gian',
    exportDate: 'Ngày xuất',
    indicator: 'Chỉ số',
    value: 'Giá trị',
    overviewSheet: 'Tổng quan',
    byDonViChuTriSheet: 'Theo đơn vị chủ trì',
    byLoaiHinhSheet: 'Theo loại hình',
    detailSheet: 'Chi tiết',
    pdfTitle: 'BÁO CÁO THỐNG KÊ KIỂM TRA, GS VÀ PBXH',
    pdfPeriod: 'Khoảng thời gian:',
    pdfExportDate: 'Xuất ngày:',
  },
} as const;
