export const matTranUyVienUyBan = {
  noViewPermission: 'Bạn không có quyền xem danh sách ủy viên ủy ban.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo bản ghi.',
  tinhCap: 'MTTQ tỉnh',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy bản ghi ủy viên.',
  },
  deleteTitle: 'Xóa ủy viên?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều ủy viên?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-uy-vien-uy-ban',
  toast: {
    create: 'Đã thêm ủy viên.',
    update: 'Đã cập nhật ủy viên.',
    delete: 'Đã xóa {{count}} bản ghi.',
    importSuccess: 'Đã nhập {{count}} ủy viên.',
  },
  import: {
    rowError: 'Dòng {{row}}: {{message}}',
    templateName: 'mau-nhap-uy-vien-uy-ban',
    badNhiemKy: 'Không tìm thấy nhiệm kỳ (ten_nhiem_ky / nhiem_ky_id).',
  },
  validation: {
    nhiemKyRequired: 'Chọn nhiệm kỳ.',
    hoVaTenRequired: 'Nhập họ và tên.',
  },
  store: {
    hoVaTenCol: 'Họ và tên',
    maUvCol: 'Mã UV',
    tenNhiemKyCol: 'Nhiệm kỳ',
    donViCol: 'Đơn vị',
    chucVuDonViCol: 'Chức vụ đơn vị',
    trangThamGiaCol: 'Trạng thái tham gia',
    soKyHopCol: 'Số kỳ họp',
    diemDanhCoMatCol: 'Có mặt',
    diemDanhVangMatCol: 'Vắng mặt',
    diemDanhChuaCol: 'Chưa điểm danh',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Ủy viên ủy ban',
  },
  searchPlaceholder: 'Tìm theo tên, mã UV, nhiệm kỳ, đơn vị, chức vụ…',
  emptyTitle: 'Chưa có ủy viên',
  emptyHint: 'Thêm ủy viên mới để bắt đầu.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionMain: 'Thông tin chính',
    sectionCaNhan: 'Nhân thân & tham gia',
    sectionHocVan: 'Trình độ & dân tộc - tôn giáo',
    sectionDang: 'Đảng viên',
    sectionLienHe: 'Liên hệ & địa chỉ',
    sectionGhiChu: 'Ghi chú',
    maUv: 'Mã UV',
    nhiemKy: 'Nhiệm kỳ',
    donVi: 'Đơn vị (xã/phường)',
    donViPlaceholder: 'Để trống = MTTQ tỉnh',
    hoVaTen: 'Họ và tên',
    chucVuDonVi: 'Chức vụ đơn vị',
    ngaySinh: 'Ngày sinh',
    gioiTinh: 'Giới tính',
    trangThamGia: 'Trạng thái tham gia',
    ngayNhapTrangThai: 'Ngày nhập trạng thái',
    vanHoa: 'Văn hóa',
    trinhDoCm: 'Trình độ CM',
    trinhDoLlct: 'Trình độ LLCT',
    danToc: 'Dân tộc',
    tonGiao: 'Tôn giáo',
    dangVien: 'Đảng viên',
    ngayVaoDang: 'Ngày vào Đảng',
    queQuan: 'Quê quán',
    noiOHienNay: 'Nơi ở hiện nay',
    soDienThoai: 'Số điện thoại',
    ghiChu: 'Ghi chú',
    createSubtitle: 'Thêm ủy viên mới',
    editSubtitle: 'Sửa ủy viên',
  },
  detail: {
    title: 'Chi tiết ủy viên ủy ban',
    tabInfo: 'Thông tin',
    tabDiemDanh: 'Điểm danh',
    diemDanhSectionTitle: 'Điểm danh theo kỳ họp',
    diemDanhEmptyKyHop: 'Chưa có kỳ họp trong nhiệm kỳ này.',
    sectionMain: 'Thông tin chính',
    sectionCaNhan: 'Nhân thân & tham gia',
    sectionHocVan: 'Trình độ & dân tộc - tôn giáo',
    sectionDang: 'Đảng viên',
    sectionLienHe: 'Liên hệ & địa chỉ',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
} as const;
