/** Chuỗi module Nhuận bút — prefix `articleCommission` trong STRINGS */
export const articleCommission = {
  tabMine: 'Của tôi',
  tabAll: 'Tất cả',
  filterTheLoai: 'Thể loại',
  filterAuthor: 'Người viết',
  filterDonVi: 'Đơn vị',
  donViChuaGan: 'Chưa gán đơn vị',
  /** Khoảng thời gian không giới hạn (bổ sung trên DateRangePicker chung với BC thống kê). */
  presetAll: 'Toàn bộ',
  kpiTotal: 'Tổng nhuận bút',
  kpiArticles: 'Số bài',
  kpiAvg: 'Trung bình / bài',
  kpiTopAuthor: 'Tác giả dẫn đầu',
  kpiTopAuthorEmpty: '—',
  chartTrend: 'Nhuận bút theo tháng',
  chartByTheLoai: 'Theo thể loại',
  chartByAuthor: 'Theo người viết',
  chartOtherSlice: 'Khác',
  tableByAuthor: 'Chi tiết theo người viết',
  tableByTheLoai: 'Chi tiết theo thể loại',
  tableColLabel: 'Đối tượng',
  tableColValue: 'Nhuận bút (lượt)',
  noData: 'Không có dữ liệu',
  noDataHint: 'Thử đổi bộ lọc hoặc khoảng thời gian.',
  loading: 'Đang tải…',
  allTabNoPermission: 'Bạn không có quyền xem thống kê toàn bộ.',
  axisAmount: 'Số tiền (VNĐ)',
  axisCount: 'Số bài',
  goToArticles: 'Mở danh sách bài viết',
  /** Placeholder DateRangePicker (theo ngày đăng bài, khác BC thống kê). */
  dateRangePlaceholder: 'Khoảng thời gian',
  noViewPermission: 'Bạn không có quyền xem module Nhuận bút.',
  exportFileName: 'Nhuan_But_Viet_Bai',
  noExportData: 'Không có dữ liệu để xuất',
  exportFailed: 'Không xuất được file. Vui lòng thử lại.',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  exportRangeAll: 'Toàn bộ thời gian',
  exportPhamVi: 'Phạm vi xem',
  exportRowTongCong: 'Tổng cộng',
  exportColChiTieu: 'Chỉ tiêu',
  exportColGiaTri: 'Giá trị',
  exportColKy: 'Kỳ',
  exportColSoBai: 'Số bài',
  exportColSoTien: 'Số tiền',
  exportColStt: 'STT',
  exportColTenBai: 'Tên bài',
  exportColTheLoai: 'Thể loại',
  exportColNgayDang: 'Ngày đăng',
  exportColNguon: 'Nguồn đăng',
  exportColTrang: 'Trang đăng',
  exportColNguoi: 'Người viết',
  exportColDonVi: 'Đơn vị',
  exportColLink: 'Liên kết',
  /* Tên sheet không dấu: tránh mọi rủi ro với phần mềm bảng tính cũ. */
  exportSheetTongHop: 'Tong hop',
  exportSheetTheoDonVi: 'Theo don vi',
  exportSheetTheoTheLoai: 'Theo the loai',
  exportSheetTheoNguon: 'Theo nguon dang',
  exportSheetTheoTrang: 'Theo trang dang',
  exportSheetTheoNguoiViet: 'Theo nguoi viet',
  exportSheetTheoThoiGian: 'Theo thoi gian',
  exportSheetChiTiet: 'Chi tiet',
} as const;
