import type { ThamHoiCaNhan } from './core/types';

export const DTTG_THAM_HOI_CA_NHAN_MOCK: ThamHoiCaNhan[] = [
  {
    id: '1',
    ca_nhan_id: '1',
    ho_va_ten: 'Hòa thượng Thích Thọ Lạc',
    doi_tuong: 'Chức sắc',
    chuc_vu_vi_tri: 'Trụ trì Chùa Cần Linh',
    phong_ban_tham_muu_id: '1',
    ten_phong_ban: 'Ban Dân tộc, Tôn giáo và Hội quần chúng',
    dip_tham_hoi: 'Đại lễ Phật đản',
    thoi_gian_du_kien: '2026-05-01',
    don_vi_tham_hoi_id: '101',
    ten_don_vi_tham_hoi: 'Phường Thành Vinh',
    qua_tang: 'Quà & Lẵng hoa',
    xa_phuong_id: '101',
    ten_xa_phuong: 'Phường Thành Vinh',
    trang_thai: 'Chưa thực hiện',
    ket_qua_ghi_chu: 'Lãnh đạo tôn giáo tiêu biểu',
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '2',
    ca_nhan_id: '4',
    ho_va_ten: 'Vừ Chông Pao',
    doi_tuong: 'Người uy tín',
    chuc_vu_vi_tri: 'Già làng',
    phong_ban_tham_muu_id: '1',
    ten_phong_ban: 'Ban Dân tộc, Tôn giáo và Hội quần chúng',
    dip_tham_hoi: 'Tết Nguyên Đán',
    thoi_gian_du_kien: '2026-01-01',
    don_vi_tham_hoi_id: null,
    ten_don_vi_tham_hoi: null,
    qua_tang: 'Quà Tết',
    xa_phuong_id: '202',
    ten_xa_phuong: 'Xã Huồi Tụ',
    trang_thai: 'Đã hoàn thành',
    ket_qua_ghi_chu: 'Vận động đồng bào định canh',
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-02T00:00:00.000Z',
    tg_cap_nhat: '2026-02-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '3',
    ca_nhan_id: '6',
    ho_va_ten: 'Nguyễn Văn Hùng',
    doi_tuong: 'Người có công',
    chuc_vu_vi_tri: 'Thương binh 1/4',
    phong_ban_tham_muu_id: '2',
    ten_phong_ban: 'Ban Tuyên giáo, Công tác xã hội',
    dip_tham_hoi: 'Ngày Thương binh Liệt sĩ',
    thoi_gian_du_kien: '2026-07-01',
    don_vi_tham_hoi_id: '303',
    ten_don_vi_tham_hoi: 'Xã Đại Huệ',
    qua_tang: 'Quà tặng',
    xa_phuong_id: '303',
    ten_xa_phuong: 'Xã Đại Huệ',
    trang_thai: 'Chưa thực hiện',
    ket_qua_ghi_chu: 'Thương binh vượt khó tiêu biểu',
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-03T00:00:00.000Z',
    tg_cap_nhat: '2026-01-03T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
];
