export const danTocThamHoiCaNhan = {
  noViewPermission: 'Bạn không có quyền xem thăm hỏi cá nhân.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  searchPlaceholder: 'Tìm theo họ tên, dịp thăm hỏi, đơn vị, phòng ban tham mưu…',
  emptyTitle: 'Chưa có lượt thăm hỏi cá nhân',
  emptyHint: 'Thêm kế hoạch hoặc ghi nhận lượt thăm hỏi cá nhân tiêu biểu.',
  emptyFilteredHint: 'Không có bản ghi phù hợp bộ lọc. Thử điều chỉnh tìm kiếm hoặc chip lọc.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'tham-hoi-ca-nhan',
  deleteTitle: 'Xóa lượt thăm hỏi',
  deleteMessage: 'Bạn có chắc muốn xóa lượt thăm hỏi này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều lượt thăm hỏi',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} lượt thăm hỏi đã chọn? Hành động không hoàn tác.',
  service: {
    notFound: 'Không tìm thấy lượt thăm hỏi',
    noEmployeeProfile: 'Không xác định được hồ sơ nhân viên. Vui lòng đăng nhập lại.',
  },
  toast: {
    create: 'Đã thêm lượt thăm hỏi cá nhân',
    update: 'Đã cập nhật lượt thăm hỏi',
    delete: 'Đã xóa {{count}} lượt thăm hỏi',
    importSuccess: 'Đã nhập {{count}} lượt thăm hỏi',
  },
  import: {
    templateName: 'tham-hoi-ca-nhan',
    rowError: 'Dòng {{row}}: {{message}}',
  },
  validation: {
    caNhanRequired: 'Vui lòng chọn cá nhân tiêu biểu',
    caNhanInvalid: 'Họ và tên cá nhân không hợp lệ',
    phongBanInvalid: 'Phòng ban tham mưu không hợp lệ',
    dipThamHoiRequired: 'Vui lòng nhập dịp thăm hỏi',
    trangThaiInvalid: 'Trạng thái không hợp lệ',
    linkUrl: 'Link kết quả phải là URL hợp lệ',
    donViThamHoiInvalid: 'Đơn vị thăm hỏi không hợp lệ',
    xaPhuongInvalid: 'Xã, Phường không hợp lệ',
    thoiGianDuKienInvalid: 'Thời gian dự kiến phải đúng định dạng tháng/năm',
    quaTangMaxLength: 'Quà tặng tối đa 200 ký tự',
  },
  store: {
    hoVaTenCol: 'Họ và tên',
    doiTuongCol: 'Đối tượng',
    chucVuViTriCol: 'Chức vụ / Vị trí',
    dipThamHoiCol: 'Dịp thăm hỏi',
    thoiGianDuKienCol: 'Thời gian dự kiến',
    donViThamHoiCol: 'Đơn vị thăm hỏi',
    phongBanThamMuuCol: 'Phòng ban tham mưu',
    quaTangCol: 'Quà tặng',
    donViXaPhuongCol: 'Xã, Phường',
    trangThaiCol: 'Trạng thái',
    ketQuaCol: 'Kết quả / Ghi chú',
    linkKetQuaCol: 'Link kết quả',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm lượt thăm hỏi cá nhân',
    editSubtitle: 'Cập nhật lượt thăm hỏi',
    sectionMain: 'Thông tin chính',
    sectionResult: 'Kết quả thực hiện',
    caNhan: 'Cá nhân tiêu biểu',
    caNhanPlaceholder: 'Chọn cá nhân từ danh mục',
    phongBanThamMuu: 'Phòng ban tham mưu',
    phongBanPlaceholder: 'Chọn phòng ban',
    dipThamHoi: 'Dịp thăm hỏi',
    thoiGianDuKien: 'Thời gian dự kiến',
    thoiGianDuKienHint: 'Chọn tháng/năm (MM/YYYY)',
    donViThamHoi: 'Đơn vị thăm hỏi',
    donViThamHoiPlaceholder: 'CQMTTQ Tỉnh hoặc chọn xã/phường',
    quaTangCreatableAction: 'Thêm « {{gift}} »',
    quaTangSearchPlaceholder: 'Tìm hoặc thêm quà tặng…',
    quaTang: 'Quà tặng',
    donViXaPhuong: 'Xã, Phường',
    trangThai: 'Trạng thái',
    ketQuaGhiChu: 'Kết quả / Ghi chú',
    linkKetQua: 'Link kết quả',
  },
  detail: {
    title: 'Chi tiết lượt thăm hỏi cá nhân',
    sectionMain: 'Thông tin chính',
    sectionResult: 'Kết quả thực hiện',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    nguoiTao: 'Người tạo',
    openLink: 'Mở link kết quả',
  },
} as const;
