export const hoNgheo = {
  tabs: {
    danhSach: 'Danh sách',
    thongKe: 'Thống kê',
    nhanHoTro: 'Thống kê nhận hỗ trợ',
  },
  noViewPermission: 'Bạn không có quyền xem module Thông tin đối tượng hỗ trợ.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập hộ thuộc xã/phường của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có hồ sơ hộ nghèo',
  emptyFiltered: 'Không có hộ nào khớp bộ lọc đang chọn',
  exportFileName: 'Thong_Tin_Doi_Tuong_Ho_Tro',
  deleteTitle: 'Xóa hồ sơ hộ',
  deleteMessage:
    'Bạn có chắc muốn xóa hộ này? Các khoản hỗ trợ của hộ vẫn được giữ ở Chương trình hỗ trợ, chỉ gỡ liên kết. Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều hộ',
  bulkDeleteMessage:
    'Bạn có chắc muốn xóa {{count}} hộ đã chọn? Các khoản hỗ trợ của những hộ này vẫn được giữ, chỉ gỡ liên kết. Hành động không hoàn tác.',
  detailTitle: 'Chi tiết hộ nghèo',
  detail: {
    sectionHoDan: 'Thông tin hộ',
    sectionLienHe: 'Liên hệ & tài khoản',
    sectionNhanKhau: 'Nhân khẩu & đời sống',
    nhanKhauLoading: 'Đang tải…',
    sectionHoTro: 'Chương trình hỗ trợ',
    sectionNhaDaiDoanKet: 'Nhà đại đoàn kết',
    systemInfo: 'Thông tin hệ thống',
    ngayTrangThaiHint: 'Máy chủ tự ghi khi trạng thái thay đổi.',
    actionChangeStatus: 'Chuyển trạng thái',
    actionEdit: 'Sửa hồ sơ',
    actionDelete: 'Xóa hồ sơ',
    hoTroEmpty: 'Hộ này chưa ghi nhận khoản hỗ trợ nào',
    hoTroAdd: 'Thêm khoản hỗ trợ',
    hoTroRecordsSuffix: 'khoản',
    nhaEmpty: 'Hộ này chưa gắn hồ sơ nhà đại đoàn kết nào',
    nhaRecordsSuffix: 'căn',
    nhaOpenModule: 'Mở module Nhà đại đoàn kết',
    nhaReadOnlyHint: 'Dữ liệu của module Nhà đại đoàn kết — bấm một dòng để xem, sửa ở module gốc.',
    nhaAdd: 'Thêm nhà đại đoàn kết',
  },
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái hộ và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
  },
  store: {
    hoTenCol: 'Họ và tên đại diện hộ',
    soCccdCol: 'Số căn cước',
    xaPhuongCol: 'Xã phường',
    khoiXomCol: 'Khối xóm',
    doiTuongCol: 'Đối tượng',
    dienThoaiCol: 'Số điện thoại',
    danTocCol: 'Dân tộc',
    tonGiaoCol: 'Tôn giáo',
    soTaiKhoanCol: 'Tài khoản ngân hàng',
    nganHangCol: 'Ngân hàng',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Thời gian trạng thái',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
    gioiTinhCol: 'Giới tính',
    namSinhCol: 'Năm sinh',
    ngayCapCccdCol: 'Ngày cấp căn cước',
    noiCapCccdCol: 'Nơi cấp căn cước',
    hoTenVoChongCol: 'Họ tên vợ hoặc chồng',
    soNhanKhauCol: 'Số nhân khẩu',
    ngheNghiepCol: 'Nghề nghiệp',
    trinhDoHocVanCol: 'Trình độ học vấn',
    viecLamCol: 'Tình trạng việc làm',
    doiTuongUuTienCol: 'Đối tượng ưu tiên',
    tinhTrangDatCol: 'Tình trạng đất ở',
  },
  hoTroStore: {
    linhVucCol: 'Lĩnh vực hỗ trợ',
    noiDungCol: 'Nội dung hỗ trợ',
    namCol: 'Năm',
    soTienCol: 'Số tiền',
    trangThaiCol: 'Trạng thái',
  },
  nhaStore: {
    noiDungCol: 'Nội dung hỗ trợ',
    namCol: 'Năm',
    loaiHinhCol: 'Loại hình hỗ trợ',
    soTienCol: 'Số tiền',
    trangThaiCol: 'Trạng thái',
  },
  form: {
    ngayTrangThaiLabel: 'Ngày trạng thái',
    ngayTrangThaiTuGhi: 'Tự ghi khi lưu',
    ngayTrangThaiSeCapNhat: 'Trạng thái vừa đổi — ngày sẽ cập nhật khi lưu.',
    createSubtitle: 'Thêm hồ sơ hộ nghèo',
    editSubtitle: 'Cập nhật hồ sơ hộ',
    sectionHoDan: 'Thông tin hộ',
    sectionLienHe: 'Liên hệ & tài khoản',
    sectionNhanKhau: 'Nhân khẩu & đời sống',
    sectionNhanKhauHint: 'Dùng để in phiếu khảo sát và biên bản bàn giao nhà đại đoàn kết. Để trống thì phiếu in dòng chấm để viết tay.',
    sectionTrangThai: 'Trạng thái',
    chonPlaceholder: 'Chọn',
    doiTuongUuTienPlaceholder: 'Người có công, dân tộc thiểu số…',
    soCccdPlaceholder: 'Nhập 12 chữ số CCCD hoặc 9 chữ số CMND',
    soCccdHint: 'CCCD 12 chữ số hoặc CMND cũ 9 chữ số, không trùng với hộ khác.',
    xaPhuongPlaceholder: 'Chọn xã/phường',
    danTocPlaceholder: 'Chọn dân tộc',
    doiTuongPlaceholder: 'Chọn đối tượng',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
  },
  toast: {
    create: 'Đã thêm hộ nghèo.',
    update: 'Đã cập nhật hồ sơ hộ.',
    delete: 'Đã xóa {{count}} hộ.',
    statusChange: 'Đã chuyển trạng thái hộ.',
  },
  service: {
    noEmployeeProfile: 'Tài khoản chưa gắn hồ sơ nhân viên nên chưa lưu được.',
  },
  validation: {
    hoTenRequired: 'Nhập họ và tên đại diện hộ.',
    soCccdKhongHopLe: 'Số căn cước phải gồm 12 chữ số (hoặc CMND cũ 9 chữ số).',
    soCccdRequired: 'Nhập số căn cước.',
    khoiXomRequired: 'Nhập khối xóm.',
    doiTuongRequired: 'Chọn đối tượng.',
    danTocRequired: 'Chọn dân tộc.',
    doiTuongInvalid: 'Đối tượng chưa hợp lệ.',
    tonGiaoInvalid: 'Tôn giáo chỉ nhận Có hoặc Không.',
    trangThaiInvalid: 'Trạng thái chưa hợp lệ.',
    gioiTinhInvalid: 'Giới tính chỉ nhận Nam hoặc Nữ.',
    namSinhInvalid: 'Năm sinh phải từ 1900 đến 2100.',
    soNhanKhauInvalid: 'Số nhân khẩu phải là số nguyên từ 0 đến 100.',
    viecLamInvalid: 'Tình trạng việc làm chưa hợp lệ.',
    tinhTrangDatInvalid: 'Tình trạng đất ở chưa hợp lệ.',
    ngayInvalid: 'Ngày chưa hợp lệ.',
  },
  noExportData: 'Không có dữ liệu để xuất.',
  import: {
    templateFileName: 'mau-nhap-ho-ngheo',
    toastDone: 'Đã nhập: {{created}} hộ mới, {{updated}} hộ được ghi đè.',
    keySoCccd: 'số căn cước',
    keyHoTenXa: 'họ tên + xã phường',
    matchHoTenXa: 'Họ tên đại diện + Xã phường',
    errXaPhuong: 'không tìm thấy xã phường “{{gia_tri}}”. Xem sheet Xa phuong trong file mẫu.',
    errXaTrungTen: 'có nhiều xã phường tên “{{gia_tri}}”. Nhập mã (id) xã phường trong sheet Xa phuong.',
    errDanToc: 'không tìm thấy dân tộc “{{gia_tri}}”. Xem sheet Dan toc trong file mẫu.',
    errDoiTuong: 'đối tượng “{{gia_tri}}” không hợp lệ. Xem sheet Gia tri hop le.',
    errTonGiao: 'tôn giáo “{{gia_tri}}” không hợp lệ — chỉ nhận Có hoặc Không.',
    errTrangThai: 'trạng thái “{{gia_tri}}” không hợp lệ. Xem sheet Gia tri hop le.',
    sheetHuongDan: 'Huong dan',
    sheetXaPhuong: 'Xa phuong',
    sheetDanToc: 'Dan toc',
    sheetGiaTri: 'Gia tri hop le',
    refColId: 'Mã (id)',
    refColTen: 'Tên',
    giaTriColCot: 'Cột',
    giaTriColGiaTri: 'Giá trị được nhận',
    huongDanColMuc: 'Mục',
    huongDanColNoiDung: 'Nội dung',
    huong1k: 'Cột bắt buộc',
    huong1v: 'Họ và tên đại diện hộ, Số căn cước, Khối xóm, Đối tượng, Dân tộc — dòng nào thiếu sẽ bị bỏ qua và báo lỗi. Số căn cước 12 chữ số (hoặc CMND 9 số); định dạng ô là Văn bản (Text) để không mất số 0 đầu.',
    huong2k: 'Xã phường, Dân tộc',
    huong2v: 'Nhập tên hoặc mã (id) đúng như các sheet tra cứu. Tên không phân biệt hoa thường và dấu.',
    huong3k: 'Tôn giáo, Trạng thái',
    huong3v: 'Để trống thì lấy mặc định: Tôn giáo “Không”, Trạng thái “Đang khó khăn”.',
    huong4k: 'Ghi đè',
    huong4v: 'Chọn chế độ “Thêm mới và ghi đè” hoặc “Chỉ cập nhật”, rồi chọn cột tham chiếu: Mã hệ thống (từ file xuất ra), Số căn cước, hoặc Họ tên + Xã phường.',
    huong5k: 'Cột không có trong file',
    huong5v: 'Khi ghi đè, cột nào không có trong file thì giữ nguyên giá trị cũ. Cột có trong file mà ô trống thì xoá giá trị cũ.',
    huong6k: 'Cán bộ cấp xã',
    huong6v: 'Chỉ nhập và ghi đè được hộ thuộc xã của mình; ô Xã phường để trống sẽ tự gán xã của mình.',
  },
};
