/** Tab "Thống kê nhận hỗ trợ" + dải tổng ở chi tiết hộ. */
export const hoNgheoNhanHoTro = {
  hint: 'Chỉ tính khoản đã trao: Chương trình hỗ trợ "Đã nhận", Nhà đại đoàn kết "Đã bàn giao", phiếu xuất kho gắn hộ.',
  listLoadErrorHint: 'Không tải được số liệu nhận hỗ trợ. Thử lại sau ít phút.',
  empty: 'Chưa có hộ nào nhận hỗ trợ trong bộ lọc này',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'thong-ke-nhan-ho-tro',
  filterNam: 'Năm',
  filterXaPhuong: 'Xã phường',
  filterDoiTuong: 'Đối tượng',
  chiHoDaNhan: 'Chỉ hộ đã nhận',
  tatCaHo: 'Tất cả hộ',
  kpi: {
    soHoDaNhan: 'Hộ đã nhận',
    vnn: 'Chương trình hỗ trợ',
    nddk: 'Nhà đại đoàn kết',
    kho: 'Hàng kho',
    tong: 'Tổng đã nhận',
  },
  col: {
    hoTen: 'Họ và tên đại diện hộ',
    soCccd: 'Số căn cước',
    xaPhuong: 'Xã phường',
    khoiXom: 'Khối xóm',
    doiTuong: 'Đối tượng',
    vnnTien: 'CT hỗ trợ — tiền',
    vnnHienVat: 'CT hỗ trợ — hiện vật',
    vnnSoKhoan: 'Số khoản',
    nddkTien: 'Nhà ĐĐK',
    nddkSoCan: 'Số căn',
    khoGiaTri: 'Hàng kho',
    khoSoPhieu: 'Số phiếu',
    tong: 'Tổng',
  },
  hoDetail: {
    title: 'Đã nhận hỗ trợ',
    tong: 'Tổng',
    vnn: 'CT hỗ trợ',
    nddk: 'Nhà ĐĐK',
    kho: 'Hàng kho',
    phieuKhoTitle: 'Phiếu xuất kho cho hộ',
    phieuKhoTrong: 'Chưa có phiếu xuất kho nào gắn hộ này.',
  },
};
