export const hoNgheo = {
  noViewPermission: 'Bạn không có quyền xem module Thông tin hộ nghèo.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập hộ thuộc xã/phường của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có hồ sơ hộ nghèo',
  emptyFiltered: 'Không có hộ nào khớp bộ lọc đang chọn',
  exportFileName: 'Thong_Tin_Ho_Ngheo',
  deleteTitle: 'Xóa hồ sơ hộ',
  deleteMessage:
    'Bạn có chắc muốn xóa hộ này? Các khoản hỗ trợ của hộ vẫn được giữ ở Chương trình vì người nghèo, chỉ gỡ liên kết. Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều hộ',
  bulkDeleteMessage:
    'Bạn có chắc muốn xóa {{count}} hộ đã chọn? Các khoản hỗ trợ của những hộ này vẫn được giữ, chỉ gỡ liên kết. Hành động không hoàn tác.',
  detailTitle: 'Chi tiết hộ nghèo',
  detail: {
    sectionHoDan: 'Thông tin hộ',
    sectionLienHe: 'Liên hệ & tài khoản',
    sectionHoTro: 'Chương trình vì người nghèo',
    sectionNhaDaiDoanKet: 'Nhà đại đoàn kết',
    systemInfo: 'Thông tin hệ thống',
    ngayTrangThaiHint: 'Máy chủ tự ghi khi trạng thái thay đổi.',
    actionChangeStatus: 'Chuyển trạng thái',
    actionEdit: 'Sửa hồ sơ',
    actionDelete: 'Xóa hồ sơ',
    hoTroEmpty: 'Hộ này chưa ghi nhận khoản hỗ trợ nào',
    hoTroAdd: 'Thêm khoản hỗ trợ',
    hoTroRecordsSuffix: 'khoản',
    nhaEmpty: 'Hộ này chưa gắn hồ sơ nhà đại đoàn kết nào',
    nhaRecordsSuffix: 'căn',
    nhaOpenModule: 'Mở module Nhà đại đoàn kết',
    nhaReadOnlyHint: 'Dữ liệu của module Nhà đại đoàn kết — sửa ở module gốc.',
  },
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái hộ và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
  },
  store: {
    hoTenCol: 'Họ và tên đại diện hộ',
    soCccdCol: 'Số căn cước',
    xaPhuongCol: 'Xã phường',
    khoiXomCol: 'Khối xóm',
    doiTuongCol: 'Đối tượng',
    dienThoaiCol: 'Số điện thoại',
    danTocCol: 'Dân tộc',
    tonGiaoCol: 'Tôn giáo',
    soTaiKhoanCol: 'Tài khoản ngân hàng',
    nganHangCol: 'Ngân hàng',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Thời gian trạng thái',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  hoTroStore: {
    linhVucCol: 'Lĩnh vực hỗ trợ',
    noiDungCol: 'Nội dung hỗ trợ',
    namCol: 'Năm',
    soTienCol: 'Số tiền',
    trangThaiCol: 'Trạng thái',
  },
  nhaStore: {
    noiDungCol: 'Nội dung hỗ trợ',
    namCol: 'Năm',
    loaiHinhCol: 'Loại hình hỗ trợ',
    soTienCol: 'Số tiền',
    trangThaiCol: 'Trạng thái',
  },
  form: {
    createSubtitle: 'Thêm hồ sơ hộ nghèo',
    editSubtitle: 'Cập nhật hồ sơ hộ',
    sectionHoDan: 'Thông tin hộ',
    sectionLienHe: 'Liên hệ & tài khoản',
    sectionTrangThai: 'Trạng thái',
    soCccdPlaceholder: 'Để trống nếu chưa có giấy tờ',
    soCccdHint: 'Đã nhập thì không được trùng với hộ khác.',
    xaPhuongPlaceholder: 'Chọn xã/phường',
    danTocPlaceholder: 'Chọn dân tộc',
    doiTuongPlaceholder: 'Chọn đối tượng',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
  },
  toast: {
    create: 'Đã thêm hộ nghèo.',
    update: 'Đã cập nhật hồ sơ hộ.',
    delete: 'Đã xóa {{count}} hộ.',
    statusChange: 'Đã chuyển trạng thái hộ.',
  },
  service: {
    noEmployeeProfile: 'Tài khoản chưa gắn hồ sơ nhân viên nên chưa lưu được.',
  },
  validation: {
    hoTenRequired: 'Nhập họ và tên đại diện hộ.',
    doiTuongInvalid: 'Đối tượng chưa hợp lệ.',
    tonGiaoInvalid: 'Tôn giáo chỉ nhận Có hoặc Không.',
    trangThaiInvalid: 'Trạng thái chưa hợp lệ.',
  },
  noExportData: 'Không có dữ liệu để xuất.',
};
