export const matTranThietLapLuong = {
  noViewPermission: 'Bạn không có quyền xem thiết lập lương.',
  noCreatePermission: 'Bạn không có quyền thêm dữ liệu thiết lập lương.',
  noEditPermission: 'Bạn không có quyền sửa dữ liệu thiết lập lương.',
  noDeletePermission: 'Bạn không có quyền xóa dữ liệu thiết lập lương.',
  tabNgach: 'Ngạch lương',
  tabBac: 'Bậc lương',
  deleteTitle: 'Xóa ngạch lương?',
  deleteMessage: 'Ngạch và toàn bộ bậc lương liên quan sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều ngạch?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} ngạch và mọi bậc lương thuộc các ngạch đó.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'ngach-luong',
  listLoadErrorHint: 'Không tải được danh sách ngạch lương.',
  toast: {
    create: 'Đã tạo ngạch lương.',
    update: 'Đã cập nhật ngạch lương.',
    delete: 'Đã xóa {{count}} ngạch.',
    bacHeSo: 'Đã cập nhật hệ số bậc.',
    bacCreate: 'Đã thêm bậc lương.',
    bacUpdate: 'Đã cập nhật bậc lương.',
    bacDelete: 'Đã xóa bậc lương.',
    mlcs: 'Đã cập nhật mức lương cơ sở.',
  },
  service: {
    notFound: 'Không tìm thấy bản ghi.',
  },
  validation: {
    tenRequired: 'Nhập tên ngạch.',
    maMax: 'Mã ngạch tối đa 64 ký tự.',
    heSoInvalid: 'Hệ số phải là số dương.',
    mlcsPositive: 'Mức lương cơ sở phải là số dương.',
    bacMaInvalid: 'Chọn mã bậc B1–B9.',
    bacMaDuplicate: 'Mã bậc này đã tồn tại cho ngạch đang chọn.',
  },
  store: {
    thuTuCol: 'Thứ tự',
    maCol: 'Mã',
    tenCol: 'Tên ngạch',
    moTaCol: 'Mô tả',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    titleNgach: 'Ngạch lương',
  },
  searchPlaceholder: 'Tìm theo mã, tên, mô tả…',
  filterMoTaChipPlaceholder: 'Mô tả',
  filterMoTaHas: 'Có mô tả',
  filterMoTaEmpty: 'Không mô tả',
  emptyTitle: 'Chưa có ngạch lương',
  emptyHint: 'Thêm ngạch để hệ thống tự tạo bậc B1–B9.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionMain: 'Thông tin ngạch',
    createSubtitle: 'Thêm ngạch lương mới',
    editSubtitle: 'Cập nhật ngạch',
    ma: 'Mã ngạch',
    ten: 'Tên ngạch',
    moTa: 'Mô tả',
    thuTu: 'Thứ tự hiển thị',
  },
  detail: {
    title: 'Chi tiết ngạch lương',
    systemInfo: 'Hệ thống',
    sectionBac: 'Bậc lương',
    bacChildRecordsSuffix: 'bậc',
    noBac: 'Chưa có bậc lương',
    noBacHint: 'Thêm bậc B1–B9 hoặc dùng nút Thêm trên ngạch mới (tự seed 9 bậc).',
  },
  bac: {
    searchPlaceholder: 'Tìm theo bậc, hệ số, lương…',
    filterNgachChipPlaceholder: 'Ngạch lương',
    filterNgachSheetGroup: 'Ngạch lương',
    pickNgach: 'Chọn ngạch',
    pickNgachHint: 'Chọn một ngạch để xem và chỉnh hệ số B1–B9.',
    noNgach: 'Chưa có ngạch nào — hãy thêm ở tab Ngạch lương.',
    mlcsLabel: 'Mức lương cơ sở (VNĐ)',
    /** Nhãn ngắn trên toolbar (cạnh ô nhập MLCS). */
    mlcsToolbarLabel: 'Lương cơ sở',
    mlcsHint: 'Lương theo bậc = mức lương cơ sở × hệ số.',
    saveMlcs: 'Lưu mức lương cơ sở',
    colNgach: 'Ngạch',
    colBac: 'Bậc',
    colHeSo: 'Hệ số',
    colLuong: 'Lương (VNĐ)',
    emptyBac: 'Không có bậc cho ngạch này.',
    allSlotsFull: 'Đã đủ 9 bậc (B1–B9) cho ngạch này.',
    addPickNgach: 'Chọn ngạch trước khi thêm bậc.',
    deleteTitle: 'Xóa bậc lương?',
    deleteMessage: 'Bậc {{ma}} sẽ bị xóa. Bạn có thể thêm lại mã bậc đó sau.',
    form: {
      sectionMain: 'Thông tin bậc',
      createSubtitle: 'Thêm bậc lương',
      editSubtitle: 'Cập nhật bậc lương',
      maBac: 'Mã bậc',
      maBacHint: 'Chỉ dùng mã B1–B9 theo quy định.',
    },
    detail: {
      title: 'Chi tiết bậc lương',
      systemInfo: 'Hệ thống',
      ngach: 'Ngạch',
    },
  },
};
