/** Thông tin tổ chức + thương hiệu (MTTQVN) */
export const company = {
  noViewPermission: 'Bạn không có quyền xem module Thông tin tổ chức.',
  title: 'Thông tin tổ chức',
  description: 'Cấu hình tên ứng dụng MTTQVN, logo (Quốc huy), mô tả ngắn và thông tin liên hệ hiển thị trên hệ thống.',
  brandSection: 'Thương hiệu & Logo',
  dropImage: 'Thả ảnh vào đây',
  upload: 'Tải lên',
  dragDrop: 'Kéo thả',
  capture: 'Chụp',
  imageHint: 'Hỗ trợ PNG, JPG, WebP. Tối đa 2MB. Hoặc dán URL ảnh công khai bên dưới.',
  logoUrl: 'URL logo',
  logoUrlPlaceholder: 'https://…/logo.png',
  logoUrlHint: 'Dùng link ảnh online (CDN, Cloudinary) thay cho tải file. Logo dùng cho sidebar, favicon và PWA.',
  appName: 'Tên ứng dụng',
  appNamePlaceholder: 'Ví dụ: MTTQVN',
  appNameHint: 'Hiển thị trên thanh bên và tiêu đề trình duyệt.',
  appDescription: 'Mô tả ngắn',
  appDescPlaceholder: 'Ví dụ: Hệ thống nền tảng số',
  appDescHint: 'Hiển thị dưới tên ứng dụng trên thanh bên (tối đa 30 ký tự).',
  legalSection: 'Định danh tổ chức & liên hệ',
  companyName: 'Tên tổ chức',
  companyNamePlaceholder: 'Ví dụ: Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh…',
  phone: 'Số điện thoại',
  phonePlaceholder: '(+84) ...',
  email: 'Email liên hệ',
  emailPlaceholder: 'contact@example.org',
  website: 'Website',
  websitePlaceholder: 'www.example.org',
  address: 'Địa chỉ trụ sở',
  addressPlaceholder: 'Số nhà, đường, phường/xã…',
  saveButton: 'Lưu thông tin',
  imageTypeError: 'Vui lòng chỉ tải lên file hình ảnh.',
  imageSizeError: 'Kích thước ảnh không được vượt quá 2MB',
  saveSuccess: 'Cập nhật thông tin tổ chức thành công!',
  validation: {
    appNameMin: 'Tên ứng dụng quá ngắn',
    appDescMax: 'Mô tả ngắn không được quá 30 ký tự',
    companyNameMin: 'Tên tổ chức là bắt buộc',
    emailInvalid: 'Email không hợp lệ',
    logoUrlInvalid: 'URL logo không hợp lệ',
  },
} as const;
