/** Báo cáo công việc — chuỗi UI (taskReport.*) */
export const taskReport = {
  title: 'Báo cáo công việc',
  subtitle: 'Tra cứu, thống kê và theo dõi tiến độ công việc trong kỳ',
  accessDenied: 'Bạn không có quyền xem báo cáo công việc.',
  loading: 'Đang tải báo cáo…',
  noData: 'Không có dữ liệu phù hợp với bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng thời gian hoặc bỏ bớt bộ lọc.',

  dateRangeLabel: 'Khoảng ngày tạo',
  filterTrachNhiem: 'Người trách nhiệm',
  filterNguoiTao: 'Người giao',
  filterTrangThai: 'Trạng thái',
  filterMucDo: 'Mức độ',
  filterOverdueOnly: 'Chỉ quá hạn',

  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'BC_Cong_Viec',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',

  kpiTotal: 'Tổng số việc',
  kpiMoi: 'Mới',
  kpiDang: 'Đang thực hiện',
  kpiHoanThanh: 'Hoàn thành',
  kpiQuaHan: 'Quá hạn',
  kpiSapHetHan: 'Sắp hết hạn (≤ 3 ngày)',
  kpiHoanThanhDungHan: '% hoàn thành đúng hạn',
  kpiDistinctTrachNhiem: 'Người trách nhiệm',

  chartTrendTitle: 'Xu hướng theo thời gian',
  chartTrendCreated: 'Tạo mới',
  chartTrendDone: 'Hoàn thành',
  chartTrendOverdue: 'Quá hạn',
  chartPhanBoTrangThai: 'Phân bố theo trạng thái',
  chartPhanBoMucDo: 'Phân bố theo mức độ',
  chartTopTrachNhiem: 'Top người trách nhiệm',

  tableTopTrachNhiem: 'Top theo % hoàn thành (Trách nhiệm)',
  tableTopNguoiTao: 'Top người giao việc',
  tableLookupTitle: 'Tra cứu chi tiết',

  tableColTen: 'Tên công việc',
  tableColMucDo: 'Mức độ',
  tableColTrangThai: 'Trạng thái',
  tableColThoiHan: 'Thời hạn',
  tableColTienDo: 'Tiến độ (theo hạn)',
  tableColTrachNhiem: 'Trách nhiệm',
  tableColNguoiTao: 'Người giao',
  tableColTgCapNhat: 'Cập nhật',
  tableColTotal: 'Tổng',
  tableColHoanThanh: 'Hoàn thành',
  tableColDang: 'Đang',
  tableColQuaHan: 'Quá hạn',
  tableColCompletionRate: '% hoàn thành',
  tableColPerson: 'Nhân viên',

  paginationLabel: 'Hiển thị {{from}}–{{to}} / {{total}}',
  paginationEmpty: 'Chưa có bản ghi',
  rowsPerPage: 'Số dòng/trang',
  sortBy: 'Sắp xếp',
  noViewPermission: 'Bạn không có quyền xem báo cáo công việc.',

  preset: {
    all: 'Tất cả',
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    thisQuarter: 'Quý này',
    thisYear: 'Năm nay',
    custom: 'Tùy chọn',
  },

  sort: {
    thoi_han_desc: 'Thời hạn ↓',
    thoi_han_asc: 'Thời hạn ↑',
    tien_do_desc: 'Tiến độ ↓',
    trang_thai_asc: 'Trạng thái ↑',
    tg_cap_nhat_desc: 'Cập nhật ↓',
  },
} as const;
