export const matTranKhenThuong = {
  noViewPermission: 'Bạn không có quyền xem khen thưởng.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo quyết định khen thưởng.',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy bản ghi khen thưởng.',
  },
  deleteTitle: 'Xóa quyết định khen thưởng?',
  deleteMessage: 'Toàn bộ dòng chi tiết theo quyết định này cũng sẽ bị xóa.',
  bulkDeleteTitle: 'Xóa nhiều quyết định?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} quyết định và toàn bộ dòng chi tiết liên quan.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-khen-thuong',
  toast: {
    create: 'Đã tạo quyết định khen thưởng.',
    update: 'Đã cập nhật quyết định khen thưởng.',
    delete: 'Đã xóa {{count}} quyết định.',
  },
  validation: {
    noiDungKhenRequired: 'Nhập nội dung khen.',
    ngayRequired: 'Chọn ngày khen thưởng.',
    trangThaiRequired: 'Chọn trạng thái.',
    canBoRequired: 'Chọn cán bộ.',
    capKhenThuongRequired: 'Chọn cấp khen thưởng.',
    hinhThucRequired: 'Chọn hình thức khen.',
    danhHieuRequired: 'Chọn danh hiệu.',
    chiTietMin: 'Cần ít nhất một dòng chi tiết (cán bộ được khen).',
  },
  filter: {
    namChip: 'Năm khen thưởng',
    donViNone: '— Trống —',
    phongBanNone: '— Chưa gán phòng ban —',
    phongBanNguoiTaoChip: 'Phòng ban người tạo',
  },
  store: {
    soQdCol: 'Số QĐ',
    noiDungKhenCol: 'Nội dung khen',
    ngayCol: 'Ngày khen',
    donViCol: 'Đơn vị khen',
    trangThaiCol: 'Trạng thái',
    soDongCol: 'Số người',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Khen thưởng',
  },
  tabs: {
    danhSach: 'Danh sách',
    chiTietList: 'Chi tiết',
    thongKe: 'Thống kê',
  },
  chiTietList: {
    searchPlaceholder: 'Tìm theo số quyết định, nội dung khen, cán bộ, hình thức, danh hiệu…',
    emptyTitle: 'Chưa có dòng chi tiết',
    emptyHint: 'Thêm người được khen trong quyết định hoặc đổi bộ lọc.',
    cols: {
      tenCanBo: 'Cán bộ',
      tgCapNhatQd: 'Cập nhật QĐ',
    },
  },
  stats: {
    loading: 'Đang tải dữ liệu…',
    noData: 'Không có dữ liệu khen thưởng trong phạm vi bạn được xem.',
    noDataHint: 'Thêm quyết định hoặc kiểm tra bộ lọc trên tab Danh sách / Chi tiết.',
    kpiTotalQd: 'Tổng quyết định',
    kpiTotalNguoi: 'Tổng số người được khen (dòng chi tiết)',
    chartTrangThai: 'Theo trạng thái',
    chartNam: 'Theo năm (ngày khen thưởng)',
    tableTopDonVi: 'Đơn vị khen (Top)',
    colLabel: 'Nhóm',
    colValue: 'Số lượng',
  },
  searchPlaceholder: 'Tìm theo số quyết định, nội dung khen, đơn vị, trạng thái…',
  emptyTitle: 'Chưa có quyết định khen thưởng',
  emptyHint: 'Thêm quyết định mới để bắt đầu.',
  form: {
    sectionHeader: 'Quyết định',
    sectionChiTiet: 'Danh sách được khen',
    soQd: 'Số quyết định',
    soQdPlaceholder: 'VD: 12/QĐ-MTTQ-BTT — để trống nếu chưa có số',
    noiDungKhen: 'Nội dung khen',
    ngayKhenThuong: 'Ngày khen thưởng',
    donViDeXuat: 'Đơn vị khen',
    ghiChu: 'Ghi chú',
    trangThai: 'Trạng thái',
    addLine: 'Thêm người được khen',
    removeLine: 'Xóa dòng',
    canBo: 'Cán bộ',
    capKhenThuong: 'Cấp khen thưởng',
    hinhThuc: 'Hình thức khen',
    danhHieu: 'Danh hiệu',
    noiDung: 'Nội dung khen',
    hoSo: 'Hồ sơ / liên kết',
    createSubtitle: 'Tạo quyết định khen thưởng mới',
    editSubtitle: 'Sửa quyết định',
    chiTietEmptyHint: 'Chưa có người được khen. Bấm nút Thêm người được khen để thêm dòng.',
  },
  chiTietDrawer: {
    titleAdd: 'Thêm người được khen',
    titleEdit: 'Sửa dòng khen thưởng',
    cannotDeleteLast: 'Cần ít nhất một người được khen trong quyết định — không thể xóa dòng cuối.',
    deleteLineTitle: 'Xóa dòng này?',
    deleteLineMessage: 'Dòng sẽ bị xóa khỏi danh sách (chưa lưu DB cho đến khi bạn lưu quyết định).',
  },
  detail: {
    title: 'Chi tiết khen thưởng',
    sectionHeader: 'Thông tin quyết định',
    sectionChiTiet: 'Người được khen',
    emptyChiTiet: 'Chưa có dòng chi tiết.',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    toolbarChangeStatus: 'Chuyển trạng thái',
  },
  /** Popup giữa màn (GenericDrawer variant=modal) — xem docs/patterns-detail-status-change.md */
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Cập nhật trạng thái quyết định và ghi chú kèm theo.',
    section: 'Trạng thái & ghi chú',
    ghiChuPlaceholder: 'Ghi chú nội bộ (tùy chọn)…',
    save: 'Cập nhật',
  },
  printPreview: {
    pageTitleQuyetDinh: 'Xem trước — Quyết định khen thưởng',
    pageTitleDeNghi: 'Xem trước — Danh sách đề nghị khen thưởng',
    print: 'In',
    download: 'Tải',
    downloadPdf: 'PDF',
    downloadDocx: 'Docx',
    fileNameQuyetDinh: 'quyet-dinh-khen-thuong',
    fileNameDeNghi: 'danh-sach-de-nghi-khen-thuong',
    printQuyetDinh: 'In quyết định',
    printDeNghi: 'In danh sách đề nghị',
    printEmpty: 'Không có người được khen trong phạm vi xem — không thể in.',
    printPopupBlocked: 'Trình duyệt chặn cửa sổ in. Cho phép popup cho trang này.',
    notFound: 'Không tìm thấy quyết định khen thưởng.',
    empty: 'Không có người được khen trong phạm vi xem.',
    coQuanChuQuan: 'Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh Nghệ An',
    banThuongTruc: 'Ban Thường trực',
    coQuanMacDinh: 'Ban Thường trực Ủy ban MTTQ Việt Nam tỉnh Nghệ An',
    thamQuyen: 'Ban Thường trực Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh Nghệ An',
    tenLoaiQuyetDinh: 'Quyết định',
    trichYeuQuyetDinh: 'Về việc tặng {{danhHieu}}',
    tenLoaiDeNghi: 'Danh sách đề nghị khen thưởng',
    trichYeuDeNghi: '(Kèm theo Tờ trình đề nghị khen thưởng của Ban Thường trực Ủy ban MTTQ Việt Nam tỉnh Nghệ An)',
    danhHieuMacDinh: 'Giấy khen',
    canCuDieuLe: 'Căn cứ Điều lệ Mặt trận Tổ quốc Việt Nam;',
    canCuQuyChe: 'Căn cứ Quy chế thi đua, khen thưởng của Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh Nghệ An;',
    canCuDeNghi: 'Xét đề nghị của Ban Thi đua — Khen thưởng.',
    canCuDeNghiDonVi: 'Xét đề nghị của {{donVi}}.',
    dieu1: 'Điều 1.',
    dieu1Noi: 'Tặng {{danhHieu}} cho {{soLuong}} cán bộ có tên trong danh sách kèm theo, đã có thành tích: {{thanhTich}}.',
    dieu1DanhSach: '(Danh sách cán bộ được khen thưởng)',
    dieu2: 'Điều 2.',
    dieu2Noi: 'Các cán bộ có tên tại Điều 1 được hưởng các quyền lợi khen thưởng theo quy định hiện hành.',
    dieu3: 'Điều 3.',
    dieu3Noi: 'Văn phòng Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh, các ban chuyên môn có liên quan và các cán bộ có tên tại Điều 1 chịu trách nhiệm thi hành Quyết định này.',
    thanhTichNhieuLoai: 'có thành tích xuất sắc theo nội dung khen ghi tại danh sách kèm theo',
    thanhTichMacDinh: 'có thành tích xuất sắc trong công tác Mặt trận',
    noiNhan1: 'Như Điều 3',
    noiNhan2: 'Lưu: VT, TĐKT',
    noiNhan3: 'Đơn vị có cán bộ được khen',
    kyThayMat: 'TM. Ban Thường trực',
    kyChucDanh: 'Chủ tịch',
    kyNguoiLap: 'Người lập biểu',
    colStt: 'STT',
    colHoTen: 'Họ và tên',
    colChucVuDonVi: 'Chức vụ, đơn vị công tác',
    colCapKhenThuong: 'Cấp khen thưởng',
    colDanhHieu: 'Danh hiệu',
    colHinhThuc: 'Hình thức khen',
    colNoiDungKhen: 'Nội dung khen',
    metaSoQd: 'Số quyết định',
    metaSoQdChuaCo: '……../QĐ-MTTQ-BTT',
    metaNgay: 'Ngày khen thưởng',
    metaDonViDeXuat: 'Đơn vị đề xuất',
    metaTrangThai: 'Trạng thái',
    metaSoNguoi: 'Số người được khen',
    metaNgayIn: 'Ngày in',
    canhBaoSoQd:
      'Quyết định này chưa có số hợp lệ — ô « Số: » trên bản in để trống để điền tay.',
    soQdTrong: '(chưa có số)',
  },
};
