export const matTranKhenThuong = {
  noViewPermission: 'Bạn không có quyền xem danh sách khen thưởng.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo quyết định khen thưởng.',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy bản ghi khen thưởng.',
  },
  deleteTitle: 'Xóa quyết định khen thưởng?',
  deleteMessage: 'Toàn bộ dòng chi tiết theo quyết định này cũng sẽ bị xóa.',
  bulkDeleteTitle: 'Xóa nhiều quyết định?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} quyết định và toàn bộ dòng chi tiết liên quan.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-khen-thuong',
  toast: {
    create: 'Đã tạo quyết định khen thưởng.',
    update: 'Đã cập nhật quyết định khen thưởng.',
    delete: 'Đã xóa {{count}} quyết định.',
  },
  validation: {
    soQdRequired: 'Nhập số quyết định.',
    ngayRequired: 'Chọn ngày khen thưởng.',
    trangThaiRequired: 'Chọn trạng thái.',
    canBoRequired: 'Chọn cán bộ.',
    hinhThucRequired: 'Chọn hình thức khen.',
    danhHieuRequired: 'Chọn danh hiệu.',
    chiTietMin: 'Cần ít nhất một dòng chi tiết (cán bộ được khen).',
  },
  filter: {
    namChip: 'Năm khen thưởng',
    donViNone: '— Trống —',
    phongBanNone: '— Chưa gán phòng ban —',
    phongBanNguoiTaoChip: 'Phòng ban người tạo',
  },
  store: {
    soQdCol: 'Số QĐ',
    ngayCol: 'Ngày khen',
    donViCol: 'Đơn vị đề xuất',
    trangThaiCol: 'Trạng thái',
    soDongCol: 'Số người',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Danh sách khen thưởng',
  },
  tabs: {
    danhSach: 'Danh sách',
    chiTietList: 'Chi tiết',
    thongKe: 'Thống kê',
  },
  chiTietList: {
    searchPlaceholder: 'Tìm theo số QĐ, cán bộ, hình thức, danh hiệu…',
    emptyTitle: 'Chưa có dòng chi tiết',
    emptyHint: 'Thêm người được khen trong quyết định hoặc đổi bộ lọc.',
    cols: {
      tenCanBo: 'Cán bộ',
      tgCapNhatQd: 'Cập nhật QĐ',
    },
  },
  stats: {
    loading: 'Đang tải dữ liệu…',
    noData: 'Không có dữ liệu khen thưởng trong phạm vi bạn được xem.',
    noDataHint: 'Thêm quyết định hoặc kiểm tra bộ lọc trên tab Danh sách / Chi tiết.',
    kpiTotalQd: 'Tổng quyết định',
    kpiTotalNguoi: 'Tổng số người được khen (dòng chi tiết)',
    chartTrangThai: 'Theo trạng thái',
    chartNam: 'Theo năm (ngày khen thưởng)',
    tableTopDonVi: 'Đơn vị đề xuất (Top)',
    colLabel: 'Nhóm',
    colValue: 'Số lượng',
  },
  searchPlaceholder: 'Tìm theo số QĐ, đơn vị, trạng thái…',
  emptyTitle: 'Chưa có quyết định khen thưởng',
  emptyHint: 'Thêm quyết định mới để bắt đầu.',
  form: {
    sectionHeader: 'Quyết định',
    sectionChiTiet: 'Danh sách được khen',
    soQd: 'Số quyết định',
    ngayKhenThuong: 'Ngày khen thưởng',
    donViDeXuat: 'Đơn vị đề xuất',
    ghiChu: 'Ghi chú',
    trangThai: 'Trạng thái',
    addLine: 'Thêm người được khen',
    removeLine: 'Xóa dòng',
    canBo: 'Cán bộ',
    hinhThuc: 'Hình thức khen',
    danhHieu: 'Danh hiệu',
    noiDung: 'Nội dung khen',
    hoSo: 'Hồ sơ / liên kết',
    createSubtitle: 'Tạo quyết định khen thưởng mới',
    editSubtitle: 'Sửa quyết định',
    chiTietEmptyHint: 'Chưa có người được khen. Bấm nút Thêm người được khen để thêm dòng.',
  },
  chiTietDrawer: {
    titleAdd: 'Thêm người được khen',
    titleEdit: 'Sửa dòng khen thưởng',
    cannotDeleteLast: 'Cần ít nhất một người được khen trong quyết định — không thể xóa dòng cuối.',
    deleteLineTitle: 'Xóa dòng này?',
    deleteLineMessage: 'Dòng sẽ bị xóa khỏi danh sách (chưa lưu DB cho đến khi bạn lưu quyết định).',
  },
  detail: {
    title: 'Chi tiết khen thưởng',
    sectionHeader: 'Thông tin quyết định',
    sectionChiTiet: 'Người được khen',
    emptyChiTiet: 'Chưa có dòng chi tiết.',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    toolbarChangeStatus: 'Chuyển trạng thái',
  },
  /** Popup giữa màn (GenericDrawer variant=modal) — xem docs/patterns-detail-status-change.md */
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Cập nhật trạng thái quyết định và ghi chú kèm theo.',
    section: 'Trạng thái & ghi chú',
    ghiChuPlaceholder: 'Ghi chú nội bộ (tùy chọn)…',
    save: 'Cập nhật',
  },
};
