/** Thống kê thăm hỏi */
export const dttgThongKeThamHoi = {
  title: 'Thống kê thăm hỏi',
  noViewPermission: 'Bạn không có quyền xem thống kê thăm hỏi.',
  loading: 'Đang tải thống kê…',
  noData: 'Không có dữ liệu trong khoảng và bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng thời gian hoặc bỏ bớt bộ lọc.',
  noExportData: 'Không có dữ liệu để xuất',
  dateRangeLabel: 'Khoảng thời gian',
  exportFileName: 'Thong_Ke_Tham_Hoi',
  exportRangeFrom: 'Từ ngày (báo cáo)',
  exportRangeTo: 'Đến ngày (báo cáo)',
  stats: {
    exportData: 'Export dữ liệu',
    clearFilters: 'Xóa bộ lọc',
    filterLoai: 'Loại thăm hỏi',
    filterLoaiToChuc: 'Tổ chức',
    filterLoaiCaNhan: 'Cá nhân',
    filterTinhTrang: 'Tình trạng',
    filterDipThamHoi: 'Dịp thăm hỏi',
    kpiTotal: 'Tổng lượt thăm hỏi',
    kpiToChuc: 'Thăm hỏi tổ chức',
    kpiCaNhan: 'Thăm hỏi cá nhân',
    kpiHoanThanh: 'Đã hoàn thành',
    kpiDangThucHien: 'Đang thực hiện',
    kpiChuaThucHien: 'Chưa thực hiện',
    chartTrend: 'Xu hướng theo thời gian',
    chartTinhTrang: 'Theo tình trạng',
    chartLoai: 'Theo loại thăm hỏi',
    chartDipThamHoi: 'Theo dịp thăm hỏi',
    chartByYear: 'Theo năm',
    chartSeriesSoDot: 'Số đợt',
    chartSeriesTongLuot: 'Tổng lượt',
    tableByYear: 'Thống kê theo năm',
    tableColNam: 'Năm',
    tableColSoDot: 'Số đợt',
    tableColTongLuot: 'Tổng lượt',
    tableLookupTitle: 'Tra cứu',
    tableColLoai: 'Loại',
    tableColTenDoiTuong: 'Đối tượng',
    tableColLoaiHinh: 'Loại hình',
    tableColDipThamHoi: 'Dịp thăm hỏi',
    tableColDonViThamHoi: 'Đơn vị thăm hỏi',
    tableColTinhTrang: 'Tình trạng',
    tableColThoiGianDuKien: 'Thời gian dự kiến',
    tableColThoiGianThucTe: 'Thời gian thực tế',
    tableColTgTao: 'Ngày tạo',
    tableTwoColLabel: 'Nhóm',
    tableTwoColValue: 'Số lượng',
  },
} as const;
