import type { ThucHienPhanBien } from './core/types';

export const PBXH_THUC_HIEN_MOCK: ThucHienPhanBien[] = [
  {
    id: '1',
    cap_thuc_hien: 'Cấp tỉnh',
    loai_hinh: 'Giám sát',
    noi_dung: 'Giám sát việc thực hiện chính sách hỗ trợ người nghèo',
    doi_tuong_id: '1',
    ten_doi_tuong: 'Sở Lao động - Thương binh và Xã hội',
    hinh_thuc_id: '20',
    ten_hinh_thuc: 'Thành lập đoàn giám sát liên ngành',
    ngay_bat_dau: '2026-03-01',
    ngay_ket_thuc: '2026-06-30',
    mo_ta_thoi_gian: null,
    tinh_trang: 'Đang thực hiện',
    don_vi_chu_tri_id: '13',
    ten_don_vi_chu_tri: 'Ban Thường trực MTTQ tỉnh',
    phong_ban_tham_muu_id: null,
    ten_phong_ban: null,
    don_vi_thuc_hien_id: null,
    ten_don_vi_thuc_hien: null,
    ket_qua_kien_nghi: 'Đang tổng hợp báo cáo',
    phan_tram_hoan_thanh: 0,
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '2',
    cap_thuc_hien: 'Cấp tỉnh',
    loai_hinh: 'Phản biện',
    noi_dung: 'Phản biện dự thảo Nghị quyết về phát triển kinh tế - xã hội địa phương',
    doi_tuong_id: '3',
    ten_doi_tuong: 'UBND tỉnh (Cơ quan soạn thảo)',
    hinh_thuc_id: '21',
    ten_hinh_thuc: 'Tổ chức hội nghị phản biện xã hội',
    ngay_bat_dau: null,
    ngay_ket_thuc: '2026-09-30',
    mo_ta_thoi_gian: 'Quý III/2026',
    tinh_trang: 'Đã lập kế hoạch',
    don_vi_chu_tri_id: '14',
    ten_don_vi_chu_tri: 'Ban Thường vụ Tỉnh Đoàn',
    phong_ban_tham_muu_id: null,
    ten_phong_ban: null,
    don_vi_thuc_hien_id: null,
    ten_don_vi_thuc_hien: null,
    ket_qua_kien_nghi: 'Chưa thực hiện',
    phan_tram_hoan_thanh: 0,
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-02T00:00:00.000Z',
    tg_cap_nhat: '2026-01-02T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
];
