export const pbxhThucHien = {
  noViewPermission: 'Bạn không có quyền xem module Kiểm tra, GS và PBXH.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  searchPlaceholder: 'Tìm theo nội dung, đối tượng, đơn vị…',
  empty: 'Chưa có bản ghi phản biện xã hội',
  deleteTitle: 'Xóa bản ghi',
  deleteMessage: 'Bạn có chắc muốn xóa bản ghi này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều bản ghi',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} bản ghi đã chọn? Hành động không hoàn tác.',
  detailTitle: 'Chi tiết phản biện xã hội',
  detail: {
    openLink: 'Mở link',
    systemInfo: 'Thông tin hệ thống',
  },
  tienDo: {
    conNgay: 'Còn {{count}} ngày',
    hetHanHomNay: 'Hết hạn hôm nay',
    quaHan: 'Quá hạn {{count}} ngày',
  },
  store: {
    capThucHienCol: 'Cấp thực hiện',
    loaiHinhCol: 'Loại hình',
    noiDungCol: 'Nội dung',
    doiTuongCol: 'Đối tượng KT, GS, PBXH',
    hinhThucCol: 'Hình thức thực hiện',
    ngayBatDauCol: 'Bắt đầu',
    ngayKetThucCol: 'Kết thúc',
    moTaThoiGianCol: 'Thời gian (mô tả)',
    tienDoCol: 'Tiến độ thực hiện',
    tinhTrangCol: 'Tình trạng',
    donViChuTriCol: 'Chủ trì',
    phongBanCol: 'Phòng ban tham mưu',
    donViThucHienCol: 'Đơn vị thực hiện',
    donViThucHienTinhCap: 'MTTQ Tỉnh',
    ketQuaCol: 'Kết quả / Kiến nghị',
    soLanHoanThanhCol: 'Số lần hoàn thành',
    soLanKhaoSatCol: 'Số lần khảo sát',
    phanTramCol: '% hoàn thành',
    linkKetQuaCol: 'Link kết quả',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm hoạt động phản biện xã hội',
    editSubtitle: 'Cập nhật hoạt động',
    sectionMain: 'Thông tin chính',
    sectionThoiGian: 'Thời gian',
    sectionDonVi: 'Đơn vị & kết quả',
  },
  toast: {
    create: 'Đã thêm bản ghi',
    update: 'Đã cập nhật bản ghi',
    delete: 'Đã xóa {{count}} bản ghi',
    importSuccess: 'Đã nhập {{count}} bản ghi',
  },
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập.',
    notFound: 'Không tìm thấy bản ghi',
  },
  validation: {
    noiDungRequired: 'Nhập nội dung',
    capThucHienInvalid: 'Chọn cấp thực hiện hợp lệ',
    loaiHinhInvalid: 'Chọn loại hình hợp lệ',
    tinhTrangInvalid: 'Chọn tình trạng hợp lệ',
    linkUrl: 'Link không hợp lệ',
    soLanHoanThanhMax: 'Số lần hoàn thành không được lớn hơn số lần khảo sát',
  },
};
