/** Chuỗi module Công việc — flatten vào STRINGS với prefix `taskList` */
export const taskList = {
  tabMineDo: 'Tôi làm',
  tabMineRelated: 'Tôi hỗ trợ',
  tabMineAssign: 'Tôi giao',
  store: {
    tenCol: 'Tên công việc',
    mucDoCol: 'Mức độ',
    thoiHanCol: 'Thời hạn',
    tienDoCol: 'Tiến độ (theo hạn)',
    trangThaiCol: 'Trạng thái',
    trachNhiemCol: 'Trách nhiệm',
    hoTroCol: 'Hỗ trợ',
    nguoiTaoCol: 'Người giao',
    tgCapNhatCol: 'Cập nhật',
    ghiChuCol: 'Ghi chú',
    chuongTrinhCol: 'Chương trình BTT',
  },
  form: {
    mucDo: 'Mức độ',
    tenCongViec: 'Tên công việc',
    ghiChu: 'Ghi chú',
    linkTaiLieu: 'Link tài liệu',
    thoiHan: 'Thời hạn',
    tienDo: 'Tiến độ (%)',
    trachNhiem: 'Người trách nhiệm',
    hoTro: 'Người hỗ trợ',
    trangThai: 'Trạng thái',
    ketQua: 'Kết quả',
    linkKq: 'Link kết quả',
    ngayHoanThanh: 'Ngày hoàn thành',
    chuongTrinhNam: 'Chương trình BTT',
    chuongTrinhNamPlaceholder: 'Chọn chương trình (tuỳ chọn)',
    createSubtitle: 'Thêm công việc mới',
    editSubtitle: 'Cập nhật công việc',
  },
  detail: {
    title: 'Chi tiết công việc',
    subtitle: 'Theo dõi tiến độ và phân công',
    chuongTrinhEmpty: 'Chưa gắn chương trình',
    sectionInfo: 'Thông tin công việc',
    sectionResult: 'Kết quả',
    openLink: 'Mở liên kết',
    actionReport: 'Báo cáo',
    actionCancelTask: 'Hủy công việc',
  },
  deadline: {
    cancelled: 'Đã hủy',
    completed: 'Đã hoàn thành',
    noDeadline: 'Chưa có thời hạn',
    dueToday: 'Hết hạn hôm nay',
    overdueDays: 'Quá hạn {{count}} ngày',
    remainingOneDay: 'Còn 1 ngày',
    remainingDays: 'Còn {{count}} ngày',
  },
  reportDialog: {
    title: 'Báo cáo công việc',
    subtitle: 'Cập nhật trạng thái và kết quả thực hiện',
    sectionResult: 'Kết quả',
    submit: 'Lưu báo cáo',
    ketQuaRequired: 'Vui lòng nhập kết quả khi trạng thái là Hoàn thành.',
  },
  cancelTask: {
    title: 'Hủy công việc',
    message: 'Trạng thái sẽ chuyển sang Hủy. Bạn có chắc muốn tiếp tục?',
  },
  deleteTitle: 'Xóa công việc',
  deleteMessage: 'Bạn có chắc muốn xóa công việc này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều công việc',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} công việc đã chọn? Hành động không hoàn tác.',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'Danh_Sach_Cong_Viec',
  toast: {
    create: 'Đã thêm công việc',
    update: 'Đã cập nhật công việc',
    delete: 'Đã xóa {{count}} công việc',
  },
  service: {
    notFound: 'Không tìm thấy công việc',
    noEmployeeProfile: 'Tài khoản chưa gắn hồ sơ nhân viên. Liên hệ quản trị để được gán trước khi thêm công việc.',
  },
  validation: {
    mucDoRequired: 'Chọn mức độ',
    tenCongViecRequired: 'Nhập tên công việc',
    tienDoRange: 'Tiến độ từ 0 đến 100',
    trachNhiemRequired: 'Chọn người trách nhiệm',
    trangThaiRequired: 'Chọn trạng thái',
    linkUrl: 'Liên kết phải là URL hợp lệ (https://...)',
    dateInvalid: 'Ngày không hợp lệ',
  },
  emptyTitle: 'Chưa có công việc',
  emptyHint: 'Thêm công việc mới hoặc điều chỉnh bộ lọc / tab.',
  noViewPermission: 'Bạn không có quyền xem module Công việc.',
  searchPlaceholder: 'Tìm theo tên, mức độ, trạng thái, người hỗ trợ…',
  filterChuongTrinh: 'Chương trình BTT',
  noEmployeeForTabs:
    'Tài khoản chưa gắn hồ sơ nhân viên: các tab (Tôi làm / Tôi hỗ trợ / Tôi giao) tạm thời không lọc theo người — danh sách hiển thị toàn bộ bản ghi bạn được phép xem. Liên hệ quản trị để gán nhân viên cho đúng nghiệp vụ.',
} as const;
