export const matTranTapHuan = {
  noViewPermission: 'Bạn không có quyền xem tập huấn.',
  noEmployeeBanner:
    'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo lớp tập huấn.',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy lớp tập huấn.',
  },
  deleteTitle: 'Xóa lớp tập huấn?',
  deleteMessage: 'Toàn bộ dòng cán bộ tham gia lớp này cũng sẽ bị xóa.',
  bulkDeleteTitle: 'Xóa nhiều lớp tập huấn?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} lớp tập huấn và toàn bộ dòng cán bộ tham gia.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-tap-huan',
  toast: {
    create: 'Đã tạo lớp tập huấn.',
    update: 'Đã cập nhật lớp tập huấn.',
    delete: 'Đã xóa {{count}} lớp tập huấn.',
  },
  validation: {
    tenLopRequired: 'Nhập tên lớp tập huấn.',
    namRequired: 'Nhập năm tập huấn.',
    namInvalid: 'Năm tập huấn không hợp lệ (2000–2100).',
    capRequired: 'Chọn cấp tập huấn.',
    canBoRequired: 'Chọn cán bộ.',
    thuocDienRequired: 'Chọn thuộc diện.',
    chiTietMin: 'Cần ít nhất một cán bộ tham gia lớp.',
    canBoProfileIncomplete:
      'Không lấy được chức vụ / tổ chức từ hồ sơ cán bộ — kiểm tra danh sách cán bộ hoặc chọn cán bộ khác.',
    donViRequired: 'Chọn xã/phường (bắt buộc với lớp Cấp xã).',
    canBoDonViMismatch:
      'Với lớp Cấp xã, mỗi cán bộ tham gia phải thuộc đúng xã/phường đã chọn cho lớp (cùng đơn vị hồ sơ).',
  },
  tabs: {
    lop: 'Lớp tập huấn',
    chiTietList: 'Danh sách CT',
    thongKe: 'Thống kê',
  },
  stats: {
    loading: 'Đang tải số liệu…',
    noData: 'Không có dữ liệu trong phạm vi lọc.',
    noDataHint: 'Thử đổi bộ lọc cấp / năm hoặc mở rộng phạm vi xem.',
    scopeHint:
      'Danh sách lớp hiển thị đủ; số người tham gia và biểu đồ theo ứng viên chỉ gồm cán bộ thuộc đơn vị xã/phường của bạn.',
    noFlatData: 'Không có dòng chi tiết trong phạm vi lọc hiện tại.',
    kpiTotalLop: 'Tổng số lớp',
    kpiTotalNguoi: 'Tổng người tham gia (dòng CT)',
    chartCap: 'Phân bố theo cấp lớp',
    chartNam: 'Phân bố theo năm tập huấn',
    chartThuocDien: 'Người tham gia theo thuộc diện',
    tableTopDonVi: 'Top đơn vị (theo số lớp)',
    tableTopLop: 'Top lớp (theo số người)',
    colLabel: 'Đơn vị',
    colValue: 'Số lượng',
    colTenLop: 'Lớp tập huấn',
    colSoNguoi: 'Số người',
    donViNone: '— (chưa gán đơn vị)',
    donViLopChip: 'Đơn vị lớp',
    thuocDienChip: 'Thuộc diện',
  },
  chiTietList: {
    searchPlaceholder: 'Tìm theo lớp, cán bộ, tổ chức, phòng ban…',
    exportFileName: 'danh-sach-tap-huan-chi-tiet',
    emptyTitle: 'Chưa có dòng chi tiết tham gia',
    emptyHint: 'Thêm cán bộ vào lớp tập huấn hoặc đổi bộ lọc.',
    lopChip: 'Lớp tập huấn',
    pickLopTitle: 'Chọn lớp tập huấn',
    pickLopSubtitle: 'Chọn lớp để thêm cán bộ tham gia.',
    pickLopRequired: 'Chọn lớp tập huấn.',
    noLopToAdd: 'Chưa có lớp tập huấn — tạo lớp trước khi thêm cán bộ.',
    viewLop: 'Xem lớp',
    cols: {
      donViLop: 'Đơn vị lớp (xã/phường)',
      tgCapNhatLop: 'Cập nhật lớp',
    },
  },
  store: {
    tenLopCol: 'Lớp tập huấn',
    namCol: 'Năm',
    capCol: 'Cấp',
    donViCol: 'Đơn vị (xã/phường)',
    soDongCol: 'Số người',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Tập huấn',
  },
  searchPlaceholder: 'Tìm theo tên lớp, cấp, ghi chú…',
  emptyTitle: 'Chưa có lớp tập huấn',
  emptyHint: 'Thêm lớp tập huấn mới để bắt đầu.',
  form: {
    sectionHeader: 'Lớp tập huấn',
    sectionChiTiet: 'Cán bộ tham gia',
    tenLop: 'Tên lớp tập huấn',
    namTapHuan: 'Năm tập huấn',
    capTapHuan: 'Cấp tập huấn',
    donVi: 'Xã/phường',
    donViHint: 'Áp dụng khi chọn Cấp xã — chọn xã/phường.',
    ghiChu: 'Ghi chú',
    addLine: 'Thêm cán bộ',
    canBo: 'Cán bộ',
    hoVaTen: 'Họ và tên',
    chucVu: 'Chức vụ',
    /** Cột / snapshot: tổ chức + phòng ban (tự lấy từ Danh sách cán bộ). */
    toChucPhongBan: 'Tổ chức — phòng ban',
    donViCongTac: 'Đơn vị công tác',
    chiTietSnapshotHint:
      'Tổ chức, phòng ban và chức vụ hiển thị theo hồ sơ cán bộ — chọn cán bộ ở trên để cập nhật.',
    thuocDien: 'Thuộc diện',
    createSubtitle: 'Tạo lớp tập huấn mới',
    editSubtitle: 'Sửa lớp tập huấn',
    chiTietEmptyHint:
      'Chưa có cán bộ tham gia. Bấm nút Thêm cán bộ để thêm dòng.',
  },
  chiTietDrawer: {
    /** Drawer chỉ đọc khi bấm vào dòng trong màn chi tiết lớp. */
    lineDetailTitle: 'Chi tiết cán bộ tham gia',
    titleAdd: 'Thêm cán bộ tham gia',
    titleEdit: 'Sửa cán bộ tham gia',
    cannotDeleteLast: 'Cần ít nhất một cán bộ tham gia lớp — không thể xóa dòng cuối.',
    deleteLineTitle: 'Xóa dòng này?',
    deleteLineMessage:
      'Dòng sẽ bị xóa khỏi danh sách (chưa lưu DB cho đến khi bạn lưu lớp tập huấn).',
  },
  detail: {
    title: 'Chi tiết lớp tập huấn',
    printList: 'In danh sách',
    printListEmpty: 'Không có cán bộ trong phạm vi xem để in.',
    sectionHeader: 'Thông tin lớp',
    sectionChiTiet: 'Cán bộ tham gia',
    emptyChiTiet: 'Chưa có cán bộ tham gia.',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
  printPreview: {
    pageTitle: 'Xem trước — Danh sách cán bộ tham gia',
    documentTitle: 'DANH SÁCH CÁN BỘ THAM GIA LỚP TẬP HUẤN',
    print: 'In',
    download: 'Tải',
    downloadPdf: 'PDF',
    downloadDocx: 'Docx',
    downloadXlsx: 'Excel (.xlsx)',
    fileName: 'danh-sach-can-bo-lop-tap-huan',
    empty: 'Không có cán bộ trong phạm vi xem.',
    notFound: 'Không tìm thấy lớp tập huấn.',
    colStt: 'STT',
    metaLop: 'Lớp',
    metaNam: 'Năm',
    metaCap: 'Cấp',
    metaDonVi: 'Đơn vị (xã/phường)',
    signedDate: 'Ngày in',
    footerNguoiTao: 'Người tạo',
    footerNguoiKiemTra: 'Người kiểm tra',
    footerNguoiPheDuyet: 'Người phê duyệt',
    printPopupBlocked: 'Trình duyệt chặn cửa sổ in. Cho phép popup cho trang này.',
  },
};
