export const matTranTapHuan = {
  noViewPermission: 'Bạn không có quyền xem danh sách tập huấn.',
  noEmployeeBanner:
    'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo lớp tập huấn.',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy lớp tập huấn.',
  },
  deleteTitle: 'Xóa lớp tập huấn?',
  deleteMessage: 'Toàn bộ dòng cán bộ tham gia lớp này cũng sẽ bị xóa.',
  bulkDeleteTitle: 'Xóa nhiều lớp tập huấn?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} lớp tập huấn và toàn bộ dòng cán bộ tham gia.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-tap-huan',
  toast: {
    create: 'Đã tạo lớp tập huấn.',
    update: 'Đã cập nhật lớp tập huấn.',
    delete: 'Đã xóa {{count}} lớp tập huấn.',
  },
  validation: {
    tenLopRequired: 'Nhập tên lớp tập huấn.',
    namRequired: 'Nhập năm tập huấn.',
    namInvalid: 'Năm tập huấn không hợp lệ (2000–2100).',
    capRequired: 'Chọn cấp tập huấn.',
    canBoRequired: 'Chọn cán bộ.',
    chucVuRequired: 'Nhập chức vụ.',
    donViCongTacRequired: 'Nhập đơn vị công tác.',
    thuocDienRequired: 'Chọn thuộc diện.',
    chiTietMin: 'Cần ít nhất một cán bộ tham gia lớp.',
  },
  store: {
    tenLopCol: 'Lớp tập huấn',
    namCol: 'Năm',
    capCol: 'Cấp',
    soDongCol: 'Số người',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Danh sách tập huấn',
  },
  searchPlaceholder: 'Tìm theo tên lớp, cấp, ghi chú…',
  emptyTitle: 'Chưa có lớp tập huấn',
  emptyHint: 'Thêm lớp tập huấn mới để bắt đầu.',
  form: {
    sectionHeader: 'Lớp tập huấn',
    sectionChiTiet: 'Cán bộ tham gia',
    tenLop: 'Tên lớp tập huấn',
    namTapHuan: 'Năm tập huấn',
    capTapHuan: 'Cấp tập huấn',
    ghiChu: 'Ghi chú',
    addLine: 'Thêm cán bộ',
    canBo: 'Cán bộ',
    hoVaTen: 'Họ và tên',
    chucVu: 'Chức vụ',
    donViCongTac: 'Đơn vị công tác',
    capQuanLy: 'Cấp quản lý',
    thuocDien: 'Thuộc diện',
    createSubtitle: 'Tạo lớp tập huấn mới',
    editSubtitle: 'Sửa lớp tập huấn',
    chiTietEmptyHint:
      'Chưa có cán bộ tham gia. Bấm nút Thêm cán bộ để thêm dòng.',
  },
  chiTietDrawer: {
    titleAdd: 'Thêm cán bộ tham gia',
    titleEdit: 'Sửa cán bộ tham gia',
    cannotDeleteLast: 'Cần ít nhất một cán bộ tham gia lớp — không thể xóa dòng cuối.',
    deleteLineTitle: 'Xóa dòng này?',
    deleteLineMessage:
      'Dòng sẽ bị xóa khỏi danh sách (chưa lưu DB cho đến khi bạn lưu lớp tập huấn).',
  },
  detail: {
    title: 'Chi tiết lớp tập huấn',
    sectionHeader: 'Thông tin lớp',
    sectionChiTiet: 'Cán bộ tham gia',
    emptyChiTiet: 'Chưa có cán bộ tham gia.',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
};
