import type { ThongTinToChucQuanTrong } from './core/types';

export const DTTG_THONG_TIN_TO_CHUC_QUAN_TRONG_MOCK: ThongTinToChucQuanTrong[] = [
  {
    id: '1',
    loai_hinh: 'Chùa',
    ten_co_so: 'Chùa Cần Linh',
    chu_tri: 'Hòa thượng Thích Thọ Lạc',
    lich_su_hinh_thanh: 'Ngôi chùa cổ có từ thời Lê, là di tích lịch sử quốc gia.',
    cong_tac_an_sinh: 'Phát quà từ thiện hàng tháng cho các hộ nghèo tại địa phương.',
    don_vi_id: null,
    ten_don_vi: 'Phường Thành Vinh',
    ten_tinh: null,
    dia_chi: 'TP. Vinh, Nghệ An',
    so_dien_thoai: '0238-384XXXX',
    trang_thai: 'Đang hoạt động',
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '2',
    loai_hinh: 'Giáo xứ',
    ten_co_so: 'Giáo xứ Cửa Nam',
    chu_tri: 'Linh mục Phêrô Nguyễn Văn Vinh',
    lich_su_hinh_thanh: 'Thành lập từ lâu đời, là trung tâm tôn giáo quan trọng của khu vực.',
    cong_tac_an_sinh: 'Khám chữa bệnh miễn phí và hỗ trợ người già neo đơn.',
    don_vi_id: null,
    ten_don_vi: 'Phường Thành Vinh',
    ten_tinh: null,
    dia_chi: 'TP. Vinh, Nghệ An',
    so_dien_thoai: '0238-383XXXX',
    trang_thai: 'Đang hoạt động',
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '3',
    loai_hinh: 'Nghĩa trang',
    ten_co_so: 'Nghĩa trang liệt sĩ Quốc tế Việt - Lào',
    chu_tri: 'UBND Xã',
    lich_su_hinh_thanh:
      'Được xây dựng từ những năm 1976 và chính thức nâng cấp, mở rộng vào năm 1982 trên diện tích gần 7 ha tại thị trấn Anh Sơn.',
    cong_tac_an_sinh: null,
    don_vi_id: null,
    ten_don_vi: 'Xã Anh Sơn',
    ten_tinh: null,
    dia_chi: null,
    so_dien_thoai: null,
    trang_thai: 'Đang hoạt động',
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '4',
    loai_hinh: 'Khác',
    ten_co_so: 'Đền Ông Hoàng Mười',
    chu_tri: null,
    lich_su_hinh_thanh: null,
    cong_tac_an_sinh: null,
    don_vi_id: null,
    ten_don_vi: null,
    ten_tinh: null,
    dia_chi: null,
    so_dien_thoai: null,
    trang_thai: 'Đang hoạt động',
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
];
