export const danTocToChucQuanTrong = {
  noViewPermission: 'Bạn không có quyền xem thông tin tổ chức tôn giáo.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  searchPlaceholder: 'Tìm theo tên cơ sở, chủ trì, xã phường, địa chỉ…',
  emptyTitle: 'Chưa có tổ chức tôn giáo',
  emptyHint: 'Thêm thông tin chùa, giáo xứ, nghĩa trang hoặc cơ sở tôn giáo.',
  emptyFilteredHint: 'Không có bản ghi phù hợp bộ lọc. Thử điều chỉnh tìm kiếm hoặc chip lọc.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'thong-tin-to-chuc-quan-trong',
  deleteTitle: 'Xóa tổ chức tôn giáo',
  deleteMessage: 'Bạn có chắc muốn xóa hồ sơ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều hồ sơ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} hồ sơ đã chọn? Hành động không hoàn tác.',
  statusChangeTitle: 'Đổi trạng thái hoạt động',
  statusChangeMessage: 'Chuyển trạng thái «{{name}}» sang «{{status}}»?',
  service: {
    notFound: 'Không tìm thấy hồ sơ tổ chức tôn giáo',
    noEmployeeProfile: 'Không xác định được hồ sơ nhân viên. Vui lòng đăng nhập lại.',
  },
  toast: {
    create: 'Đã thêm tổ chức tôn giáo',
    update: 'Đã cập nhật hồ sơ',
    delete: 'Đã xóa {{count}} hồ sơ',
    importSuccess: 'Đã nhập {{count}} tổ chức tôn giáo',
  },
  import: {
    templateName: 'to-chuc-quan-trong',
    rowError: 'Dòng {{row}}: {{message}}',
  },
  validation: {
    tenCoSoRequired: 'Vui lòng nhập tên cơ sở',
    loaiHinhInvalid: 'Loại hình không hợp lệ',
    trangThaiInvalid: 'Trạng thái không hợp lệ',
    donViInvalid: 'Xã/phường không hợp lệ',
  },
  store: {
    loaiHinhCol: 'Loại hình',
    tenCoSoCol: 'Tên cơ sở',
    chuTriCol: 'Chủ trì',
    donViCol: 'Xã, Phường',
    diaChiCol: 'Địa chỉ liên lạc',
    soDienThoaiCol: 'Số điện thoại',
    trangThaiCol: 'Trạng thái',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm tổ chức tôn giáo',
    editSubtitle: 'Cập nhật hồ sơ',
    sectionMain: 'Thông tin chính',
    sectionHistory: 'Lịch sử & an sinh',
    sectionContact: 'Liên hệ & địa chỉ',
    loaiHinh: 'Loại hình',
    tenCoSo: 'Tên cơ sở tôn giáo',
    chuTri: 'Chủ trì cơ sở tôn giáo',
    lichSuHinhThanh: 'Lịch sử hình thành',
    congTacAnSinh: 'Công tác an sinh xã hội',
    donVi: 'Xã, Phường',
    donViHint: 'Chọn xã/phường từ danh mục địa bàn hệ thống.',
    diaChi: 'Địa chỉ liên lạc',
    soDienThoai: 'Số điện thoại',
    trangThai: 'Trạng thái hoạt động',
  },
  detail: {
    title: 'Chi tiết tổ chức tôn giáo',
    sectionMain: 'Thông tin chính',
    sectionHistory: 'Lịch sử & an sinh',
    sectionContact: 'Liên hệ & địa chỉ',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    nguoiTao: 'Người tạo',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
    sectionThamHoi: 'Lịch sử thăm hỏi',
    noThamHoi: 'Chưa có lượt thăm hỏi nào',
    noThamHoiHint: 'Thêm lượt thăm hỏi tại module Thăm hỏi tổ chức.',
    viewAllThamHoi: 'Xem tất cả',
  },
} as const;
