import type { ThamHoiToChuc } from './core/types';

export const DTTG_THAM_HOI_TO_CHUC_MOCK: ThamHoiToChuc[] = [
  {
    id: '1',
    to_chuc_id: '1',
    ten_co_so: 'Chùa Cần Linh',
    loai_hinh: 'Chùa',
    dip_tham_hoi_id: '1',
    dip_tham_hoi: 'Đại lễ Phật đản',
    ten_dip_tham_hoi: 'Đại lễ Phật đản',
    thoi_gian_du_kien: 'Tháng 5/2026',
    thoi_gian_thuc_te: null,
    don_vi_tham_hoi_id: '101',
    ten_don_vi_tham_hoi: 'Phường Thành Vinh',
    phong_ban_tham_muu_id: '1',
    ten_phong_ban: 'Ban Dân tộc, Tôn giáo và Hội quần chúng',
    noi_dung_tham_hoi: 'Chúc mừng Ban trị sự, tăng ni, Phật tử',
    thanh_phan_doan: 'Lãnh đạo MTTQ tỉnh, Ban Tôn giáo',
    qua_tang: 'Lẵng hoa và quà tặng',
    tien_do: 'Chưa thực hiện',
    ket_qua_thuc_hien: null,
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '2',
    to_chuc_id: '3',
    ten_co_so: 'Chùa Đại Tuệ',
    loai_hinh: 'Chùa',
    dip_tham_hoi_id: '2',
    dip_tham_hoi: 'Tết Nguyên Đán',
    ten_dip_tham_hoi: 'Tết Nguyên Đán',
    thoi_gian_du_kien: 'Tháng 1/2026',
    thoi_gian_thuc_te: '2026-01-28',
    don_vi_tham_hoi_id: '303',
    ten_don_vi_tham_hoi: 'Xã Đại Huệ',
    phong_ban_tham_muu_id: null,
    ten_phong_ban: null,
    noi_dung_tham_hoi: 'Thăm hỏi, chúc Tết',
    thanh_phan_doan: 'Thường trực MTTQ huyện Nam Đàn',
    qua_tang: 'Quà Tết',
    tien_do: 'Đã hoàn thành',
    ket_qua_thuc_hien: 'Diễn ra trang trọng',
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-02T00:00:00.000Z',
    tg_cap_nhat: '2026-02-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
  {
    id: '3',
    to_chuc_id: '4',
    ten_co_so: 'Tòa Giám mục Xã Đoài',
    loai_hinh: 'Giáo xứ',
    dip_tham_hoi_id: '1',
    dip_tham_hoi: 'Lễ bổn mạng của Giám mục',
    ten_dip_tham_hoi: 'Lễ bổn mạng của Giám mục',
    thoi_gian_du_kien: 'Tháng 8/2026',
    thoi_gian_thuc_te: null,
    don_vi_tham_hoi_id: null,
    ten_don_vi_tham_hoi: null,
    phong_ban_tham_muu_id: '1',
    ten_phong_ban: 'Ban Dân tộc, Tôn giáo và Hội quần chúng',
    noi_dung_tham_hoi: 'Thăm hỏi cá nhân Đức Giám mục',
    thanh_phan_doan: 'Ban Thường trực MTTQ tỉnh',
    qua_tang: 'Lẵng hoa chúc mừng',
    tien_do: 'Đang thực hiện',
    ket_qua_thuc_hien: null,
    link_ket_qua: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-03T00:00:00.000Z',
    tg_cap_nhat: '2026-01-03T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock',
  },
];
