export const danTocThamHoiToChuc = {
  noViewPermission: 'Bạn không có quyền xem thăm hỏi tổ chức.',
  noViewRowPermission: 'Bạn không có quyền xem lượt thăm hỏi này.',
  noEditOtherDonVi: 'Bạn chỉ được sửa bản ghi thuộc đơn vị của mình.',
  noDeleteOtherDonVi: 'Bạn chỉ được xóa bản ghi thuộc đơn vị của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  searchPlaceholder: 'Tìm theo tên cơ sở, dịp thăm hỏi, đơn vị thăm hỏi, nội dung…',
  emptyTitle: 'Chưa có lượt thăm hỏi',
  emptyHint: 'Thêm kế hoạch hoặc ghi nhận lượt thăm hỏi tổ chức dân tộc, tôn giáo.',
  emptyFilteredHint: 'Không có bản ghi phù hợp bộ lọc. Thử điều chỉnh tìm kiếm hoặc chip lọc.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'tham-hoi-to-chuc',
  deleteTitle: 'Xóa lượt thăm hỏi',
  deleteMessage: 'Bạn có chắc muốn xóa lượt thăm hỏi này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều lượt thăm hỏi',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} lượt thăm hỏi đã chọn? Hành động không hoàn tác.',
  service: {
    notFound: 'Không tìm thấy lượt thăm hỏi',
    noEmployeeProfile: 'Không xác định được hồ sơ nhân viên. Vui lòng đăng nhập lại.',
  },
  toast: {
    create: 'Đã thêm lượt thăm hỏi',
    update: 'Đã cập nhật lượt thăm hỏi',
    delete: 'Đã xóa {{count}} lượt thăm hỏi',
    importSuccess: 'Đã nhập {{count}} lượt thăm hỏi',
    changeStatus: 'Đã cập nhật trạng thái',
  },
  import: {
    templateName: 'tham-hoi-to-chuc',
    rowError: 'Dòng {{row}}: {{message}}',
  },
  validation: {
    toChucRequired: 'Vui lòng chọn cơ sở tôn giáo',
    toChucInvalid: 'Tên cơ sở tôn giáo không hợp lệ',
    dipThamHoiRequired: 'Vui lòng chọn dịp thăm hỏi',
    dipThamHoiInvalid: 'Dịp thăm hỏi không hợp lệ',
    tienDoInvalid: 'Tiến độ thực hiện không hợp lệ',
    linkUrl: 'Link kết quả phải là URL hợp lệ',
    donViThamHoiInvalid: 'Đơn vị thăm hỏi không hợp lệ',
  },
  store: {
    tenCoSoCol: 'Tên cơ sở tôn giáo',
    dipThamHoiCol: 'Dịp thăm hỏi',
    thoiGianDuKienCol: 'Thời gian dự kiến',
    donViThamHoiCol: 'Đơn vị thăm hỏi',
    donViThamHoiTinhCap: 'MTTQ Tỉnh',
    noiDungCol: 'Nội dung thăm hỏi',
    thanhPhanDoanCol: 'Thành phần đoàn',
    quaTangCol: 'Quà tặng',
    tienDoCol: 'Tiến độ thực hiện',
    ketQuaCol: 'Kết quả thực hiện',
    linkKetQuaCol: 'Link kết quả',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm lượt thăm hỏi tổ chức',
    editSubtitle: 'Cập nhật lượt thăm hỏi',
    sectionMain: 'Thông tin chính',
    sectionContent: 'Nội dung thăm hỏi',
    sectionResult: 'Kết quả thực hiện',
    toChuc: 'Cơ sở tôn giáo',
    toChucPlaceholder: 'Chọn cơ sở từ danh mục tổ chức tôn giáo',
    dipThamHoi: 'Dịp thăm hỏi',
    dipThamHoiPlaceholder: 'Chọn dịp thăm hỏi',
    thoiGianDuKien: 'Thời gian dự kiến',
    thoiGianThucTe: 'Thời gian thực tế',
    phongBanThamMuu: 'Phòng ban tham mưu',
    phongBanPlaceholder: 'Chọn phòng ban',
    thoiGianDuKienHint: 'VD: Tháng 5/2026',
    donViThamHoi: 'Đơn vị thăm hỏi',
    donViThamHoiPlaceholder: 'Chọn đơn vị thăm hỏi',
    noiDungThamHoi: 'Nội dung thăm hỏi',
    thanhPhanDoan: 'Thành phần đoàn',
    quaTang: 'Quà tặng',
    tienDo: 'Tiến độ thực hiện',
    ketQuaThucHien: 'Kết quả thực hiện',
    linkKetQua: 'Link kết quả',
  },
  detail: {
    title: 'Chi tiết lượt thăm hỏi',
    sectionMain: 'Thông tin chính',
    sectionContent: 'Nội dung thăm hỏi',
    sectionResult: 'Kết quả thực hiện',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    nguoiTao: 'Người tạo',
    openLink: 'Mở link kết quả',
    actionChangeStatus: 'Chuyển trạng thái',
    changeStatusTitle: 'Chuyển trạng thái thăm hỏi',
    changeStatusHint: 'Chọn tiến độ thực hiện mới',
  },
} as const;
