export const matTranDotCuuTro = {
  noViewPermission: 'Bạn không có quyền xem danh sách đợt cứu trợ.',
  deleteTitle: 'Xóa đợt cứu trợ?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều bản ghi?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'dot-cuu-tro',
  toast: {
    create: 'Đã tạo bản ghi.',
    update: 'Đã cập nhật bản ghi.',
    delete: 'Đã xóa {{count}} bản ghi.',
  },
  service: {
    notFound: 'Không tìm thấy bản ghi.',
  },
  validation: {
    tenRequired: 'Nhập tên đợt cứu trợ.',
    linkInvalid: 'Liên kết không hợp lệ (cần URL đầy đủ, VD https://…).',
  },
  store: {
    ttCol: 'TT',
    tenCol: 'Tên đợt',
    linkCol: 'Liên kết',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  searchPlaceholder: 'Tìm theo tên, liên kết…',
  emptyTitle: 'Chưa có đợt cứu trợ',
  emptyHint: 'Thêm đợt tổ chức (VD: Bão Yagi 2026) kèm mô tả và liên kết tham khảo.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionMain: 'Thông tin',
    ten: 'Tên đợt',
    moTa: 'Mô tả',
    link: 'Liên kết (URL)',
    createSubtitle: 'Thêm đợt cứu trợ',
    editSubtitle: 'Sửa thông tin',
  },
  detail: {
    title: 'Chi tiết đợt cứu trợ',
    sectionMain: 'Thông tin',
    moTa: 'Mô tả',
    linkOpen: 'Mở liên kết',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
};
