export const matTranDotCuuTro = {
  noViewPermission: 'Bạn không có quyền xem danh sách chương trình vận động.',
  deleteTitle: 'Xóa chương trình vận động?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều bản ghi?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'chuong-trinh-van-dong',
  toast: {
    create: 'Đã tạo bản ghi.',
    update: 'Đã cập nhật bản ghi.',
    delete: 'Đã xóa {{count}} bản ghi.',
  },
  service: {
    notFound: 'Không tìm thấy bản ghi.',
  },
  validation: {
    tenRequired: 'Nhập tên chương trình vận động.',
    loaiInvalid: 'Chọn loại chương trình.',
    donViChuTriRequired: 'Chọn đơn vị chủ trì.',
    trangThaiInvalid: 'Chọn trạng thái.',
    ngayInvalid: 'Ngày không hợp lệ.',
    denNgayTruocTuNgay: 'Ngày kết thúc phải sau ngày bắt đầu.',
    linkInvalid: 'Liên kết không hợp lệ (cần URL đầy đủ, VD https://…).',
  },
  store: {
    ttCol: 'TT',
    tenCol: 'Tên chương trình',
    linkCol: 'Văn bản phát động',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
    loaiCol: 'Loại',
    donViChuTriCol: 'Đơn vị chủ trì',
    thoiGianCol: 'Thời gian',
    taiKhoanCol: 'Tài khoản tiếp nhận',
    nganHangCol: 'Ngân hàng',
    trangThaiCol: 'Trạng thái',
    tienDoCol: 'Tiến độ',
  },
  thoiGianTuDen: '{{tu}} – {{den}}',
  thoiGianTu: 'Từ {{tu}}',
  thoiGianDen: 'Đến {{den}}',
  filterLoaiPlaceholder: 'Loại',
  filterTrangThaiPlaceholder: 'Trạng thái',
  filterLinkHas: 'Có văn bản',
  filterLinkEmpty: 'Chưa có văn bản',
  filterLinkChipPlaceholder: 'Văn bản phát động',
  emptyTitle: 'Chưa có chương trình vận động',
  emptyHint: 'Thêm chương trình (VD: Ủng hộ đồng bào bão số 3 năm 2026) kèm thời gian, tài khoản tiếp nhận và văn bản phát động.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionMain: 'Thông tin',
    sectionTiepNhan: 'Tiếp nhận ủng hộ',
    sectionTienDo: 'Trạng thái & tiến độ',
    ten: 'Tên chương trình',
    loai: 'Loại',
    donViChuTri: 'Đơn vị chủ trì',
    donViChuTriHint: 'Chương trình của xã nào chỉ cán bộ xã đó và cấp tỉnh thấy.',
    tuNgay: 'Từ ngày',
    denNgay: 'Đến ngày',
    taiKhoan: 'Tài khoản tiếp nhận',
    nganHang: 'Ngân hàng',
    trangThai: 'Trạng thái',
    tienDo: 'Tiến độ',
    tienDoPlaceholder: 'VD: Đã tiếp nhận 120 triệu, đang phân bổ cho 3 xã…',
    moTa: 'Mô tả',
    link: 'Văn bản phát động (URL)',
    createSubtitle: 'Thêm chương trình vận động',
    editSubtitle: 'Sửa thông tin',
  },
  detail: {
    title: 'Chi tiết chương trình vận động',
    sectionMain: 'Thông tin',
    sectionTiepNhan: 'Tiếp nhận ủng hộ',
    sectionTienDo: 'Trạng thái & tiến độ',
    ngayCapNhatTrangThai: 'Ngày cập nhật trạng thái',
    moTa: 'Mô tả',
    linkOpen: 'Mở văn bản phát động',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
};
