/** Thống kê tổ chức, cá nhân */
export const dttgThongKeToChucCaNhan = {
  title: 'Thống kê tổ chức, cá nhân',
  noViewPermission: 'Bạn không có quyền xem thống kê tổ chức, cá nhân.',
  noViewRowPermission: 'Bạn không có quyền xem hồ sơ này.',
  noDetailPermission: 'Bạn không có quyền xem chi tiết hồ sơ này.',
  loading: 'Đang tải thống kê…',
  noData: 'Không có dữ liệu trong khoảng và bộ lọc đã chọn.',
  noDataHint: 'Thử đổi khoảng thời gian hoặc bỏ bớt bộ lọc.',
  noExportData: 'Không có dữ liệu để xuất',
  dateRangeLabel: 'Khoảng thời gian (ngày tạo)',
  exportFileName: 'Thong_Ke_To_Chuc_Ca_Nhan',
  stats: {
    exportReport: 'Xuất báo cáo',
    exportSuccess: 'Đã xuất báo cáo',
    exportSuccessDesc: 'File Excel đã được tải về.',
    exportError: 'Không thể xuất báo cáo',
    clearFilters: 'Xóa bộ lọc',
    filterLoai: 'Loại hồ sơ',
    filterLoaiToChuc: 'Tổ chức',
    filterLoaiCaNhan: 'Cá nhân',
    filterTrangThai: 'Trạng thái',
    filterLoaiHinh: 'Loại hình',
    filterDoiTuong: 'Đối tượng',
    filterDonVi: 'Đơn vị',
    kpiTotal: 'Tổng hồ sơ',
    kpiToChuc: 'Tổ chức',
    kpiCaNhan: 'Cá nhân',
    kpiDangHoatDong: 'Đang hoạt động',
    kpiNgungHoatDong: 'Ngừng hoạt động',
    chartTrend: 'Xu hướng bổ sung hồ sơ',
    chartTrangThai: 'Theo trạng thái',
    chartLoai: 'Theo loại hồ sơ',
    chartLoaiHinh: 'Theo loại hình (tổ chức)',
    chartDoiTuong: 'Theo đối tượng (cá nhân)',
    chartDonVi: 'Theo đơn vị',
    tableLookupTitle: 'Tra cứu',
    tableColLoai: 'Loại',
    tableColTen: 'Tên',
    tableColPhanLoai: 'Phân loại',
    tableColDonVi: 'Đơn vị',
    tableColTrangThai: 'Trạng thái',
    tableColTgTao: 'Ngày tạo',
    tableColToChuc: 'Tổ chức',
    tableColCaNhan: 'Cá nhân',
    tableColTotal: 'Tổng',
    tableTwoColLabel: 'Nhóm',
    tableTwoColValue: 'Số lượng',
  },
  report: {
    indicator: 'Chỉ tiêu',
    value: 'Giá trị',
    period: 'Kỳ báo cáo',
    allTime: 'Tất cả',
    exportDate: 'Ngày xuất',
    overviewSheet: 'Tổng quan',
    byDonViSheet: 'Theo đơn vị',
    byLoaiHinhSheet: 'Theo loại hình',
    byDoiTuongSheet: 'Theo đối tượng',
    byTrangThaiSheet: 'Theo trạng thái',
    detailSheet: 'Chi tiết',
  },
} as const;
