export const matTranTangLuong = {
  noViewPermission: 'Bạn không có quyền xem danh sách tăng lương.',
  noCreatePermission: 'Bạn không có quyền thêm bản ghi tăng lương.',
  noEditPermission: 'Bạn không có quyền sửa bản ghi tăng lương.',
  noDeletePermission: 'Bạn không có quyền xóa bản ghi tăng lương.',
  listLoadErrorHint: 'Không tải được danh sách tăng lương.',
  emptyTitle: 'Chưa có bản ghi tăng lương',
  emptyHint: 'Thêm bản ghi để theo dõi kỳ nâng lương và lập kế hoạch năm.',
  emptyFilteredHint: 'Thử đổi bộ lọc hoặc xóa tìm kiếm.',
  tabs: {
    lichSu: 'Lịch sử',
    keHoach: 'Kế hoạch năm',
    thongKe: 'Thống kê',
  },
  loaiKy: {
    dungHan: 'Đúng hạn',
    truocHan6: 'Trước hạn 6 tháng',
    truocHan9: 'Trước hạn 9 tháng',
    truocHan12: 'Trước hạn 12 tháng',
  },
  store: {
    ngayNangCol: 'Ngày nâng lương',
    canBoCol: 'Cán bộ',
    loaiKyCol: 'Loại kỳ',
    ngachMoiCol: 'Ngạch · Bậc mới',
    luongCol: 'Lương',
    ngachCuCol: 'Ngạch · Bậc cũ',
    ghiChuCol: 'Ghi chú',
  },
  form: {
    sectionMain: 'Thông tin tăng lương',
    createSubtitle: 'Ghi nhận tăng lương',
    editSubtitle: 'Cập nhật tăng lương',
    canBo: 'Cán bộ',
    ngayNang: 'Ngày nâng lương',
    loaiKy: 'Loại kỳ',
    ngachCu: 'Ngạch cũ',
    bacCu: 'Bậc cũ',
    ngachMoi: 'Ngạch mới',
    bacMoi: 'Bậc mới',
    luong: 'Lương (snapshot)',
    luongHint: 'Tự điền theo MLCS × hệ số bậc mới; có thể sửa trước khi lưu.',
    luongPreviewEmpty: 'Chọn bậc mới để tự điền lương.',
    ngayDenHanGoc: 'Ngày đến hạn gốc',
    ngayDenHanGocHint: 'Tính từ ngày nâng lương lần trước + 3 năm.',
    ghiChu: 'Ghi chú',
    fileQuyetDinh: 'File quyết định (URL)',
    fileQuyetDinhHint: 'Dán link hoặc đường dẫn file quyết định.',
  },
  detail: {
    title: 'Chi tiết tăng lương',
    systemInfo: 'Hệ thống',
  },
  keHoach: {
    yearLabel: 'Năm',
    groupQuarter: 'Theo quý',
    groupMonth: 'Theo tháng',
    quarterLabel: 'Quý {{quarter}}/{{year}}',
    monthLabel: 'Tháng {{month}}/{{year}}',
    nextDueCol: 'Ngày đến hạn',
    lastRaiseCol: 'Lần nâng gần nhất',
    ngachBacCol: 'Ngạch · Bậc hiện tại',
    recordAction: 'Ghi nhận',
    emptyTitle: 'Không có cán bộ đến hạn trong năm này',
    emptyHint: 'Chỉ hiển thị cán bộ đã có ít nhất một bản ghi lịch sử tăng lương.',
    warnD30: '≤ 30 ngày',
    warnD60: '≤ 60 ngày',
    warnD90: '≤ 90 ngày',
    missingHistoryKpi: '{{count}} cán bộ chưa có lịch sử (không tính vào kế hoạch)',
  },
  stats: {
    loading: 'Đang tải thống kê…',
    noData: 'Chưa có dữ liệu thống kê',
    noDataHint: 'Thêm bản ghi lịch sử hoặc đổi bộ lọc năm.',
    kpiTotalRecords: 'Tổng bản ghi',
    kpiTotalCanBo: 'Cán bộ có lịch sử',
    kpiDungHan: 'Đúng hạn',
    kpiTruocHan: 'Trước hạn',
    kpiDueInYear: 'Đến hạn trong năm',
    kpiDoneInYear: 'Đã nâng trong năm',
    chartLoaiKy: 'Theo loại kỳ',
    chartMonth: 'Theo tháng',
    chartPhongBan: 'Theo phòng ban',
    chartNgach: 'Theo ngạch mới',
    chartPlanVsDone: 'Kế hoạch vs thực hiện',
    planDue: 'Đến hạn',
    planDone: 'Đã nâng',
    planPending: 'Chưa nâng',
    yearFilter: 'Năm thống kê',
    noExportData: 'Chưa có dữ liệu để xuất.',
    exportFileName: 'TangLuong_ThongKe',
  },
  validation: {
    canBoRequired: 'Chọn cán bộ.',
    ngayNangRequired: 'Nhập ngày nâng lương.',
    ngachMoiRequired: 'Chọn ngạch mới.',
    bacMoiRequired: 'Chọn bậc mới.',
    luongRequired: 'Nhập lương.',
    bacNotInNgach: 'Bậc không thuộc ngạch đã chọn.',
    luongZero: 'Lương phải lớn hơn 0.',
    canBoNotInDonVi: 'Cán bộ không thuộc đơn vị của bạn.',
    ngayTruocHanAfterDue: 'Ngày nâng trước hạn phải không muộn hơn ngày đến hạn gốc.',
    consecutiveEarlyWarning:
      'Cảnh báo: hai lần trước hạn liên tiếp. Quy định khuyến nghị có ít nhất một lần đúng hạn ở giữa. Vẫn lưu?',
  },
  service: {
    notFound: 'Không tìm thấy bản ghi tăng lương.',
    noEmployeeProfile: 'Tài khoản chưa liên kết hồ sơ nhân viên.',
  },
  toast: {
    create: 'Đã ghi nhận tăng lương.',
    update: 'Đã cập nhật tăng lương.',
    delete: 'Đã xóa bản ghi tăng lương.',
    deleteMany: 'Đã xóa {{count}} bản ghi.',
  },
  deleteTitle: 'Xóa bản ghi tăng lương?',
  deleteMessage: 'Bản ghi tăng lương ngày {{ngay}} sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều bản ghi?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi tăng lương.',
  searchPlaceholder: 'Tìm cán bộ, ngạch, bậc, lương, ghi chú…',
  filterLoaiKy: 'Loại kỳ',
  filterPhongBan: 'Phòng ban',
  filterDonVi: 'Đơn vị (xã/phường)',
  filterToChuc: 'Tổ chức',
};
