export const khenThuongNhaTaiTro = {
  tabs: {
    danhSach: 'Danh sách',
    thongKe: 'Thống kê',
  },
  noViewPermission: 'Bạn không có quyền xem module Khen thưởng nhà tài trợ.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập quyết định khen cấp xã của xã/phường mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có quyết định khen thưởng nào',
  exportFileName: 'Khen_Thuong_Nha_Tai_Tro',
  deleteTitle: 'Xóa quyết định khen',
  deleteMessage: 'Bạn có chắc muốn xóa quyết định khen này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều quyết định khen',
  bulkDeleteMessage:
    'Bạn có chắc muốn xóa {{count}} quyết định khen đã chọn? Hành động không hoàn tác.',
  detailTitle: 'Chi tiết khen thưởng nhà tài trợ',
  detail: {
    systemInfo: 'Thông tin hệ thống',
    actionChangeStatus: 'Chuyển trạng thái',
    sectionThanhTich: 'Thành tích hỗ trợ',
    thanhTichHint:
      'Tự tính trong kỳ thành tích: tiền mặt và hiện vật quy đổi từ Chương trình hỗ trợ, cộng giá trị hàng các phiếu nhập kho từ nhà tài trợ này.',
    thanhTichEmpty: 'Chưa có khoản hỗ trợ nào của nhà tài trợ này trong kỳ',
    openVnn: 'Mở Chương trình hỗ trợ',
    kySuffix: 'khoản',
    phieuSuffix: 'phiếu',
    kyTatCa: 'Mọi năm',
  },
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái quyết định khen và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
    noApproveHint:
      'Bạn không có quyền Duyệt nên không chọn được "Đã duyệt" / "Không duyệt".',
  },
  store: {
    ngayKhenCol: 'Ngày khen',
    noiDungCol: 'Nội dung khen',
    soQuyetDinhCol: 'Số quyết định',
    capKhenCol: 'Cấp khen',
    donViKhenCol: 'Đơn vị khen',
    xaPhuongCol: 'Xã phường',
    nhaTaiTroCol: 'Nhà tài trợ',
    loaiNhaTaiTroCol: 'Loại nhà tài trợ',
    kyThanhTichCol: 'Kỳ thành tích',
    namTuCol: 'Từ năm',
    namDenCol: 'Đến năm',
    soKhoanCol: 'Số khoản hỗ trợ',
    soNguoiCol: 'Số người được hỗ trợ',
    tongTienHoTroCol: 'Tiền mặt (CT hỗ trợ)',
    hienVatQuyDoiCol: 'Hiện vật quy đổi (CT hỗ trợ)',
    giaTriNhapKhoCol: 'Hàng nhập kho',
    giaTriKhacCol: 'Đóng góp khác',
    tongGiaTriCol: 'Tổng giá trị đóng góp',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Ngày cập nhật trạng thái',
    nguoiDuyetCol: 'Người duyệt',
    tgDuyetCol: 'Thời gian duyệt',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
    nguoiNhanCol: 'Người được hỗ trợ',
    namCol: 'Năm',
    linhVucCol: 'Lĩnh vực',
    soTienCol: 'Số tiền',
  },
  form: {
    createSubtitle: 'Thêm quyết định khen nhà tài trợ',
    editSubtitle: 'Cập nhật quyết định khen',
    sectionKhen: 'Nội dung khen',
    sectionNhaTaiTro: 'Nhà tài trợ & thành tích',
    sectionTrangThai: 'Trạng thái',
    donViKhenPlaceholder: 'Ví dụ: Ủy ban MTTQ Việt Nam tỉnh Nghệ An',
    nhaTaiTroPlaceholder: 'Chọn từ danh mục Đơn vị cứu trợ',
    kyHint: 'Chỉ khoản hỗ trợ / phiếu nhập kho có năm trong kỳ này được tính vào thành tích. Để trống = không giới hạn.',
    giaTriKhacHint:
      'Chỉ nhập phần CHƯA ghi ở Chương trình hỗ trợ hay Nhập kho (công trình, ủng hộ quỹ…) — phần đã ghi được tự cộng.',
    tuTinhTitle: 'Tự tính từ dữ liệu đã ghi',
    tuTinhChonNhaTaiTro: 'Chọn nhà tài trợ để xem số tự tính.',
    tuTinhNamKhongHopLe: 'Kỳ năm chưa hợp lệ — sửa lại để xem số tự tính.',
    tuTinhLoi: 'Không tải được số tự tính.',
    tuTinhTong: 'Tổng (gồm đóng góp khác)',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
  },
  toast: {
    create: 'Đã thêm quyết định khen',
    update: 'Đã cập nhật quyết định khen',
    delete: 'Đã xóa {{count}} quyết định khen',
    statusChange: 'Đã chuyển trạng thái quyết định khen',
  },
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập.',
  },
  validation: {
    noiDungRequired: 'Nhập nội dung khen',
    ngayKhenRequired: 'Chọn ngày khen',
    capKhenInvalid: 'Chọn cấp khen hợp lệ',
    xaPhuongRequired: 'Khen cấp xã phải chọn xã phường',
    nhaTaiTroRequired: 'Chọn nhà tài trợ',
    namInvalid: 'Năm phải từ 2000 đến 2100',
    kyInvalid: '"Đến năm" không được nhỏ hơn "Từ năm"',
    tienInvalid: 'Số tiền không hợp lệ',
    tienMin: 'Số tiền không được âm',
    trangThaiInvalid: 'Chọn trạng thái hợp lệ',
  },
};
