/** Danh mục tỉnh thành – xã phường (2 tab, 2 bảng) */
export const diaBan = {
  title: 'Danh mục tỉnh thành – xã phường',
  description: 'Quản lý tỉnh/thành và xã/phường trực thuộc.',
  tabTinh: 'Tỉnh thành',
  tabXa: 'Xã phường',
  backToSystem: 'Quay lại Hệ thống',
  colId: 'ID',
  colTen: 'Tên',
  colThuTu: 'Thứ tự',
  colTgTao: 'Ngày tạo',
  colTgCapNhat: 'Cập nhật',
  colIdTinhThanh: 'ID tỉnh/thành',
  filterTinh: 'Tỉnh/thành',
  /** Chip filter tab xã: khi chưa chọn tỉnh (xem tất cả). */
  filterTinhChipPlaceholder: 'Tất cả tỉnh/thành',
  filterTinhHint: 'Để trống bộ lọc để xem mọi xã/phường; chọn một tỉnh để thu hẹp danh sách.',
  /** Chip tab tỉnh: lọc theo số xã đã gắn. */
  filterSoXaChipPlaceholder: 'Số xã/phường',
  filterSoXaGroup: 'Số xã/phường',
  filterSoXaHas: 'Đã có xã/phường',
  filterSoXaNone: 'Chưa có xã/phường',
  emptyTinh: 'Chưa có dữ liệu tỉnh/thành.',
  emptyXa: 'Chưa có xã/phường.',
  loading: 'Đang tải…',
  noExportData: 'Không có dữ liệu để xuất',
  bulkDeleteTinhTitle: 'Xóa nhiều tỉnh/thành',
  bulkDeleteTinhMessage: 'Bạn có chắc muốn xóa {{count}} tỉnh/thành? Toàn bộ xã/phường trực thuộc cũng sẽ bị xóa.',
  bulkDeleteXaTitle: 'Xóa nhiều xã/phường',
  bulkDeleteXaMessage: 'Bạn có chắc muốn xóa {{count}} xã/phường?',
  deleteTinhTitle: 'Xóa tỉnh/thành',
  deleteTinhMessage: 'Xóa tỉnh/thành này? Mọi xã/phường trực thuộc sẽ bị xóa theo.',
  deleteXaTitle: 'Xóa xã/phường',
  deleteXaMessage: 'Xóa xã/phường này?',
  store: {
    orderCol: 'Thứ tự',
    nameCol: 'Tên',
    soXaPhuongCol: 'Số xã/phường',
    createdCol: 'Ngày tạo',
    updatedCol: 'Cập nhật',
  },
  detail: {
    tinhTitle: 'Chi tiết tỉnh/thành',
    tinhSubtitle: 'Danh mục địa bàn',
    xaTitle: 'Chi tiết xã/phường',
    xaSubtitle: 'Danh mục địa bàn',
    basicInfo: 'Thông tin cơ bản',
    systemInfo: 'Thông tin hệ thống',
    wardsSection: 'Xã phường trực thuộc',
    addWard: 'Thêm xã/phường',
    noWards: 'Chưa có xã/phường',
    noWardsHint: 'Thêm xã/phường để hoàn thiện danh mục.',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    parentTinh: 'Thuộc tỉnh/thành',
  },
  form: {
    tinhCreateTitle: 'Thêm tỉnh/thành',
    tinhEditTitle: 'Sửa tỉnh/thành',
    xaCreateTitle: 'Thêm xã/phường',
    xaEditTitle: 'Sửa xã/phường',
    ten: 'Tên',
    tenPlaceholderTinh: 'Ví dụ: An Giang',
    tenPlaceholderXa: 'Ví dụ: Phường Long Xuyên',
    thuTu: 'Thứ tự hiển thị',
    tinhSelect: 'Tỉnh/thành',
    tinhSelectHint: 'Chọn tỉnh/thành chứa xã/phường này.',
  },
  toast: {
    createTinhSuccess: 'Đã tạo tỉnh/thành',
    updateTinhSuccess: 'Đã cập nhật tỉnh/thành',
    deleteTinhSuccess: 'Đã xóa {{count}} tỉnh/thành',
    createXaSuccess: 'Đã tạo xã/phường',
    updateXaSuccess: 'Đã cập nhật xã/phường',
    deleteXaSuccess: 'Đã xóa {{count}} xã/phường',
    importSuccess: 'Đã import {{count}} dòng thành công',
  },
  import: {
    templateTinh: 'Mau_Import_Tinh_Thanh',
    templateXa: 'Mau_Import_Xa_Phuong',
    colTenTinh: 'ten (tên tỉnh/thành)',
    colThuTuTinh: 'thu_tu (số, tùy chọn)',
    colTenXa: 'ten (tên xã/phường)',
    colThuTuXa: 'thu_tu (số, tùy chọn)',
    colTinhXa: 'id_tinh_thanh hoặc ten_tinh',
    rowEmptyTenTinh: 'Dòng {{row}}: Thiếu cột ten (tên tỉnh/thành).',
    rowInvalidTinh: 'Dòng {{row}}: Không hợp lệ — {{detail}}',
    rowDupTenTinh: 'Dòng {{row}}: Trùng tên "{{ten}}" (đã có hoặc trùng trong file).',
    rowEmptyTenXa: 'Dòng {{row}}: Thiếu cột ten (tên xã/phường).',
    rowMissingTinhXa: 'Dòng {{row}}: Cần id_tinh_thanh đúng ID hoặc ten_tinh khớp danh mục tỉnh.',
    rowInvalidXa: 'Dòng {{row}}: Không hợp lệ — {{detail}}',
    rowError: 'Dòng {{row}}: {{detail}}',
    needTinhCatalog: 'Chưa có tỉnh/thành trong danh mục — hãy thêm hoặc import tỉnh trước khi import xã/phường.',
  },
  validation: {
    tenMin: 'Tên quá ngắn',
    tenMax: 'Tên quá dài',
    tinhRequired: 'Vui lòng chọn tỉnh/thành',
  },
} as const;
