/**
 * Chuỗi giao diện của bốn màn hình quỹ tiền (dùng chung cho Quỹ vì người nghèo
 * và Quỹ cứu trợ). Tên quỹ được ghép vào lúc chạy từ `QUY_LABEL`.
 */
export const quy = {
  common: {
    backToParent: 'Quay lại An sinh xã hội',
    tongThu: 'Tổng thu',
    tongChi: 'Tổng chi',
    soDu: 'Số dư',
    soDuTheoTaiKhoan: 'Số dư theo tài khoản',
    soDuChuaCo: 'Chưa có tài khoản nào trong danh mục.',
    loaiThu: 'Phiếu thu',
    loaiChi: 'Phiếu chi',
    khoanThu: 'Khoản thu',
    khoanChi: 'Khoản chi',
    trangThaiHoatDong: 'Hoạt động',
    trangThaiNgung: 'Ngừng',
  },

  soThuChi: {
    noViewPermission: 'Bạn không có quyền xem sổ thu chi của quỹ.',
    exportFileName: 'so-thu-chi',
    noExportData: 'Không có dữ liệu để xuất.',
    deleteTitle: 'Xóa phiếu?',
    deleteMessage:
      'Phiếu sẽ bị xóa vĩnh viễn khỏi sổ quỹ và số dư sẽ đổi theo. Hành động không hoàn tác.',
    bulkDeleteTitle: 'Xóa nhiều phiếu?',
    bulkDeleteMessage: 'Sẽ xóa {{count}} phiếu khỏi sổ quỹ. Hành động không hoàn tác.',
    searchPlaceholder: 'Tìm theo số chứng từ, nội dung, người nộp/nhận, khoản mục…',
    emptyTitle: 'Sổ quỹ chưa có phiếu nào',
    emptyHint: 'Bấm “Thêm mới” để lập phiếu thu hoặc phiếu chi đầu tiên.',
    emptyFilteredHint: 'Không có phiếu nào khớp bộ lọc. Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
    thieuDanhMuc:
      'Chưa có khoản mục hoặc tài khoản cho quỹ này. Vào “Danh mục khoản thu chi” và “Danh mục tài khoản” để khai báo trước khi lập phiếu.',
    toast: {
      create: 'Đã lập phiếu vào sổ quỹ.',
      update: 'Đã cập nhật phiếu.',
      delete: 'Đã xóa {{count}} phiếu.',
    },
    service: {
      notFound: 'Không tìm thấy phiếu. Có thể phiếu đã bị người khác xóa.',
    },
    store: {
      soChungTuCol: 'Số chứng từ',
      ngayChungTuCol: 'Ngày chứng từ',
      loaiCol: 'Loại phiếu',
      khoanCol: 'Khoản mục',
      taiKhoanCol: 'Tài khoản',
      soTienCol: 'Số tiền',
      noiDungCol: 'Nội dung',
      nguoiNopNhanCol: 'Người nộp/nhận',
      donViCol: 'Xã/phường',
      chungTuGocCol: 'Chứng từ gốc',
      ghiChuCol: 'Ghi chú',
      nguoiTaoCol: 'Người lập',
      tgTaoCol: 'Ngày tạo',
      tgCapNhatCol: 'Cập nhật',
    },
    filter: {
      loaiPlaceholder: 'Loại phiếu',
      khoanPlaceholder: 'Khoản mục',
      taiKhoanPlaceholder: 'Tài khoản',
      ngayPlaceholder: 'Ngày chứng từ',
    },
    form: {
      createSubtitle: 'Lập phiếu mới',
      editSubtitle: 'Sửa phiếu',
      sectionChungTu: 'Chứng từ',
      sectionTien: 'Nội dung và số tiền',
      sectionKhac: 'Thông tin thêm',
      loai: 'Loại phiếu',
      loaiHintEdit: 'Phiếu đã phát hành số nên không đổi được loại. Cần đổi thì xóa và lập lại.',
      soChungTu: 'Số chứng từ',
      soChungTuHintCreate: 'Hệ thống tự cấp số khi lưu (PT-2026-0001 / PC-2026-0001).',
      soChungTuHintEdit: 'Số chứng từ đã phát hành nên không sửa được.',
      ngayChungTu: 'Ngày chứng từ',
      khoan: 'Khoản mục',
      khoanHint: 'Chỉ hiện khoản mục cùng loại với phiếu và đang hoạt động.',
      khoanEmptyThu: 'Chưa có khoản thu nào. Khai báo ở Danh mục khoản thu chi.',
      khoanEmptyChi: 'Chưa có khoản chi nào. Khai báo ở Danh mục khoản thu chi.',
      taiKhoan: 'Tài khoản / nguồn tiền',
      taiKhoanEmpty: 'Chưa có tài khoản nào. Khai báo ở Danh mục tài khoản.',
      soTien: 'Số tiền (đồng)',
      soTienHint: 'Nhập số dương. Gõ liền hoặc có dấu chấm đều được: 1500000 hay 1.500.000.',
      noiDung: 'Nội dung',
      nguoiNopNhanThu: 'Người nộp tiền',
      nguoiNopNhanChi: 'Người nhận tiền',
      donVi: 'Xã/phường liên quan',
      donViHint: 'Tùy chọn — dùng cho báo cáo theo địa bàn.',
      chungTuGoc: 'Chứng từ gốc',
      chungTuGocHint: 'Số hóa đơn, biên lai, quyết định… kèm theo phiếu.',
      ghiChu: 'Ghi chú',
    },
    validation: {
      loaiRequired: 'Chọn loại phiếu thu hay phiếu chi.',
      ngayRequired: 'Chọn ngày chứng từ.',
      khoanRequired: 'Chọn khoản mục.',
      taiKhoanRequired: 'Chọn tài khoản / nguồn tiền.',
      soTienRequired: 'Nhập số tiền.',
      soTienKhongDoc: 'Số tiền chưa hợp lệ. Chỉ nhập chữ số, ví dụ 1.500.000.',
      soTienPhaiDuong: 'Số tiền phải lớn hơn 0.',
      noiDungRequired: 'Nhập nội dung thu/chi.',
      donViInvalid: 'Xã/phường không hợp lệ.',
    },
    detail: {
      title: 'Chi tiết phiếu',
      sectionChungTu: 'Chứng từ',
      sectionTien: 'Nội dung và số tiền',
      sectionKhac: 'Thông tin thêm',
      systemInfo: 'Thông tin hệ thống',
      nguoiTao: 'Người lập phiếu',
      tgTao: 'Thời điểm tạo',
      tgCapNhat: 'Cập nhật lần cuối',
    },
  },

  danhMucKhoan: {
    noViewPermission: 'Bạn không có quyền xem danh mục khoản thu chi của quỹ.',
    exportFileName: 'danh-muc-khoan-thu-chi',
    noExportData: 'Không có dữ liệu để xuất.',
    deleteTitle: 'Xóa khoản mục?',
    deleteMessage:
      'Khoản mục sẽ bị xóa vĩnh viễn. Nếu đã có phiếu dùng khoản mục này thì hệ thống sẽ không cho xóa.',
    bulkDeleteTitle: 'Xóa nhiều khoản mục?',
    bulkDeleteMessage: 'Sẽ xóa {{count}} khoản mục. Hành động không hoàn tác.',
    searchPlaceholder: 'Tìm theo tên khoản mục, mô tả…',
    emptyTitle: 'Chưa có khoản thu chi nào',
    emptyHint: 'Thêm khoản thu và khoản chi để phân loại các phiếu trong sổ quỹ.',
    emptyFilteredHint: 'Không có khoản mục nào khớp bộ lọc. Thử xóa bộ lọc hoặc đổi từ khóa.',
    toast: {
      create: 'Đã thêm khoản mục.',
      update: 'Đã cập nhật khoản mục.',
      delete: 'Đã xóa {{count}} khoản mục.',
    },
    store: {
      thuTuCol: 'TT',
      loaiCol: 'Loại',
      tenCol: 'Tên khoản mục',
      moTaCol: 'Mô tả',
      trangThaiCol: 'Trạng thái',
      tgTaoCol: 'Ngày tạo',
      tgCapNhatCol: 'Cập nhật',
    },
    filter: {
      loaiPlaceholder: 'Loại',
      trangThaiPlaceholder: 'Trạng thái',
    },
    form: {
      createSubtitle: 'Thêm khoản thu chi',
      editSubtitle: 'Sửa khoản thu chi',
      sectionMain: 'Thông tin khoản mục',
      loai: 'Loại',
      loaiHint: 'Khoản thu dùng cho phiếu thu, khoản chi dùng cho phiếu chi.',
      loaiHintEdit: 'Đổi loại khi khoản mục đã có phiếu sẽ bị hệ thống từ chối.',
      ten: 'Tên khoản mục',
      moTa: 'Mô tả',
      thuTu: 'Thứ tự hiển thị',
      trangThai: 'Trạng thái',
      trangThaiHint: 'Khoản mục “Ngừng” không còn hiện khi lập phiếu mới.',
    },
    validation: {
      loaiRequired: 'Chọn khoản thu hay khoản chi.',
      tenRequired: 'Nhập tên khoản mục.',
      trangThaiRequired: 'Chọn trạng thái.',
      thuTuInvalid: 'Thứ tự hiển thị chỉ nhận số nguyên không âm.',
    },
    detail: {
      title: 'Chi tiết khoản thu chi',
      sectionMain: 'Thông tin',
      systemInfo: 'Thông tin hệ thống',
      tgTao: 'Thời điểm tạo',
      tgCapNhat: 'Cập nhật lần cuối',
    },
  },

  danhMucTaiKhoan: {
    noViewPermission: 'Bạn không có quyền xem danh mục tài khoản của quỹ.',
    exportFileName: 'danh-muc-tai-khoan',
    noExportData: 'Không có dữ liệu để xuất.',
    deleteTitle: 'Xóa tài khoản?',
    deleteMessage:
      'Tài khoản sẽ bị xóa vĩnh viễn. Nếu đã có phiếu dùng tài khoản này thì hệ thống sẽ không cho xóa.',
    bulkDeleteTitle: 'Xóa nhiều tài khoản?',
    bulkDeleteMessage: 'Sẽ xóa {{count}} tài khoản. Hành động không hoàn tác.',
    searchPlaceholder: 'Tìm theo tên, số tài khoản, ngân hàng…',
    emptyTitle: 'Chưa có tài khoản nào',
    emptyHint: 'Thêm quỹ tiền mặt hoặc tài khoản ngân hàng để bắt đầu ghi sổ.',
    emptyFilteredHint: 'Không có tài khoản nào khớp bộ lọc. Thử xóa bộ lọc hoặc đổi từ khóa.',
    toast: {
      create: 'Đã thêm tài khoản.',
      update: 'Đã cập nhật tài khoản.',
      delete: 'Đã xóa {{count}} tài khoản.',
    },
    store: {
      thuTuCol: 'TT',
      tenCol: 'Tên tài khoản',
      soTaiKhoanCol: 'Số tài khoản',
      nganHangCol: 'Ngân hàng',
      moTaCol: 'Mô tả',
      trangThaiCol: 'Trạng thái',
      soDuCol: 'Số dư',
      tgTaoCol: 'Ngày tạo',
      tgCapNhatCol: 'Cập nhật',
    },
    filter: {
      trangThaiPlaceholder: 'Trạng thái',
      loaiNguonPlaceholder: 'Hình thức',
      loaiNguonTienMat: 'Tiền mặt',
      loaiNguonNganHang: 'Ngân hàng',
    },
    form: {
      createSubtitle: 'Thêm tài khoản',
      editSubtitle: 'Sửa tài khoản',
      sectionMain: 'Thông tin tài khoản',
      ten: 'Tên tài khoản',
      tenHint: 'Ví dụ: Quỹ tiền mặt, Tài khoản Vietcombank chi nhánh tỉnh.',
      soTaiKhoan: 'Số tài khoản',
      soTaiKhoanHint: 'Để trống nếu đây là quỹ tiền mặt.',
      nganHang: 'Ngân hàng',
      moTa: 'Mô tả',
      thuTu: 'Thứ tự hiển thị',
      trangThai: 'Trạng thái',
      trangThaiHint: 'Tài khoản “Ngừng” không còn hiện khi lập phiếu mới.',
    },
    validation: {
      tenRequired: 'Nhập tên tài khoản.',
      trangThaiRequired: 'Chọn trạng thái.',
      thuTuInvalid: 'Thứ tự hiển thị chỉ nhận số nguyên không âm.',
    },
    detail: {
      title: 'Chi tiết tài khoản',
      sectionMain: 'Thông tin',
      systemInfo: 'Thông tin hệ thống',
      tgTao: 'Thời điểm tạo',
      tgCapNhat: 'Cập nhật lần cuối',
    },
  },

  baoCao: {
    noViewPermission: 'Bạn không có quyền xem báo cáo thống kê quỹ.',
    exportFileName: 'bao-cao-quy',
    noExportData: 'Không có dữ liệu để xuất.',
    kpiTongThu: 'Tổng thu',
    kpiTongChi: 'Tổng chi',
    kpiSoDu: 'Số dư trong kỳ',
    kpiSoPhieu: 'Số phiếu',
    kpiSoPhieuThu: 'Phiếu thu',
    kpiSoPhieuChi: 'Phiếu chi',
    chartXuHuong: 'Diễn biến thu – chi theo tháng',
    chartTheoKhoanThu: 'Thu theo khoản mục',
    chartTheoKhoanChi: 'Chi theo khoản mục',
    tableTheoTaiKhoan: 'Thu – chi – số dư theo tài khoản',
    tableTheoKy: 'Tổng hợp theo tháng',
    tableTheoDonVi: 'Thu – chi theo xã/phường',
    colTaiKhoan: 'Tài khoản',
    colKhoan: 'Khoản mục',
    colKy: 'Tháng',
    colDonVi: 'Xã/phường',
    colThu: 'Thu',
    colChi: 'Chi',
    colSoDu: 'Số dư',
    colSoPhieu: 'Số phiếu',
    emptyTitle: 'Chưa có dữ liệu trong kỳ đã chọn',
    emptyHint: 'Đổi khoảng thời gian hoặc xóa bộ lọc để xem số liệu khác.',
    emptyNoData: 'Sổ quỹ chưa có phiếu nào. Lập phiếu ở màn Sổ thu chi trước.',
    filterKhoanPlaceholder: 'Khoản mục',
    filterTaiKhoanPlaceholder: 'Tài khoản',
    filterLoaiPlaceholder: 'Loại phiếu',
    khongXacDinh: 'Không xác định',
  },
} as const;
