export const matTranTonKho = {
  noViewPermission: 'Bạn không có quyền xem tồn kho.',
  listLoadErrorHint: 'Không tải được dữ liệu tồn kho. Thử lại sau.',
  tabs: {
    byProduct: 'Tồn hàng hóa',
    baoCaoNXT: 'Báo cáo NXT',
  },
  empty: 'Không có dữ liệu tồn kho.',
  records: 'bản ghi',
  byProduct: {
    searchPlaceholder: 'Tên hàng, danh mục…',
    empty: 'Không có dữ liệu',
    emptyHint: 'Thử đổi bộ lọc kho hoặc danh mục.',
    totalQty: 'Tổng SL',
    warehouseCount: 'Số kho có tồn',
    noExportData: 'Không có dữ liệu để xuất.',
  },
  toolbar: {
    warehouse: 'Kho',
    category: 'Danh mục',
    export: 'Xuất Excel',
  },
  table: {
    maHang: 'Mã',
    tenHang: 'Tên hàng',
    danhMuc: 'Danh mục',
    dvt: 'ĐVT',
    kho: 'Kho',
    soLuong: 'Số lượng',
  },
  export: {
    maHang: 'Mã',
    tenHang: 'Tên hàng',
    danhMuc: 'Danh mục',
    dvt: 'ĐVT',
    kho: 'Kho',
    soLuong: 'Số lượng',
    success: 'Đã xuất file.',
    error: 'Xuất file thất bại.',
  },
  summary: {
    tonDauKy: 'Tồn đầu kỳ',
    tongNhap: 'Nhập trong kỳ',
    tongXuat: 'Xuất trong kỳ',
    tonCuoiKy: 'Tồn cuối kỳ',
  },
  nxt: {
    period: 'Kỳ báo cáo',
    periodPlaceholder: 'Chọn kỳ',
    filterWarehousePlaceholder: 'Tất cả kho',
    filterLoaiPlaceholder: 'Loại phiếu',
    filterCategoryPlaceholder: 'Danh mục',
    filterProductPlaceholder: 'Hàng hóa',
    export: 'Xuất',
    exportExcel: 'Xuất Excel',
    print: 'In báo cáo',
    refresh: 'Làm mới',
    periodLabel: '{{from}} — {{to}}',
    preset: {
      all: 'Tất cả',
      thisMonth: 'Tháng này',
      lastMonth: 'Tháng trước',
      thisQuarter: 'Quý này',
      thisYear: 'Năm nay',
      custom: 'Tuỳ chọn',
    },
    warehouses: 'Kho',
    loaiPhieu: 'Loại phiếu',
    categories: 'Danh mục',
    products: 'Hàng hóa',
    dateInvalid: 'Từ ngày không được sau Đến ngày.',
    selectPeriod: 'Chọn kỳ báo cáo (từ ngày — đến ngày).',
    loading: 'Đang tải báo cáo…',
    maHang: 'Mã',
    tenHang: 'Tên hàng',
    danhMuc: 'Danh mục',
    dvt: 'ĐVT',
    tonDau: 'Tồn đầu',
    nhap: 'Nhập',
    xuat: 'Xuất',
    tonCuoi: 'Tồn cuối',
    tenKho: 'Tên kho',
    empty: 'Không có dữ liệu trong kỳ đã chọn.',
    emptyHint: 'Thử đổi kỳ hoặc xóa bộ lọc.',
    noData: 'Chưa có dữ liệu để xuất.',
    sectionByProduct: 'Theo hàng hóa',
    detailDrawer: {
      title: 'Chi tiết NXT theo hàng',
      sectionTotals: 'Tổng hợp trong kỳ',
      sectionByWarehouse: 'Chi tiết theo kho',
      emptyWarehouse: 'Không có dòng theo kho (cùng bộ lọc kỳ).',
    },
  },
  detail: {
    productTitle: 'Tồn theo hàng hóa',
    sectionSummary: 'Tóm tắt',
    sectionByWarehouse: 'Số lượng theo kho',
    historyNx: {
      title: 'Lịch sử NX',
      loading: 'Đang tải lịch sử…',
      empty: 'Chưa có phiếu kho',
      emptyHint: 'Chưa có dòng chi tiết phiếu kho cho hàng này.',
      colDate: 'Ngày',
      colSoPhieu: 'Số phiếu',
      colLoai: 'Loại',
      colKho: 'Kho',
      colSl: 'Số lượng',
      colTon: 'Tồn',
      loaiNhap: 'Nhập',
      loaiXuat: 'Xuất',
      loaiChuyen: 'Luân chuyển',
      khoChuyen: '{{from}} → {{to}}',
    },
  },
};
