export const matTranDonViCuuTro = {
  noViewPermission: 'Bạn không có quyền xem danh sách đơn vị cứu trợ.',
  deleteTitle: 'Xóa đơn vị cứu trợ?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều bản ghi?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'don-vi-cuu-tro',
  toast: {
    create: 'Đã tạo bản ghi.',
    update: 'Đã cập nhật bản ghi.',
    delete: 'Đã xóa {{count}} bản ghi.',
  },
  service: {
    notFound: 'Không tìm thấy bản ghi.',
  },
  validation: {
    loaiRequired: 'Chọn loại: tổ chức hoặc cá nhân.',
    tenRequired: 'Nhập tên tổ chức hoặc họ tên.',
    emailInvalid: 'Email không hợp lệ.',
  },
  store: {
    ttCol: 'TT',
    loaiCol: 'Loại',
    tenCol: 'Tên',
    diaChiCol: 'Địa chỉ',
    dienThoaiCol: 'Điện thoại',
    emailCol: 'Email',
    ghiChuCol: 'Ghi chú',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Đơn vị cứu trợ',
  },
  searchPlaceholder: 'Tìm theo tên, địa chỉ, SĐT, email…',
  emptyTitle: 'Chưa có đơn vị cứu trợ',
  emptyHint: 'Thêm tổ chức hoặc cá nhân tham gia quyên góp.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  /** Danh sách — lỗi tải (kèm nút thử lại trên trang). */
  listLoadErrorHint: 'Không tải được danh sách. Kiểm tra kết nối rồi thử lại.',
  loai: {
    toChuc: 'Tổ chức',
    caNhan: 'Cá nhân',
  },
  form: {
    sectionMain: 'Thông tin',
    loai: 'Loại',
    ten: 'Tên',
    diaChi: 'Địa chỉ',
    dienThoai: 'Điện thoại',
    email: 'Email',
    ghiChu: 'Ghi chú',
    createSubtitle: 'Thêm đơn vị cứu trợ',
    editSubtitle: 'Sửa thông tin',
  },
  detail: {
    title: 'Chi tiết đơn vị cứu trợ',
    sectionMain: 'Thông tin',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
};
