export const matTranDonViCuuTro = {
  noViewPermission: 'Bạn không có quyền xem danh sách đơn vị hỗ trợ.',
  deleteTitle: 'Xóa đơn vị hỗ trợ?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều bản ghi?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'don-vi-cuu-tro',
  toast: {
    create: 'Đã tạo bản ghi.',
    update: 'Đã cập nhật bản ghi.',
    delete: 'Đã xóa {{count}} bản ghi.',
    importSuccess: 'Đã nhập {{count}} đơn vị hỗ trợ',
  },
  import: {
    templateName: 'don-vi-cuu-tro',
    rowError: 'Dòng {{row}}: {{message}}',
    errDonViGioiThieuNotFound: 'Không tìm thấy đơn vị giới thiệu «{{ten}}». Ghi "MTTQ tỉnh" hoặc đúng tên xã/phường.',
  },
  service: {
    notFound: 'Không tìm thấy bản ghi.',
  },
  validation: {
    loaiRequired: 'Chọn loại đối tượng trong danh sách.',
    tenRequired: 'Nhập tên nhà tài trợ hoặc họ tên.',
    emailInvalid: 'Email không hợp lệ.',
    soNguoiInvalid: 'Số người phải là số nguyên không âm.',
    donViGioiThieuInvalid: 'Đơn vị giới thiệu chưa hợp lệ. Chọn lại trong danh sách.',
  },
  store: {
    ttCol: 'TT',
    loaiCol: 'Loại đối tượng',
    tenCol: 'Tên nhà tài trợ',
    soNguoiCol: 'Số người',
    nguoiDaiDienCol: 'Người đại diện',
    chucVuCol: 'Chức vụ',
    diaChiCol: 'Địa chỉ',
    dienThoaiCol: 'Điện thoại',
    donViGioiThieuCol: 'Đơn vị giới thiệu',
    emailCol: 'Email',
    ghiChuCol: 'Ghi chú',
    tgTaoCol: 'Ngày tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Đơn vị hỗ trợ',
    filterDonViGioiThieu: 'Đơn vị giới thiệu',
  },
  emptyTitle: 'Chưa có đơn vị hỗ trợ',
  emptyHint: 'Thêm doanh nghiệp, câu lạc bộ, cơ sở tôn giáo, nhóm thiện nguyện hoặc cá nhân tham gia quyên góp.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  /** Danh sách — lỗi tải (kèm nút thử lại trên trang). */
  listLoadErrorHint: 'Không tải được danh sách. Kiểm tra kết nối rồi thử lại.',
  loai: {
    doanhNghiep: 'Doanh nghiệp',
    cauLacBo: 'Câu lạc bộ',
    cqCapTinh: 'CQ cấp tỉnh',
    caNhan: 'Cá nhân',
    coSoTonGiao: 'Cơ sở tôn giáo',
    nhomThienNguyen: 'Nhóm thiện nguyện',
    donViSuNghiep: 'Đơn vị sự nghiệp',
    cqCapXa: 'CQ cấp xã',
  },
  /** Nhãn cấp tỉnh cho ô "Đơn vị giới thiệu" — trùng cách gọi ở Kỳ họp / Uỷ viên. */
  tinhCap: 'MTTQ tỉnh',
  donViGioiThieuChuaNhap: 'Chưa nhập',
  form: {
    sectionMain: 'Thông tin',
    loai: 'Loại đối tượng',
    ten: 'Tên nhà tài trợ',
    soNguoi: 'Số người',
    nguoiDaiDien: 'Người đại diện',
    chucVu: 'Chức vụ',
    diaChi: 'Địa chỉ',
    dienThoai: 'Điện thoại',
    donViGioiThieu: 'Đơn vị giới thiệu',
    donViGioiThieuPlaceholder: 'Chọn MTTQ tỉnh hoặc xã/phường',
    email: 'Email',
    ghiChu: 'Ghi chú',
    createSubtitle: 'Thêm đơn vị hỗ trợ',
    editSubtitle: 'Sửa thông tin',
  },
  detail: {
    title: 'Chi tiết đơn vị hỗ trợ',
    sectionMain: 'Thông tin',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
};
