/** Chuỗi module Chương trình năm — flatten vào STRINGS với prefix `chuongTrinhNam` */
export const chuongTrinhNam = {
  noViewPermission: 'Bạn không có quyền xem module Chương trình năm.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể tạo chương trình mới.',
  searchPlaceholder: 'Tìm theo tên chương trình, phòng ban, người tạo…',
  emptyTitle: 'Chưa có chương trình năm',
  emptyHint: 'Thêm chương trình để theo dõi kế hoạch theo phòng ban.',
  deleteTitle: 'Xóa chương trình năm',
  deleteMessage: 'Bạn có chắc muốn xóa chương trình này? Hành động không thể hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều chương trình',
  bulkDeleteMessage: 'Xóa {{count}} chương trình đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'chuong-trinh-nam',
  service: {
    notFound: 'Không tìm thấy chương trình.',
    noEmployeeProfile: 'Tài khoản chưa gắn nhân viên — không thể ghi dữ liệu.',
  },
  toast: {
    create: 'Đã tạo chương trình.',
    update: 'Đã cập nhật chương trình.',
    delete: 'Đã xóa {{count}} chương trình.',
  },
  validation: {
    tenRequired: 'Nhập tên chương trình.',
    tenMax: 'Tên chương trình tối đa 500 ký tự.',
    dateRequired: 'Chọn ngày.',
    dateOrder: 'Ngày kết thúc phải sau hoặc trùng ngày bắt đầu.',
    trangThaiRequired: 'Chọn trạng thái.',
  },
  store: {
    tenCol: 'Tên chương trình',
    ngayBatDauCol: 'Bắt đầu',
    ngayKetThucCol: 'Kết thúc',
    trangThaiCol: 'Trạng thái',
    phongBanCol: 'Phòng ban',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  detail: {
    title: 'Chi tiết chương trình năm',
    subtitle: 'Xem đầy đủ nội dung và lịch biểu',
    sectionInfo: 'Thông tin chương trình',
    sectionMeta: 'Lịch sử hệ thống',
    sectionCongViec: 'Công việc theo chương trình',
    fieldTgTao: 'Thời gian tạo',
    fieldGhiChu: 'Ghi chú chương trình',
    actionChangeStatus: 'Chuyển trạng thái',
    noCongViec: 'Chưa có công việc',
    noCongViecHint: 'Thêm công việc gắn với chương trình này.',
    congViecLimitHint:
      'Hiển thị tối đa 200 công việc. Xem đầy đủ tại module Danh sách công việc.',
  },
  changeStatus: {
    title: 'Chuyển trạng thái chương trình',
    section: 'Trạng thái và ghi chú',
    ghiChu: 'Ghi chú',
    ghiChuPlaceholder: 'Tuỳ chọn — lưu ý nội bộ khi đổi trạng thái',
    submit: 'Lưu',
  },
  form: {
    sectionMain: 'Nội dung chương trình',
    sectionSchedule: 'Thời gian và phạm vi',
    ten: 'Tên chương trình',
    moTa: 'Mô tả',
    ngayBatDau: 'Ngày bắt đầu',
    ngayKetThuc: 'Ngày kết thúc',
    trangThai: 'Trạng thái',
    phongBan: 'Phòng ban',
    phongBanPlaceholder: 'Chọn phòng ban (tuỳ chọn)',
    ghiChu: 'Ghi chú',
    createSubtitle: 'Thêm chương trình năm mới.',
    editSubtitle: 'Chỉnh sửa chương trình',
  },
} as const;
