/** Chuỗi module Chương trình BTT — flatten vào STRINGS với prefix `chuongTrinhNam` */
export const chuongTrinhNam = {
  tabList: 'Danh sách',
  tabStats: 'Thống kê',
  stats: {
    title: 'Thống kê chương trình BTT',
    loading: 'Đang tải dữ liệu…',
    noData: 'Không có chương trình trong khoảng và bộ lọc đã chọn.',
    noDataHint: 'Thử đổi khoảng ngày tạo hoặc bỏ bớt bộ lọc.',
    dateRangeLabel: 'Khoảng ngày tạo',
    filterTrangThai: 'Trạng thái',
    filterPhongBan: 'Phòng ban',
    filterNamBatDau: 'Năm bắt đầu',
    filterTienDo: 'Tiến độ',
    exportFileName: 'Thong_Ke_Chuong_Trinh_BTT',
    noExportData: 'Không có dữ liệu để xuất',
    exportRangeFrom: 'Từ ngày (báo cáo)',
    exportRangeTo: 'Đến ngày (báo cáo)',
    kpiTotal: 'Tổng số chương trình',
    kpiHoatDong: 'Hoạt động',
    kpiTamDung: 'Tạm dừng',
    kpiKetThuc: 'Kết thúc',
    kpiTienDoQuaHan: 'Quá hạn (theo ngày kết thúc)',
    kpiTienDoSapDenHan: 'Sắp đến hạn (≤7 ngày)',
    kpiTienDoConHan: 'Còn thời gian',
    kpiTienDoDaKetThuc: 'Đã kết thúc (trạng thái)',
    chartTrendCount: 'Số lượng theo ngày tạo',
    chartTrangThai: 'Theo trạng thái',
    chartTopPhongBan: 'Theo phòng ban (Top)',
    chartTopNamBatDau: 'Theo năm bắt đầu (Top)',
    tableLookupTitle: 'Tra cứu',
    tableColTen: 'Tên chương trình',
    tableColPhongBan: 'Phòng ban',
    tableColTrangThai: 'Trạng thái',
    tableColNgayBatDau: 'Bắt đầu',
    tableColNgayKetThuc: 'Kết thúc',
    tableColTienDo: 'Tiến độ',
    tableColNguoiTao: 'Người tạo',
    tableTwoColLabel: 'Nhóm',
    tableTwoColValue: 'Số lượng',
    preset: {
      thisWeek: 'Tuần này',
      thisMonth: 'Tháng này',
      thisQuarter: 'Quý này',
      thisYear: 'Năm nay',
      custom: 'Tùy chọn',
    },
  },
  noViewPermission: 'Bạn không có quyền xem module Chương trình BTT.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể tạo chương trình mới.',
  searchPlaceholder: 'Tìm theo tên chương trình, phòng ban, người tạo…',
  emptyTitle: 'Chưa có chương trình BTT',
  emptyHint: 'Thêm chương trình để theo dõi kế hoạch theo phòng ban.',
  deleteTitle: 'Xóa chương trình BTT',
  deleteMessage: 'Bạn có chắc muốn xóa chương trình này? Hành động không thể hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều chương trình',
  bulkDeleteMessage: 'Xóa {{count}} chương trình đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  exportFileName: 'chuong-trinh-nam',
  service: {
    notFound: 'Không tìm thấy chương trình.',
    noEmployeeProfile: 'Tài khoản chưa gắn nhân viên — không thể ghi dữ liệu.',
    rowViewDenied: 'Bạn không có quyền xem chương trình này.',
  },
  toast: {
    create: 'Đã tạo chương trình.',
    update: 'Đã cập nhật chương trình.',
    delete: 'Đã xóa {{count}} chương trình.',
  },
  validation: {
    tenRequired: 'Nhập tên chương trình.',
    tenMax: 'Tên chương trình tối đa 500 ký tự.',
    dateRequired: 'Chọn ngày.',
    dateOrder: 'Ngày kết thúc phải sau hoặc trùng ngày bắt đầu.',
    trangThaiRequired: 'Chọn trạng thái.',
  },
  filter: {
    namBatDauChip: 'Năm bắt đầu',
    noPhongBan: 'Chưa gán phòng ban',
    tienDoChip: 'Tiến độ',
    tienDoQuaHan: 'Quá hạn',
    tienDoSapDenHan: 'Sắp đến hạn',
    tienDoConHan: 'Còn thời gian',
    tienDoKetThuc: 'Đã kết thúc',
  },
  tienDo: {
    ended: 'Đã kết thúc',
    noEndDate: 'Chưa có ngày kết thúc',
    overdueDays: 'Quá hạn {{count}} ngày',
    dueToday: 'Đến hạn hôm nay',
    remainingOneDay: 'Còn 1 ngày',
    remainingDays: 'Còn {{count}} ngày',
  },
  store: {
    tenCol: 'Tên chương trình',
    ngayBatDauCol: 'Bắt đầu',
    ngayKetThucCol: 'Kết thúc',
    tienDoCol: 'Tiến độ',
    trangThaiCol: 'Trạng thái',
    phongBanCol: 'Phòng ban',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  detail: {
    fieldTienDo: 'Tiến độ theo ngày kết thúc',
    title: 'Chi tiết chương trình BTT',
    subtitle: 'Xem đầy đủ nội dung và lịch biểu',
    sectionInfo: 'Thông tin chương trình',
    sectionMeta: 'Lịch sử hệ thống',
    sectionCongViec: 'Công việc theo chương trình',
    fieldTgTao: 'Thời gian tạo',
    fieldGhiChu: 'Ghi chú chương trình',
    actionChangeStatus: 'Chuyển trạng thái',
    noCongViec: 'Chưa có công việc',
    noCongViecHint: 'Thêm công việc gắn với chương trình này.',
    congViecLimitHint:
      'Hiển thị tối đa 200 công việc. Xem đầy đủ tại module Danh sách công việc.',
  },
  changeStatus: {
    title: 'Chuyển trạng thái chương trình',
    section: 'Trạng thái và ghi chú',
    ghiChu: 'Ghi chú',
    ghiChuPlaceholder: 'Tuỳ chọn — lưu ý nội bộ khi đổi trạng thái',
    submit: 'Lưu',
  },
  form: {
    sectionMain: 'Nội dung chương trình',
    sectionSchedule: 'Thời gian và phạm vi',
    ten: 'Tên chương trình',
    moTa: 'Mô tả',
    ngayBatDau: 'Ngày bắt đầu',
    ngayKetThuc: 'Ngày kết thúc',
    trangThai: 'Trạng thái',
    phongBan: 'Phòng ban',
    phongBanPlaceholder: 'Chọn phòng ban (tuỳ chọn)',
    ghiChu: 'Ghi chú',
    createSubtitle: 'Thêm chương trình BTT mới.',
    editSubtitle: 'Chỉnh sửa chương trình',
  },
} as const;
