import type { DipThamHoi } from './core/types';

export const DTTG_DIP_THAM_HOI_MOCK: DipThamHoi[] = [
  {
    id: '1',
    ten_dip: 'Đại lễ Phật đản',
    mo_ta: 'Thăm hỏi các cơ sở tôn giáo dịp Phật đản',
    thoi_gian_du_kien: 'Tháng 5/2026',
    thoi_gian_thuc_te: null,
    don_vi_to_chuc_id: null,
    ten_don_vi_to_chuc: null,
    phong_ban_tham_muu_id: '1',
    ten_phong_ban: 'Phòng Dân tộc Tôn giáo',
    so_luong_to_chuc_du_kien: 10,
    so_luong_ca_nhan_du_kien: 5,
    so_luong_du_kien_tong: 15,
    so_thuc_hien_to_chuc: 2,
    so_thuc_hien_ca_nhan: 1,
    so_hoan_thanh_to_chuc: 0,
    so_hoan_thanh_ca_nhan: 0,
    so_luong_thuc_te_tong: 0,
    trang_thai: 'Chưa thực hiện',
    ghi_chu: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-01-01T00:00:00.000Z',
    tg_cap_nhat: '2026-01-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock User',
  },
  {
    id: '2',
    ten_dip: 'Ngày Thương binh - Liệt sĩ (27/7)',
    mo_ta: 'Thăm hỏi dịp 27/7',
    thoi_gian_du_kien: 'Tháng 7/2026',
    thoi_gian_thuc_te: '2026-07-27',
    don_vi_to_chuc_id: null,
    ten_don_vi_to_chuc: null,
    phong_ban_tham_muu_id: null,
    ten_phong_ban: null,
    so_luong_to_chuc_du_kien: 8,
    so_luong_ca_nhan_du_kien: 12,
    so_luong_du_kien_tong: 20,
    so_thuc_hien_to_chuc: 3,
    so_thuc_hien_ca_nhan: 2,
    so_hoan_thanh_to_chuc: 1,
    so_hoan_thanh_ca_nhan: 1,
    so_luong_thuc_te_tong: 2,
    trang_thai: 'Đang thực hiện',
    ghi_chu: null,
    id_nguoi_tao: '1',
    tg_tao: '2026-02-01T00:00:00.000Z',
    tg_cap_nhat: '2026-06-01T00:00:00.000Z',
    ho_va_ten_nguoi_tao: 'Mock User',
  },
];
