export const danTocDipThamHoi = {
  noViewPermission: 'Bạn không có quyền xem dịp thăm hỏi.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  searchPlaceholder: 'Tìm theo tên dịp, mô tả, ghi chú…',
  emptyTitle: 'Chưa có dịp thăm hỏi',
  emptyHint: 'Thêm dịp thăm hỏi để quản lý kế hoạch và theo dõi thực hiện.',
  emptyFilteredHint: 'Không có bản ghi phù hợp bộ lọc. Thử điều chỉnh tìm kiếm hoặc chip lọc.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'dip-tham-hoi',
  deleteTitle: 'Xóa dịp thăm hỏi',
  deleteMessage: 'Bạn có chắc muốn xóa dịp thăm hỏi này? Các lượt thăm hỏi con sẽ mất liên kết dịp.',
  bulkDeleteTitle: 'Xóa nhiều dịp thăm hỏi',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} dịp thăm hỏi đã chọn?',
  service: {
    notFound: 'Không tìm thấy dịp thăm hỏi',
    noEmployeeProfile: 'Không xác định được hồ sơ nhân viên. Vui lòng đăng nhập lại.',
    tenDipDuplicate: 'Tên dịp thăm hỏi đã tồn tại',
  },
  toast: {
    create: 'Đã thêm dịp thăm hỏi',
    update: 'Đã cập nhật dịp thăm hỏi',
    delete: 'Đã xóa {{count}} dịp thăm hỏi',
    changeStatus: 'Đã cập nhật trạng thái',
  },
  validation: {
    tenDipRequired: 'Vui lòng nhập tên dịp thăm hỏi',
    trangThaiInvalid: 'Trạng thái không hợp lệ',
    soLuongInt: 'Số lượng phải là số nguyên',
    soLuongMin: 'Số lượng không được âm',
  },
  store: {
    tenDipCol: 'Tên dịp',
    thoiGianDuKienCol: 'Thời gian dự kiến',
    thoiGianThucTeCol: 'Thời gian thực tế',
    donViCol: 'Đơn vị tổ chức',
    phongBanCol: 'Phòng ban tham mưu',
    donViTinhCap: 'MTTQ Tỉnh',
    soDuKienToChucCol: 'Dự kiến tổ chức',
    soDuKienCaNhanCol: 'Dự kiến cá nhân',
    soDuKienTongCol: 'Dự kiến tổng',
    soThucTeTongCol: 'Thực tế (hoàn thành)',
    soThucHienToChucCol: 'Thực hiện tổ chức',
    soThucHienCaNhanCol: 'Thực hiện cá nhân',
    trangThaiCol: 'Trạng thái',
    moTaCol: 'Mô tả',
    ghiChuCol: 'Ghi chú',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm dịp thăm hỏi',
    editSubtitle: 'Cập nhật dịp thăm hỏi',
    sectionMain: 'Thông tin chính',
    sectionPlan: 'Kế hoạch số lượng',
    sectionNote: 'Ghi chú',
    tenDip: 'Tên dịp thăm hỏi',
    moTa: 'Mô tả',
    thoiGianDuKien: 'Thời gian dự kiến',
    thoiGianDuKienHint: 'VD: Tháng 5/2026',
    thoiGianThucTe: 'Thời gian thực tế',
    donViToChuc: 'Đơn vị tổ chức',
    donViToChucPlaceholder: 'Chọn đơn vị',
    phongBanThamMuu: 'Phòng ban tham mưu',
    phongBanPlaceholder: 'Chọn phòng ban',
    soLuongToChucDuKien: 'Số lượng dự kiến tổ chức',
    soLuongCaNhanDuKien: 'Số lượng dự kiến cá nhân',
    trangThai: 'Trạng thái',
    ghiChu: 'Ghi chú',
  },
  detail: {
    title: 'Chi tiết dịp thăm hỏi',
    sectionMain: 'Thông tin chính',
    sectionStats: 'Thống kê thực hiện',
    sectionDetailList: 'Danh sách chi tiết',
    tabToChuc: 'Thăm hỏi tổ chức',
    tabCaNhan: 'Thăm hỏi cá nhân',
    noChildToChuc: 'Chưa có lượt thăm hỏi tổ chức',
    noChildCaNhan: 'Chưa có lượt thăm hỏi cá nhân',
    addToChuc: 'Thêm tổ chức',
    addCaNhan: 'Thêm cá nhân',
    viewAllToChuc: 'Xem tất cả tổ chức',
    viewAllCaNhan: 'Xem tất cả cá nhân',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Ngày tạo',
    tgCapNhat: 'Cập nhật lần cuối',
    nguoiTao: 'Người tạo',
    actionChangeStatus: 'Chuyển trạng thái',
    changeStatusTitle: 'Chuyển trạng thái dịp thăm hỏi',
    changeStatusHint: 'Chọn trạng thái mới cho dịp thăm hỏi',
  },
};
