export const viNguoiNgheo = {
  tabs: {
    danhSach: 'Danh sách',
    thongKe: 'Thống kê',
  },
  noViewPermission: 'Bạn không có quyền xem module Chương trình hỗ trợ.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập khoản hỗ trợ thuộc xã/phường của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có khoản hỗ trợ nào',
  exportFileName: 'Chuong_Trinh_Ho_Tro',
  deleteTitle: 'Xóa khoản hỗ trợ',
  deleteMessage: 'Bạn có chắc muốn xóa khoản hỗ trợ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều khoản hỗ trợ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} khoản hỗ trợ đã chọn? Hành động không hoàn tác.',
  detailTitle: 'Chi tiết khoản hỗ trợ',
  detail: {
    systemInfo: 'Thông tin hệ thống',
    actionChangeStatus: 'Chuyển trạng thái',
    lienKetHoNgheo: 'Liên kết hộ nghèo',
    daLienKet: 'Đã liên kết',
    chuaLienKet: 'Nhập tay (không liên kết)',
  },
  statusChangeModal: {
    canNhapTien: 'Khoản "Đã nhận" phải có số tiền / giá trị quy đổi cụ thể. Mở "Sửa" để nhập trước.',
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái khoản hỗ trợ và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
  },
  store: {
    namCol: 'Năm',
    noiDungCol: 'Nội dung hỗ trợ',
    linhVucCol: 'Lĩnh vực hỗ trợ',
    nguonCol: 'Nguồn',
    nguonHoTroCol: 'Nguồn hỗ trợ',
    nguoiNhanCol: 'Họ và tên người được hỗ trợ',
    xaPhuongCol: 'Xã phường',
    khoiXomCol: 'Khối xóm',
    doiTuongCol: 'Đối tượng',
    hinhThucCol: 'Hình thức hỗ trợ',
    soTienCol: 'Số tiền hỗ trợ',
    soLuongCol: 'Số lượng',
    tongTienQuyDoiCol: 'Tổng tiền quy đổi',
    tongTienBanGiaoCol: 'Tổng tiền khi bàn giao',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Ngày cập nhật trạng thái',
    donViHoTroCol: 'Nhà tài trợ',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm khoản hỗ trợ',
    editSubtitle: 'Cập nhật khoản hỗ trợ',
    sectionNguoiNhan: 'Người được hỗ trợ',
    sectionHoTro: 'Nội dung & nguồn hỗ trợ',
    sectionTrangThai: 'Trạng thái',
    hoNgheoLabel: 'Chọn từ danh sách hộ nghèo',
    hoTenTuHoNgheo: 'Tự lấy theo hộ nghèo đã chọn',
    hoNgheoHint: 'Chỉ chọn được người trong danh sách hộ nghèo — họ tên, xã phường, khối xóm, đối tượng tự điền theo hộ. Chưa có thì thêm hộ ở Danh sách hộ nghèo trước.',
    hoNgheoPlaceholder: 'Tìm theo tên hoặc số căn cước…',
    donViHoTroPlaceholder: 'Chọn từ danh mục Nhà tài trợ',
    soTienPlaceholder: 'Để trống nếu chỉ hỗ trợ bằng hiện vật',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
  },
  phieuKhaoSat: {
    tenPhieu: {
      'thien-tai': 'Phiếu khảo sát hộ bị thiệt hại do thiên tai, sự cố',
      'benh-tat': 'Phiếu khảo sát hộ có thành viên ốm đau hoặc qua đời',
      'sinh-ke': 'Phiếu khảo sát hỗ trợ mô hình sinh kế',
      'hoc-sinh': 'Phiếu khảo sát học sinh có hoàn cảnh khó khăn',
    },
    hint: 'Thông tin chủ hộ (căn cước, năm sinh, nhân khẩu, dân tộc…) lấy từ hộ nghèo đã chọn ở trên — sửa ở hồ sơ hộ nghèo. Ô nào để trống thì phiếu in dòng chấm để viết tay.',
    hintChuaGanHo: 'Chưa chọn hộ nghèo: phần thông tin chủ hộ trên phiếu sẽ in dòng chấm.',
    dangTai: 'Đang tải dữ liệu phiếu khảo sát…',
    nhomChung: 'Thông tin chung',
    nhomMucII: 'Mục II',
    nhomYKien: 'Ý kiến tổ công tác',
    nhomBenh: 'Trường hợp ốm đau, bệnh hiểm nghèo',
    nhomQuaDoi: 'Trường hợp qua đời',
    nhomNhaO: 'Chi tiết nhà ở (khi nhà sập đổ hoặc hư hỏng nặng)',
    khac: 'Khác:',
    khacPlaceholder: 'Ghi rõ…',
    actionPrint: 'In phiếu',
    detailEmpty: 'Chưa nhập dữ liệu phiếu khảo sát.',
    khongCoPhieu: 'Lĩnh vực này không có phiếu khảo sát để in.',
    notFound: 'Không tìm thấy khoản hỗ trợ.',
    nhan: {
      chung: {
        ngay_khao_sat: 'Ngày khảo sát',
        thu_nhap_binh_quan: 'Thu nhập bình quân/tháng',
        doi_tuong_uu_tien: 'Đối tượng ưu tiên',
        hoan_canh_gia_dinh: 'Hoàn cảnh gia đình',
        ho_tro_nguon_khac: 'Đã nhận hỗ trợ từ nguồn khác (nguồn, nội dung, giá trị)',
        ket_luan: 'Kết luận',
        muc_de_xuat: 'Mức/nội dung đề xuất hỗ trợ',
        muc_de_xuat_placeholder: 'Để trống thì in nội dung và số tiền của khoản hỗ trợ',
        ghi_chu: 'Ghi chú của tổ công tác',
      },
      thien_tai: {
        loai_su_co: 'Loại thiên tai, sự cố',
        thoi_gian_xay_ra: 'Thời gian xảy ra',
        thiet_hai_nha: 'Thiệt hại về nhà ở',
        thiet_hai_tai_san: 'Thiệt hại về tài sản, lương thực, vật dụng thiết yếu',
        thiet_hai_san_xuat: 'Thiệt hại về cây trồng, vật nuôi, sản xuất',
        uoc_tinh_thiet_hai: 'Ước tính tổng giá trị thiệt hại',
        ket_cau_nha: 'Kết cấu nhà (loại nhà, tường, mái)',
        dien_tich_nha: 'Diện tích nhà (m²)',
        nam_xay_dung: 'Năm xây dựng',
        noi_o_tam: 'Nơi ở tạm hiện nay',
        kha_nang_doi_ung: 'Khả năng đối ứng của hộ (kinh phí, ngày công)',
        nhu_cau: 'Nhu cầu cần hỗ trợ',
      },
      benh_tat: {
        ho_ten: 'Họ tên thành viên',
        nam_sinh: 'Năm sinh',
        quan_he_chu_ho: 'Quan hệ với chủ hộ',
        chan_doan: 'Bệnh/chẩn đoán',
        co_so_dieu_tri: 'Cơ sở khám, chữa bệnh đang điều trị',
        dieu_tri_tu: 'Điều trị từ ngày',
        dieu_tri_den: 'Điều trị đến ngày',
        co_bhyt: 'Thẻ bảo hiểm y tế',
        chi_phi_da_tra: 'Chi phí đã chi trả',
        chi_phi_du_kien: 'Chi phí dự kiến',
        ngay_mat: 'Ngày mất',
        noi_mat: 'Nơi mất',
        nguyen_nhan: 'Nguyên nhân',
        nguoi_phu_thuoc: 'Người phụ thuộc còn lại (con nhỏ, người già, người khuyết tật...)',
        giay_to: 'Giấy tờ kèm theo',
        nhu_cau: 'Nhu cầu cần hỗ trợ',
      },
      sinh_ke: {
        so_lao_dong: 'Số lao động trong hộ',
        nguon_thu_nhap_chinh: 'Nguồn thu nhập chính',
        dien_tich_dat_sx: 'Diện tích đất sản xuất (m²)',
        chuong_trai: 'Chuồng trại/mặt bằng',
        kinh_nghiem: 'Kinh nghiệm sản xuất, kinh doanh',
        mo_hinh: 'Mô hình đề nghị hỗ trợ',
        quy_mo: 'Quy mô, số lượng đề nghị',
        von_doi_ung: 'Vốn, công lao động đối ứng của hộ',
        hieu_qua_du_kien: 'Hiệu quả dự kiến',
        nguoi_huong_dan: 'Người theo dõi, hướng dẫn kỹ thuật',
      },
      hoc_sinh: {
        ho_ten: 'Họ tên học sinh',
        gioi_tinh: 'Giới tính',
        ngay_sinh: 'Ngày sinh',
        lop: 'Lớp',
        truong: 'Trường',
        quan_he_chu_ho: 'Quan hệ với chủ hộ',
        ket_qua_hoc_tap: 'Kết quả học tập năm học trước',
        hoan_canh: 'Hoàn cảnh của học sinh',
        khoang_cach_km: 'Khoảng cách từ nhà đến trường (km)',
        phuong_tien: 'Phương tiện đi học',
        nhu_cau: 'Nhu cầu cần hỗ trợ',
      },
    },
  },
  inPhieu: {
    chonPhieuTitle: 'Chọn phiếu in',
    tenPhieu: {
      'khao-sat': 'Phiếu khảo sát',
      'ban-giao': 'Biên bản bàn giao tiền, hiện vật',
    },
    moTa: {
      'khao-sat': 'Phiếu khảo sát theo lĩnh vực hỗ trợ',
      'ban-giao': 'Bàn giao tiền mặt / hiện vật cho người nhận, có bên làm chứng',
    },
    loaiPhieuKhongHopLe: 'Loại phiếu in không hợp lệ.',
  },
  bienBanBanGiao: {
    section: 'Biên bản bàn giao',
    hint: 'Người nhận, căn cước, số tiền, nguồn, đơn vị tài trợ và người được hỗ trợ (học sinh / người bệnh / người qua đời — nhập ở phiếu khảo sát) tự lấy khi in. Ô nào để trống thì biên bản in dòng chấm để viết tay.',
    dangTai: 'Đang tải dữ liệu biên bản bàn giao…',
    nhomBenGiao: 'Bên giao',
    nhomLamChung: 'Bên làm chứng (cán bộ khối, xóm, thôn, bản)',
    nhomCanCu: 'Căn cứ quyết định',
    nhomHienVat: 'Hiện vật',
    nhomKhac: 'Mục đích và cam kết',
    hienVatHint: 'Chưa nhập dòng nào thì biên bản in một dòng từ Nội dung, Số lượng và Tổng tiền quy đổi ở trên.',
    hienVatDongN: 'Hiện vật {{n}}',
    themHienVat: 'Thêm hiện vật',
    xoaDong: 'Xoá dòng',
    thanhTien: 'Thành tiền: {{soTien}} đ',
    tongHienVat: 'Tổng giá trị hiện vật: {{soTien}} đ',
    detailEmpty: 'Chưa nhập dữ liệu biên bản bàn giao.',
    nhan: {
      ngay_ban_giao: 'Ngày bàn giao',
      dia_diem: 'Địa điểm bàn giao',
      don_vi_ben_giao: 'Đơn vị bên giao',
      don_vi_ben_giao_placeholder: 'Để trống thì in "Uỷ ban MTTQ Việt Nam" + xã phường của khoản',
      dai_dien_ho_ten: 'Đại diện bên giao — họ tên',
      dai_dien_chuc_vu: 'Đại diện bên giao — chức vụ',
      lam_chung_1_ho_ten: 'Người làm chứng 1 — họ tên',
      lam_chung_1_chuc_vu: 'Người làm chứng 1 — chức vụ',
      lam_chung_2_ho_ten: 'Người làm chứng 2 — họ tên',
      lam_chung_2_chuc_vu: 'Người làm chứng 2 — chức vụ',
      so_quyet_dinh: 'Số quyết định',
      so_quyet_dinh_placeholder: 'VD: 12/QĐ-MTTQ',
      ngay_quyet_dinh: 'Ngày quyết định',
      co_quan_quyet_dinh: 'Cơ quan ban hành quyết định',
      ve_viec: 'Về việc',
      muc_dich: 'Mục đích sử dụng',
      so_thang_duy_tri: 'Thời gian duy trì mô hình (tháng)',
      han_hoan_thanh_nha: 'Hạn hoàn thành xây dựng/sửa chữa nhà',
      ten: 'Tên hiện vật',
      dvt: 'ĐVT',
      so_luong: 'Số lượng',
      don_gia: 'Đơn giá',
      ghi_chu: 'Ghi chú',
    },
  },
  toast: {
    create: 'Đã thêm khoản hỗ trợ',
    update: 'Đã cập nhật khoản hỗ trợ',
    delete: 'Đã xóa {{count}} khoản hỗ trợ',
    statusChange: 'Đã chuyển trạng thái khoản hỗ trợ',
  },
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập.',
  },
  validation: {
    soTienBatBuoc: 'Khoản "Đã nhận" phải có số tiền cụ thể (lớn hơn 0) để cộng tổng ủng hộ.',
    quyDoiBatBuoc: 'Khoản "Đã nhận" có hiện vật phải có tổng tiền quy đổi (lớn hơn 0).',
    nhaTaiTroRequired: 'Nguồn "Ủng hộ trực tiếp" phải chọn nhà tài trợ.',
    noiDungRequired: 'Nhập nội dung hỗ trợ',
    nguoiNhanRequired: 'Nhập họ tên người được hỗ trợ',
    hoNgheoRequired: 'Chọn người được hỗ trợ từ danh sách hộ nghèo',
    namInvalid: 'Năm phải từ 2000 đến 2100',
    linhVucInvalid: 'Chọn lĩnh vực hỗ trợ hợp lệ',
    nguonInvalid: 'Chọn nguồn hợp lệ',
    nguonHoTroInvalid: 'Chọn nguồn hỗ trợ hợp lệ',
    hinhThucInvalid: 'Chọn hình thức hỗ trợ hợp lệ',
    trangThaiInvalid: 'Chọn trạng thái hợp lệ',
    soTienInvalid: 'Số tiền không hợp lệ',
    soTienMin: 'Số tiền không được âm',
    soLuongInvalid: 'Số lượng phải là số nguyên không âm',
  },
};
