export const viNguoiNgheo = {
  tabs: {
    danhSach: 'Danh sách',
    thongKe: 'Thống kê',
  },
  noViewPermission: 'Bạn không có quyền xem module Chương trình vì người nghèo.',
  noViewRowPermission: 'Bạn không có quyền xem bản ghi này.',
  noXaPhuongScopePermission: 'Bạn chỉ được nhập khoản hỗ trợ thuộc xã/phường của mình.',
  listLoadErrorHint: 'Không tải được danh sách. Thử tải lại.',
  empty: 'Chưa có khoản hỗ trợ nào',
  exportFileName: 'Chuong_Trinh_Vi_Nguoi_Ngheo',
  deleteTitle: 'Xóa khoản hỗ trợ',
  deleteMessage: 'Bạn có chắc muốn xóa khoản hỗ trợ này? Hành động không hoàn tác.',
  bulkDeleteTitle: 'Xóa nhiều khoản hỗ trợ',
  bulkDeleteMessage: 'Bạn có chắc muốn xóa {{count}} khoản hỗ trợ đã chọn? Hành động không hoàn tác.',
  detailTitle: 'Chi tiết khoản hỗ trợ',
  detail: {
    systemInfo: 'Thông tin hệ thống',
    actionChangeStatus: 'Chuyển trạng thái',
    lienKetHoNgheo: 'Liên kết hộ nghèo',
    daLienKet: 'Đã liên kết',
    chuaLienKet: 'Nhập tay (không liên kết)',
  },
  statusChangeModal: {
    title: 'Chuyển trạng thái',
    subtitle: 'Đổi trạng thái khoản hỗ trợ và ghi lý do',
    section: 'Trạng thái mới',
    save: 'Chuyển trạng thái',
    lyDoLabel: 'Lý do / ghi chú',
    lyDoPlaceholder: 'Vì sao chuyển sang trạng thái này?',
    hint: 'Mỗi lần đổi đều được lưu vết: từ trạng thái nào sang trạng thái nào, ai đổi, lúc nào.',
  },
  store: {
    namCol: 'Năm',
    noiDungCol: 'Nội dung hỗ trợ',
    linhVucCol: 'Lĩnh vực hỗ trợ',
    nguonCol: 'Nguồn',
    nguonHoTroCol: 'Nguồn hỗ trợ',
    nguoiNhanCol: 'Họ và tên người được hỗ trợ',
    xaPhuongCol: 'Xã phường',
    khoiXomCol: 'Khối xóm',
    doiTuongCol: 'Đối tượng',
    hinhThucCol: 'Hình thức hỗ trợ',
    soTienCol: 'Số tiền hỗ trợ',
    trangThaiCol: 'Trạng thái',
    ngayTrangThaiCol: 'Ngày cập nhật trạng thái',
    donViHoTroCol: 'Đơn vị, cá nhân hỗ trợ',
    ghiChuCol: 'Ghi chú',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  form: {
    createSubtitle: 'Thêm khoản hỗ trợ',
    editSubtitle: 'Cập nhật khoản hỗ trợ',
    sectionNguoiNhan: 'Người được hỗ trợ',
    sectionHoTro: 'Nội dung & nguồn hỗ trợ',
    sectionTrangThai: 'Trạng thái',
    hoNgheoLabel: 'Chọn từ danh sách hộ nghèo',
    hoNgheoHint: 'Chọn hộ để tự điền họ tên, xã phường, khối xóm, đối tượng. Không có trong danh sách thì bỏ trống và nhập tay.',
    hoNgheoPlaceholder: 'Tìm theo tên hoặc số căn cước…',
    donViHoTroPlaceholder: 'Chọn từ danh mục Đơn vị cứu trợ',
    soTienPlaceholder: 'Để trống nếu chỉ hỗ trợ bằng quà',
    ghiChuHint: 'Ghi chú cũng được lưu làm lý do cho lần đổi trạng thái này.',
  },
  toast: {
    create: 'Đã thêm khoản hỗ trợ',
    update: 'Đã cập nhật khoản hỗ trợ',
    delete: 'Đã xóa {{count}} khoản hỗ trợ',
    statusChange: 'Đã chuyển trạng thái khoản hỗ trợ',
  },
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập.',
  },
  validation: {
    noiDungRequired: 'Nhập nội dung hỗ trợ',
    nguoiNhanRequired: 'Nhập họ tên người được hỗ trợ',
    namInvalid: 'Năm phải từ 2000 đến 2100',
    linhVucInvalid: 'Chọn lĩnh vực hỗ trợ hợp lệ',
    nguonInvalid: 'Chọn nguồn hợp lệ',
    nguonHoTroInvalid: 'Chọn nguồn hỗ trợ hợp lệ',
    hinhThucInvalid: 'Chọn hình thức hỗ trợ hợp lệ',
    trangThaiInvalid: 'Chọn trạng thái hợp lệ',
    soTienInvalid: 'Số tiền không hợp lệ',
    soTienMin: 'Số tiền không được âm',
  },
};
