/** Chữ giao diện dùng chung (nav, trang, lỗi, …) */
export const ui = {
  "nav": {
    "changePassword": {
      "title": "Đổi mật khẩu",
      "description": "Nhập mật khẩu hiện tại và mật khẩu mới để bảo mật tài khoản.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "newPasswordHint": "Ít nhất 6 ký tự.",
      "submit": "Cập nhật mật khẩu",
      "success": "Đổi mật khẩu thành công.",
      "errorCurrentRequired": "Vui lòng nhập mật khẩu hiện tại.",
      "errorNewMin": "Mật khẩu mới phải có ít nhất 6 ký tự.",
      "errorConfirmMismatch": "Xác nhận mật khẩu không khớp.",
      "errorWrongCurrent": "Mật khẩu hiện tại không đúng.",
      "errorSession": "Phiên đăng nhập không hợp lệ. Vui lòng đăng nhập lại.",
      "errorNotConfigured": "Chưa cấu hình xác thực. Liên hệ quản trị viên.",
      "errorGeneric": "Không thể đổi mật khẩu. Vui lòng thử lại."
    },
    "home": "Trang chủ",
    "back": "Quay lại",
    "licenseInfo": "Thông tin bản quyền",
    "matTranToQuoc": "Mặt trận tổ quốc",
    "quanLyVietBai": "Quản lý viết bài",
    "quanLyGiaoViec": "Quản lý giao việc",
    "phanBienXaHoi": "Kiểm tra, giám sát, phản biện xã hội",
    "danTocTonGiao": "Dân tộc, tôn giáo",
    "trangThongTinKhac": "Trang thông tin khác",
    "system": "Hệ thống",
    "skipToMain": "Chuyển đến nội dung chính",
    "collapseSidebar": "Thu gọn sidebar",
    "expandSidebar": "Mở rộng sidebar",
    "closeOverlay": "Đóng overlay",
    "notification": "Thông báo",
    "userMenu": "Menu người dùng",
    "guestUser": "Khách",
    "roleAdmin": "Quản trị viên",
    "roleMember": "Thành viên",
    "userAvatarAlt": "Ảnh đại diện",
    "profile": "Hồ sơ cá nhân",
    "logout": "Đăng xuất",
    "logoutConfirmTitle": "Xác nhận đăng xuất",
    "logoutConfirmMessage": "Bạn có chắc chắn muốn kết thúc phiên làm việc?",
    "logoutCancel": "Hủy bỏ",
    "defaultAppDescription": "Hệ thống nền tảng số",
    "mainNav": "Điều hướng chính",
    "changePasswordLabel": "Đổi mật khẩu",
    "commandPalette": {
      "title": "Điều hướng nhanh",
      "placeholder": "Tìm trang hoặc đường dẫn…",
      "empty": "Không có kết quả",
      "hint": "Esc đóng · Enter mở · ↑↓ chọn",
      "groupGeneral": "Chung",
      "groupSystem": "Hệ thống",
      "groupAccount": "Tài khoản",
      "groupArticleMgmt": "Quản lý viết bài",
      "groupTaskMgmt": "Quản lý giao việc",
      "groupMatTranToQuoc": "Mặt trận tổ quốc",
      "groupPhanBienXaHoi": "Kiểm tra, giám sát, phản biện xã hội"
    }
  },
  "shared": {
    "export": {
      "title": "Xuất dữ liệu",
      "format": "Định dạng",
      "scope": "Phạm vi",
      "scopeAll": "Tất cả",
      "scopeCurrentPage": "Trang hiện tại",
      "scopeSelected": "Đã chọn",
      "rows": "dòng",
      "selectColumns": "Chọn cột xuất",
      "deselectAll": "Bỏ chọn hết",
      "selectAll": "Chọn tất cả",
      "pdfHeader": "Xuất ngày: {{date}} | {{count}} bản ghi",
      "exporting": "Đang xuất...",
      "exportRows": "Xuất {{count}} dòng"
    },
    "import": {
      "title": "Import dữ liệu",
      "subtitle": "Tải lên file Excel hoặc CSV",
      "dropHere": "Kéo thả file vào đây",
      "orClickToSelect": "hoặc nhấn để chọn file (.xlsx, .xls, .csv)",
      "downloadTemplate": "Tải file mẫu (.xlsx)",
      "rowsRead": "Đã đọc {{count}} dòng dữ liệu",
      "systemColumn": "Cột hệ thống",
      "fileColumn": "Cột trong file",
      "skipColumn": "-- Bỏ qua --",
      "preview": "Xem trước (5 dòng đầu)",
      "success": "Import thành công!",
      "successCount": "{{count}} bản ghi đã được nhập",
      "error": "Không import được",
      "noDataOrHeader": "File không có dữ liệu hoặc thiếu header",
      "cannotReadFile": "Không thể đọc file. Vui lòng kiểm tra định dạng.",
      "missingRequiredColumns": "Chưa mapping cột bắt buộc: {{columns}}",
      "rowEmptyField": "Dòng {{row}}: \"{{column}}\" không được để trống",
      "importError": "Lỗi khi import dữ liệu",
      "importRows": "Import {{count}} dòng",
      "errorColumnLabel": "Lỗi",
      "downloadErrors": "Tải {{count}} dòng lỗi (.xlsx)"
    },
    "empty": {
      "title": "Không có dữ liệu",
      "description": "Chưa có dữ liệu. Thử thêm bản ghi hoặc điều chỉnh bộ lọc."
    },
    "error": {
      "title": "Đã xảy ra lỗi",
      "message": "Không thể tải dữ liệu. Vui lòng thử lại.",
      "retry": "Tải lại",
      "backHome": "Về trang chủ",
      "reloading": "Đang tải lại...",
      "network": "Lỗi kết nối mạng. Kiểm tra internet và thử lại.",
      "unauthorized": "Phiên đăng nhập hết hạn hoặc không có quyền truy cập.",
      "forbidden": "Bạn không có quyền thực hiện thao tác này.",
      "notFound": "Không tìm thấy tài nguyên.",
      "server": "Lỗi máy chủ. Vui lòng thử lại sau.",
      "timeout": "Hết thời gian chờ. Vui lòng thử lại.",
      "unknown": "Đã xảy ra lỗi không xác định. Vui lòng thử lại.",
      "beforeInitialization": "Lỗi khởi tạo: không thể truy cập trước khi khởi tạo. Vui lòng tải lại trang.",
      "notDefined": "Tham chiếu lỗi: thành phần chưa được định nghĩa. Vui lòng tải lại trang.",
      "notFunction": "Lỗi gọi hàm: giá trị không phải là hàm. Vui lòng tải lại trang.",
      "chunkLoad": "Không tải được phần mềm. Vui lòng tải lại trang.",
      "devDetail": "Chi tiết kỹ thuật (chế độ phát triển):"
    },
    "mobileFilter": {
      "title": "Bộ lọc",
      "searchPlaceholder": "Tìm {{label}}...",
      "selectAll": "Chọn tất cả",
      "notFound": "Không tìm thấy",
      "clear": "Xóa bộ lọc"
    },
    "mobileActions": {
      "title": "Thao tác"
    }
  },
  "page": {
    "home": {
      "greeting": "Xin chào,",
      "greetingMorning": "Chào buổi sáng",
      "greetingAfternoon": "Chào buổi chiều",
      "greetingEvening": "Chào buổi tối",
      "adminFallback": "Quản trị viên",
      "systemModuleDesc": "Cấu hình, phân quyền và nhân sự.",
      "licenseInfoDesc": "Quản lý sở hữu trí tuệ và thông tin nhà phát triển.",
      "placeholderModuleDesc": "Nội dung đang được cập nhật.",
      "taskMgmtModuleDesc": "Công việc, giao việc và báo cáo tiến độ.",
      "matTranModuleDesc": "Tập huấn, khen thưởng, ủy viên ủy ban và thiết lập cán bộ."
    },
    "license": {
      "title": "Thông tin Bản quyền",
      "subtitle": "Quản lý sở hữu trí tuệ và thông tin nhà phát triển",
      "unitTitle": "Đơn vị xây dựng & Phát triển",
      "companyName": "Tên công ty / Tổ chức",
      "representative": "Người đại diện",
      "taxCode": "Mã số thuế",
      "address": "Địa chỉ trụ sở",
      "rightsTitle": "Quyền hạn & Bảo mật",
      "rightsIntro": "Phần mềm này cùng toàn bộ mã nguồn, giao diện và cơ sở dữ liệu thuộc quyền sở hữu trí tuệ duy nhất của Công ty ABC. Mọi hành vi sao chép, chỉnh sửa hoặc phân phối lại mà không có sự đồng ý bằng văn bản đều là vi phạm pháp luật.",
      "version": "Phiên bản hiện tại",
      "licenseDate": "Ngày cấp phép",
      "status": "Trạng thái",
      "statusRegistered": "Đã đăng ký bản quyền tại Cục Sở hữu trí tuệ.",
      "communityLinks": "Liên kết cộng đồng",
      "website": "Website chính thức",
      "fanpage": "Fanpage Facebook",
      "communityGroup": "Group Cộng đồng",
      "zaloGroup": "Cộng đồng Zalo",
      "tiktok": "Kênh TikTok",
      "supportTitle": "Hỗ trợ kỹ thuật?",
      "supportDesc": "Gặp sự cố hoặc cần tư vấn thêm về giải pháp?",
      "contactHotline": "Liên hệ Hotline",
      "footer": "© 2024 - 2026 Bản quyền thuộc về Công ty ABC. Được bảo vệ bởi hệ thống bảo vệ bản quyền số quốc tế.",
      "technicalContact": "Liên hệ Kỹ thuật",
      "businessContact": "Liên hệ Kinh doanh",
      "contactName": "Tên",
      "contactPosition": "Chức vụ",
      "contactPhone": "Số điện thoại",
      "contactEmail": "Email"
    },
    "placeholder": {
      "backToHome": "Quay lại trang chủ",
      "backToSubmenu": "Quay lại",
      "moduleComingSoon": "Chức năng đang được phát triển.",
      "title": "Module đang được phát triển",
      "description": "Chúng tôi đang nỗ lực hoàn thiện tính năng này để mang lại trải nghiệm tốt nhất cho bạn. Vui lòng quay lại sau!",
      "descriptionWithModule": "Tính năng {{name}} đang được hoàn thiện. Vui lòng quay lại sau!",
      "badgeComingSoon": "Sắp ra mắt",
      "refreshPage": "Làm mới trang",
      "expectedCompletion": "Dự kiến hoàn thành: Quý 2 - 2026",
      "exampleDoc": "Công văn",
      "exampleContract": "Hợp đồng",
      "exampleRecruit": "Tuyển dụng",
      "exampleAttendance": "Chấm công",
      "exampleCampaign": "Chiến dịch",
      "exampleAccounting": "Kế toán",
      "exampleOrder": "Đặt hàng",
      "exampleInventory": "Tồn kho"
    },
    "login": {
      "emailRequired": "Vui lòng nhập email",
      "emailInvalid": "Email không hợp lệ",
      "usernameRequired": "Vui lòng nhập tên tài khoản",
      "usernameMin": "Tên tài khoản phải có ít nhất 2 ký tự",
      "username": "Tên tài khoản",
      "usernamePlaceholder": "VD: admin",
      "passwordMin": "Mật khẩu phải có ít nhất 6 ký tự",
      "mockUserName": "Lê Minh Công",
      "loginSuccess": "Đăng nhập thành công!",
      "googleUser": "Google User",
      "googleSuccess": "Đăng nhập bằng Google thành công!",
      "heading": "Quản lý doanh nghiệp",
      "headingHighlight": "thông minh & hiệu quả",
      "description": "Nền tảng tích hợp AI giúp tối ưu hóa quy trình nhân sự, tài chính và vận hành hệ thống của bạn trong một giao diện duy nhất.",
      "feature1": "Tích hợp AI Assistant mạnh mẽ",
      "feature2": "Dashboard phân tích dữ liệu Realtime",
      "feature3": "Bảo mật dữ liệu tiêu chuẩn Enterprise",
      "welcome": "Mặt trận số Nghệ an",
      "welcomeDesc": "Nhập tên tài khoản và mật khẩu để truy cập.",
      "email": "Email",
      "emailPlaceholder": "name@company.com",
      "password": "Mật khẩu",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "forgotPassword": "Quên mật khẩu?",
      "rememberMe": "Ghi nhớ đăng nhập",
      "loginButton": "Đăng nhập",
      "orLoginWith": "Hoặc đăng nhập bằng",
      "forgotAccountLabel": "Tên tài khoản",
      "forgotAccountPlaceholder": "Nhập tên tài khoản đã đăng ký",
      "copyright": "© 2024",
      "companyFallback": "MTTQVN",
      "legal": "Bảo mật • Điều khoản sử dụng",
      "forgotPasswordTitle": "Quên mật khẩu",
      "forgotPasswordDesc": "Nhập tên tài khoản đã đăng ký, chúng tôi sẽ gửi hướng dẫn khôi phục mật khẩu.",
      "sendRecovery": "Gửi link khôi phục",
      "recoverySent": "Đã gửi thông tin khôi phục về email của bạn. Vui lòng kiểm tra hộp thư.",
      "recoverySentTitle": "Đã gửi"
    },
    "profile": {
      "nameMin": "Tên phải có ít nhất 2 ký tự",
      "emailInvalid": "Địa chỉ email không hợp lệ",
      "bioMax": "Giới thiệu không được quá 160 ký tự",
      "defaultBio": "Lập trình viên Frontend | Đam mê công nghệ",
      "updateSuccess": "Cập nhật hồ sơ thành công!",
      "userNotFound": "Không tìm thấy thông tin người dùng.",
      "title": "Hồ sơ cá nhân",
      "description": "Quản lý thông tin tài khoản và cài đặt của bạn.",
      "activeStatus": "Đang hoạt động",
      "roleUser": "User",
      "joinedAt": "Tham gia",
      "verified": "Tài khoản xác thực",
      "avatarAlt": "Avatar của {{name}}",
      "avatarAltFallback": "Avatar người dùng",
      "basicInfo": "Thông tin cơ bản",
      "fullName": "Họ và tên",
      "namePlaceholder": "Nhập tên của bạn",
      "email": "Email",
      "emailPlaceholder": "email@example.com",
      "bio": "Giới thiệu",
      "bioPlaceholder": "Mô tả ngắn về bản thân...",
      "bioHint": "Tối đa 160 ký tự",
      "settingsSection": "Cài đặt",
      "emailNotification": "Thông báo qua Email",
      "emailNotificationDesc": "Nhận cập nhật về hoạt động tài khoản và tin tức mới nhất.",
      "viewOnlyBanner": "Bạn chỉ có quyền xem hồ sơ.",
      "changeAvatar": "Đổi ảnh đại diện",
      "changePassword": "Đổi mật khẩu",
      "changePasswordTitle": "Đổi mật khẩu",
      "changePasswordDesc": "Nhập mật khẩu hiện tại và mật khẩu mới.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "passwordPlaceholder": "••••••••",
      "avatarModalTitle": "Đổi ảnh đại diện",
      "avatarModalHint": "Kéo thả hoặc chọn ảnh. PNG, JPG, tối đa 2MB.",
      "emptyField": "Chưa cập nhật",
      "detailSectionsTitle": "Thông tin chi tiết",
      "comingSoon": "Sắp ra mắt",
      "comingSoonDesc": "Tính năng đang được phát triển.",
      "avatarUpdateSuccess": "Đã cập nhật ảnh đại diện."
    },
    "systemDashboard": {
      "orgChartGroup": "Sơ đồ",
      "employee": "Nhân viên",
      "employeeDesc": "Hồ sơ và thông tin nhân sự.",
      "department": "Phòng ban",
      "departmentDesc": "Cơ cấu tổ chức đơn vị.",
      "position": "Chức vụ",
      "positionDesc": "Quản lý các vị trí công việc.",
      "securityGroup": "Bảo mật & Cấu hình",
      "companyInfo": "Thông tin tổ chức",
      "companyInfoDesc": "Logo, tên ứng dụng MTTQVN và thông tin liên hệ hiển thị trên hệ thống.",
      "permission": "Phân quyền",
      "permissionDesc": "Vai trò và quyền hạn.",
      "provinceList": "Tỉnh thành – xã phường",
      "provinceListDesc": "Danh mục tỉnh/thành và xã/phường: import, xuất, phân quyền theo module.",
      "backToSystem": "Quay lại Hệ thống"
    },
    "taskDashboard": {
      "groupMain": "Giao việc & báo cáo",
      "yearProgram": "Chương trình BTT",
      "yearProgramDesc": "Kế hoạch và chương trình công việc theo năm (đang phát triển).",
      "tasks": "Công việc",
      "tasksDesc": "Danh sách, trạng thái và chi tiết công việc được giao.",
      "taskReport": "Báo cáo công việc",
      "taskReportDesc": "Thống kê theo thời gian, người thực hiện và trạng thái.",
      "backToParent": "Quay lại Quản lý giao việc"
    },
    "matTranDashboard": {
      "groupTrainingReward": "Tập huấn & Khen thưởng",
      "groupCommittee": "Ủy viên ủy ban",
      "groupReliefWarehouse": "Kho cứu trợ",
      "groupSalaryManagement": "Quản lý lương",
      "groupOtherSettings": "Tổ chức cán bộ",
      "trainingList": "Tập huấn",
      "trainingListDesc": "Theo dõi các đợt tập huấn và danh sách tham gia.",
      "rewardList": "Khen thưởng",
      "rewardListDesc": "Danh mục khen thưởng đã duyệt và chi tiết.",
      "term": "Nhiệm kỳ",
      "termDesc": "Các nhiệm kỳ ủy ban Mặt trận Tổ quốc.",
      "session": "Kỳ họp",
      "sessionDesc": "Lịch và nội dung các kỳ họp ủy ban.",
      "committeeMembers": "Ủy viên ủy ban",
      "committeeMembersDesc": "Hồ sơ và danh sách ủy viên.",
      "committeeMemberStatsReport": "Báo cáo ủy viên",
      "committeeMemberStatsReportDesc": "Thống kê, lọc và tra cứu ủy viên theo nhiệm kỳ, đơn vị và tiêu chí khác.",
      "reliefCampaign": "Đợt cứu trợ",
      "reliefCampaignDesc": "Quản lý các đợt tiếp nhận, phân bổ và theo dõi cứu trợ.",
      "reliefGoods": "Hàng hóa",
      "reliefGoodsDesc": "Danh mục hàng hóa, vật tư và đơn vị tính phục vụ cứu trợ.",
      "reliefStockTransactions": "Nhập xuất kho",
      "reliefStockTransactionsDesc": "Ghi nhận phiếu nhập, phiếu xuất và luân chuyển hàng cứu trợ.",
      "reliefInventory": "Tồn kho",
      "reliefInventoryDesc": "Theo dõi số lượng tồn, giá trị và tình trạng hàng hóa trong kho.",
      "reliefWarehouseList": "Danh sách kho",
      "reliefWarehouseListDesc": "Quản lý danh sách kho, địa điểm lưu trữ và thông tin phụ trách.",
      "reliefSupportUnits": "Đơn vị hỗ trợ",
      "reliefSupportUnitsDesc": "Danh sách tổ chức và cá nhân tham gia quyên góp, hỗ trợ cứu trợ.",
      "reliefSupportReport": "Báo cáo hỗ trợ",
      "reliefSupportReportDesc": "Tổng hợp nhập – xuất cứu trợ theo đơn vị hỗ trợ, đợt cứu trợ và hàng hóa.",
      "officerList": "Danh sách cán bộ",
      "officerListDesc": "Cán bộ thuộc phạm vi thiết lập Mặt trận Tổ quốc.",
      "officerStatsReport": "Báo cáo cán bộ",
      "officerStatsReportDesc": "Thống kê, lọc và tra cứu hồ sơ cán bộ theo nhiều tiêu chí.",
      "setupSettings": "Thiết lập cài đặt",
      "setupSettingsDesc": "Cấu hình và tùy chọn chung cho phạm vi Mặt trận Tổ quốc.",
      "salaryIncreaseList": "Danh sách tăng lương",
      "salaryIncreaseListDesc": "Theo dõi lịch sử, kế hoạch năm và thống kê tăng lương cán bộ.",
      "salarySetup": "Thiết lập lương",
      "salarySetupDesc": "Cấu hình ngạch lương, bậc B1–B9 và mức lương cơ sở.",
      "backToParent": "Quay lại Mặt trận tổ quốc"
    },
    "phanBienXaHoiDashboard": {
      "groupMain": "Kiểm tra, giám sát, phản biện xã hội",
      "thucHien": "Kiểm tra, GS và PBXH",
      "thucHienDesc": "Ghi nhận và theo dõi các hoạt động phản biện xã hội.",
      "thietLapDanhMuc": "Thiết lập danh mục",
      "thietLapDanhMucDesc": "Cấu hình danh mục và thiết lập cho module phản biện xã hội.",
      "thongKe": "Thống kê kiểm tra, GS và PBXH",
      "thongKeDesc": "Báo cáo và thống kê kết quả phản biện xã hội.",
      "backToParent": "Quay lại Kiểm tra, giám sát, phản biện xã hội"
    },
    "pbxhThietLap": {
      "tabDoiTuong": "Đối tượng KT, GS, PBXH",
      "tabDonViChuTri": "Đơn vị chủ trì",
      "tabHinhThuc": "Hình thức thực hiện",
      "addItem": "Thêm mục",
      "editItem": "Sửa mục",
      "formCreateSubtitle": "Thêm danh mục",
      "formEditSubtitle": "Cập nhật danh mục",
      "detailTitle": "Chi tiết danh mục",
      "empty": "Chưa có mục danh mục",
      "deleteTitle": "Xóa mục",
      "deleteMessage": "Bạn có chắc muốn xóa mục này? Hành động không hoàn tác.",
      "bulkDeleteTitle": "Xóa nhiều mục",
      "bulkDeleteMessage": "Bạn có chắc muốn xóa {{count}} mục đã chọn? Hành động không hoàn tác.",
      "filterMoTaChipPlaceholder": "Mô tả",
      "filterMoTaHas": "Có mô tả",
      "filterMoTaEmpty": "Không mô tả",
      "toast": {
        "create": "Đã thêm mục",
        "update": "Đã cập nhật mục",
        "delete": "Đã xóa {{count}} mục"
      },
      "validation": {
        "tenRequired": "Nhập tên"
      }
    },
    "danTocTonGiaoDashboard": {
      "groupThamHoi": "Thăm hỏi",
      "groupThongTin": "Thông tin",
      "dipThamHoi": "Dịp thăm hỏi",
      "dipThamHoiDesc": "Quản lý các dịp thăm hỏi và theo dõi tiến độ thăm hỏi tổ chức, cá nhân.",
      "thamHoiToChuc": "Thăm hỏi tổ chức",
      "thamHoiToChucDesc": "Ghi nhận và theo dõi các lượt thăm hỏi tổ chức dân tộc, tôn giáo.",
      "thamHoiCaNhan": "Thăm hỏi cá nhân",
      "thamHoiCaNhanDesc": "Ghi nhận và theo dõi các lượt thăm hỏi cá nhân tiêu biểu.",
      "thongKeThamHoi": "Thống kê thăm hỏi",
      "thongKeThamHoiDesc": "Tổng hợp thống kê lượt thăm hỏi tổ chức và cá nhân.",
      "thongTinToChucQuanTrong": "Thông tin tổ chức tôn giáo",
      "thongTinToChucQuanTrongDesc": "Danh mục và hồ sơ các tổ chức tôn giáo.",
      "thongTinCaNhanTieuBieu": "Thông tin cá nhân tiêu biểu",
      "thongTinCaNhanTieuBieuDesc": "Danh sách cá nhân tiêu biểu trong cộng đồng dân tộc, tôn giáo.",
      "thongKeToChucCaNhan": "Thống kê tổ chức, cá nhân",
      "thongKeToChucCaNhanDesc": "Tổng hợp thống kê hồ sơ tổ chức tôn giáo và cá nhân tiêu biểu.",
      "backToParent": "Quay lại Dân tộc, tôn giáo"
    },
    "matTranThietLap": {
      "tabCapQuanLy": "Cấp quản lý",
      "tabToChuc": "Tổ chức",
      "tabDanToc": "Dân tộc",
      "tabTrinhDo": "Trình độ",
      "tabLyLuanChinhTri": "Lý luận chính trị",
      "tabTrangThai": "Trạng thái",
      "addItem": "Thêm mục",
      "editItem": "Sửa mục",
      "formCreateSubtitle": "Thêm danh mục",
      "formEditSubtitle": "Cập nhật danh mục",
      "detailTitle": "Chi tiết thiết lập",
      "empty": "Chưa có bản ghi",
      "deleteTitle": "Xóa mục",
      "deleteMessage": "Bạn có chắc muốn xóa mục này? Hành động không hoàn tác.",
      "bulkDeleteTitle": "Xóa nhiều mục",
      "bulkDeleteMessage": "Bạn có chắc muốn xóa {{count}} mục đã chọn? Hành động không hoàn tác.",
      "toast": {
        "create": "Đã thêm mục",
        "update": "Đã cập nhật mục",
        "delete": "Đã xóa {{count}} mục"
      },
      "service": {
        "notFound": "Không tìm thấy bản ghi thiết lập"
      },
      "validation": {
        "tenRequired": "Nhập tên"
      },
      "filterMoTaChipPlaceholder": "Mô tả",
      "filterMoTaHas": "Có mô tả",
      "filterMoTaEmpty": "Không mô tả",
      "noViewPermission": "Bạn không có quyền xem module Thiết lập cài đặt."
    },
    "articleDashboard": {
      "groupMain": "Nội dung & cấu hình",
      "articles": "Bài viết",
      "articlesDesc": "Danh sách, soạn thảo và trạng thái bài viết.",
      "commission": "Nhuận bút",
      "commissionDesc": "Theo dõi nhuận bút theo bài và tác giả.",
      "statsReport": "BC thống kê bài viết",
      "statsReportDesc": "Báo cáo và thống kê hiệu quả nội dung.",
      "settings": "Thiết lập bài viết",
      "settingsDesc": "Danh mục, template và quy tắc đăng bài.",
      "backToParent": "Quay lại Quản lý viết bài"
    },
    "externalLinksDashboard": {
      "groupMain": "Liên kết truy cập",
      "mttqNews": "Trang tin MTTQ",
      "mttqNewsDesc": "Cổng thông tin điện tử Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh Nghệ An.",
      "zaloOa": "Trang thông tin OA",
      "zaloOaDesc": "Cổng quản lý tài khoản Zalo OA (tài khoản chính thức) và tương tác với người dùng Zalo.",
      "matTranSo": "Mặt trận số",
      "matTranSoDesc": "Hệ thống các nền tảng số — cổng đăng nhập Mặt trận số.",
      "quanLyVanBan": "Quản lý văn bản",
      "quanLyVanBanDesc": "Hệ thống thông tin điều hành tác nghiệp — quản lý văn bản và điều hành.",
      "lichCongTacBanTt": "Lịch công tác ban TT",
      "lichCongTacBanTtDesc": "Lịch công tác Ban Thường trực — tra cứu và theo dõi lịch làm việc trên hệ thống VNPT iOffice."
    },
    "articleSettings": {
      "tabTheLoai": "Thể loại",
      "tabThietLapKhac": "Thiết lập khác",
      "sectionTrangDang": "Trang đăng",
      "sectionNguonDang": "Nguồn đăng",
      "addTheLoai": "Thêm thể loại",
      "addKhac": "Thêm mục",
      "editTheLoai": "Sửa thể loại",
      "editKhac": "Sửa mục",
      "colTenTheLoai": "Tên thể loại",
      "colMoTa": "Mô tả",
      "colDonGia": "Đơn giá (VNĐ)",
      "colTgTao": "Ngày tạo",
      "colTgCapNhat": "Ngày cập nhật",
      "colTen": "Tên",
      "colThuTu": "Thứ tự",
      "emptyTheLoai": "Chưa có thể loại",
      "emptyKhac": "Chưa có bản ghi",
      "deleteConfirm": "Xóa {{count}} mục đã chọn?",
      "deleteOneConfirm": "Xóa mục này?",
      "deleteTheLoaiTitle": "Xóa thể loại",
      "deleteTheLoaiMessage": "Bạn có chắc muốn xóa thể loại này? Hành động không hoàn tác.",
      "deleteKhacTitle": "Xóa thiết lập",
      "deleteKhacMessage": "Bạn có chắc muốn xóa mục này?",
      "formDonGia": "Đơn giá (VNĐ)",
      "formTenTheLoai": "Tên thể loại",
      "formTen": "Tên hiển thị",
      "formThuTu": "Thứ tự",
      "service": {
        "notFoundTheLoai": "Không tìm thấy thể loại",
        "notFoundKhac": "Không tìm thấy bản ghi thiết lập"
      },
      "validation": {
        "tenTheLoaiRequired": "Nhập tên thể loại",
        "donGiaMin": "Đơn giá không âm",
        "tenRequired": "Nhập tên"
      },
      "toast": {
        "theLoaiCreate": "Đã thêm thể loại",
        "theLoaiUpdate": "Đã cập nhật thể loại",
        "theLoaiDelete": "Đã xóa {{count}} thể loại",
        "khacCreate": "Đã thêm thiết lập",
        "khacUpdate": "Đã cập nhật thiết lập",
        "khacDelete": "Đã xóa {{count}} mục"
      },
      "detailTheLoaiTitle": "Chi tiết thể loại",
      "detailTheLoaiSubtitle": "Thể loại bài viết",
      "detailKhacTitle": "Chi tiết thiết lập",
      "detailBasic": "Thông tin chính",
      "detailSystem": "Thông tin hệ thống",
      "bulkDeleteTheLoaiTitle": "Xóa nhiều thể loại",
      "bulkDeleteTheLoaiMessage": "Bạn có chắc muốn xóa {{count}} thể loại đã chọn? Hành động không hoàn tác.",
      "bulkDeleteKhacTitle": "Xóa nhiều thiết lập",
      "bulkDeleteKhacMessage": "Bạn có chắc muốn xóa {{count}} mục thiết lập đã chọn? Hành động không hoàn tác.",
      "noExportData": "Không có dữ liệu để xuất",
      "formTheLoaiCreateSubtitle": "Thêm thể loại mới cho hệ thống",
      "formTheLoaiEditSubtitle": "Cập nhật thể loại",
      "formKhacCreateSubtitle": "Thêm mục thiết lập mới",
      "formKhacEditSubtitle": "Cập nhật thiết lập",
      "filterDonGiaChipPlaceholder": "Đơn giá",
      "filterDonGiaFree": "Miễn phí (0 ₫)",
      "filterDonGiaPaid": "Có phí",
      "filterMoTaChipPlaceholder": "Mô tả",
      "filterMoTaHas": "Có mô tả",
      "filterMoTaEmpty": "Không mô tả",
      "noViewPermission": "Bạn không có quyền xem module Thiết lập bài viết."
    }
  },
  "notification": {
    "title": "Thông báo",
    "markAllRead": "Đánh dấu tất cả đã đọc",
    "clearAll": "Xóa tất cả",
    "empty": "Chưa có thông báo",
    "emptyHint": "Các thông báo mới sẽ hiển thị tại đây.",
    "remove": "Xóa thông báo",
    "viewAll": "Xem tất cả thông báo",
    "collapse": "Thu gọn",
    "demoTooltip": "Thông báo · Tính năng đang phát triển",
    "demoBannerTitle": "Tính năng đang phát triển",
    "demoBannerDesc": "Hệ thống thông báo thời gian thực đang được hoàn thiện. Vui lòng quay lại sau."
  },
  "breadcrumb": {
    "label": "Đường dẫn",
    "home": "Trang chủ",
    "licenseInfo": "Thông tin bản quyền",
    "goHome": "Về trang chủ",
    "matTranToQuoc": "Mặt trận tổ quốc",
    "quanLyVietBai": "Quản lý viết bài",
    "quanLyGiaoViec": "Quản lý giao việc",
    "phanBienXaHoi": "Kiểm tra, giám sát, phản biện xã hội",
    "danTocTonGiao": "Dân tộc, tôn giáo",
    "trangThongTinKhac": "Trang thông tin khác",
    "systemAdmin": "Hệ thống",
    "employee": "Nhân sự",
    "department": "Phòng ban",
    "position": "Chức vụ",
    "companyInfo": "Thông tin tổ chức",
    "permission": "Phân quyền",
    "provinceList": "Tỉnh thành – xã phường",
    "profile": "Hồ sơ cá nhân",
    "articleArticles": "Bài viết",
    "articleCommission": "Nhuận bút",
    "articleStats": "BC thống kê bài viết",
    "articleSettings": "Thiết lập bài viết",
    "taskChuongTrinhNam": "Chương trình BTT",
    "taskCongViec": "Công việc",
    "taskBaoCaoCongViec": "Báo cáo công việc",
    "matTranTrainingList": "Tập huấn",
    "matTranRewardList": "Khen thưởng",
    "matTranTerm": "Nhiệm kỳ",
    "matTranNhiemKyDiemDanhMatrix": "Điểm danh ma trận",
    "matTranSession": "Kỳ họp",
    "matTranCommitteeMembers": "Ủy viên ủy ban",
    "matTranCommitteeMemberStats": "Báo cáo ủy viên",
    "matTranReliefCampaign": "Đợt cứu trợ",
    "matTranReliefGoods": "Hàng hóa",
    "matTranReliefStockTransactions": "Nhập xuất kho",
    "matTranReliefInventory": "Tồn kho",
    "matTranReliefWarehouseList": "Danh sách kho",
    "matTranReliefSupportUnits": "Đơn vị hỗ trợ",
    "matTranReliefSupportReport": "Báo cáo hỗ trợ",
    "matTranOfficerList": "Danh sách cán bộ",
    "matTranOfficerStats": "Báo cáo cán bộ",
    "matTranSetupSettings": "Thiết lập cài đặt",
    "matTranSalaryIncreaseList": "Danh sách tăng lương",
    "matTranSalarySetup": "Thiết lập lương"
  },
  "clock": {
    "sunday": "Chủ nhật",
    "monday": "Thứ 2",
    "tuesday": "Thứ 3",
    "wednesday": "Thứ 4",
    "thursday": "Thứ 5",
    "friday": "Thứ 6",
    "saturday": "Thứ 7"
  },
  "common": {
    "save": "Lưu",
    "required": "Trường bắt buộc",
    "saving": "Đang lưu...",
    "cancel": "Hủy",
    "close": "Đóng",
    "create": "Thêm",
    "view": "Xem",
    "edit": "Sửa",
    "delete": "Xóa",
    "add": "Thêm",
    "confirm": "Xác nhận",
    "deleteAll": "Xóa tất cả",
    "deleteManyConfirm": "Xóa {{count}} bản ghi đã chọn?",
    "statusChangeManyConfirm": "Đổi trạng thái {{count}} bản ghi sang {{status}}?",
    "back": "Quay lại",
    "search": "Tìm kiếm...",
    /** Menu sort trên header cột (GenericTable) — dùng chung mọi module */
    "sortAsc": "Sắp xếp A đến Z",
    "sortDesc": "Sắp xếp Z đến A",
    /** Placeholder ô tìm trong header cột (dropdown + inline) — dùng chung mọi module */
    "columnHeaderSearchPlaceholder": "Lọc…",
    "searchPlaceholder": "Tìm kiếm . . .",
    "searchShortcut": "Tìm kiếm... (nhấn /)",
    "unknown": "Không xác định",
    /** Giá trị trống trong bảng / chi tiết (phòng ban, chức vụ chưa gán) */
    "emptyCell": "Chưa có",
    "noData": "Không có dữ liệu",
    "noResults": "Không có kết quả phù hợp.",
    "loading": "Đang tải...",
    "active": "Hoạt động",
    "inactive": "Ngừng hoạt động",
    "status": "Trạng thái",
    "actions": "Thao tác",
    "moreRowActions": "Thao tác thêm",
    "description": "Mô tả",
    "all": "Tất cả",
    "perPage": "/ trang",
    "apply": "Áp dụng",
    "reset": "Khôi phục mặc định",
    "import": "Nhập",
    "export": "Xuất",
    /** Nút xuất vô hiệu khi ma trận không cấp quyền xuất module */
    "exportNoPermission": "Bạn không có quyền xuất dữ liệu. Liên hệ quản trị để được cấp quyền Xuất trên module tương ứng.",
    "addNew": "Thêm",
    "activate": "Kích hoạt",
    "deactivate": "Tắt",
    "selected": "đã chọn",
    "selectAll": "Chọn tất cả",
    "select": "Chọn",
    "deselectAll": "Bỏ chọn tất cả",
    "clearSelection": "Xóa chọn",
    "clearFilter": "Xóa bộ lọc",
    "clearFilters": "Xóa {{count}} bộ lọc",
    "moreFilters": "Thêm bộ lọc",
    "dateRangePreset": {
      "all": "Tất cả",
      "thisWeek": "Tuần này",
      "lastWeek": "Tuần trước",
      "thisMonth": "Tháng này",
      "lastMonth": "Tháng trước",
      "thisQuarter": "Quý này",
      "lastQuarter": "Quý trước",
      "thisYear": "Năm nay",
      "lastYear": "Năm trước",
      "custom": "Tùy chọn"
    },
    "columnDisplay": "Cột hiển thị",
    "columnOptions": "Tùy chọn cột",
    "saveChanges": "Lưu",
    "cancelAction": "Hủy",
    "loadingData": "Đang tải dữ liệu",
    "processing": "Đang xử lý...",
    "finish": "Hoàn tất",
    "selectFile": "Chọn file khác",
    "allStatuses": "Tất cả trạng thái",
    "activeStatus": "Đang hoạt động",
    "inactiveStatus": "Ngừng hoạt động",
    "noDescription": "Không có mô tả",
    "error": "Đã xảy ra lỗi",
    "errorLoadData": "Không thể tải dữ liệu. Vui lòng thử lại.",
    "retry": "Thử lại",
    "firstPage": "Trang đầu",
    "prevPage": "Trang trước",
    "nextPage": "Trang sau",
    "lastPage": "Trang cuối",
    "doubleClickToPage": "Nhấn đúp để nhập trang"
  },
  "stats": {
    "columnLabel": "Tiêu đề",
    "columnValue": "Giá trị",
    "noData": "Không có dữ liệu",
    "trendVsLastPeriod": "So với kỳ trước"
  },
  "guide": {
    "buttonTitle": "Hướng dẫn",
    "modules": {
      "quanLyVietBai_baiViet": {
        "intro": "Quản lý các bài viết đã đăng: thể loại, đơn giá, nguồn và trang đăng.",
        "overview":
          "Module ghi nhận từng bài viết với liên kết thực tế, gắn thiết lập thể loại và danh mục trang đăng / nguồn đăng. Người tạo được lấy tự động từ hồ sơ nhân viên đăng nhập.",
        "permissions":
          "Theo ma trận phân quyền chức vụ: Xem danh sách, Thêm, Sửa, Xóa, Xuất. Tab \"Của tôi\" chỉ lọc giao diện theo người tạo; quyền thao tác vẫn theo module.",
        "workflow": "Thêm bài → điền thông tin → Lưu. Sửa hoặc xóa từ danh sách hoặc từ màn chi tiết. Có thể xuất Excel từ thanh công cụ.",
        "quickStart":
          "1) Vào Quản lý viết bài → Bài viết. 2) Chọn tab Tất cả hoặc Của tôi. 3) Thêm bài mới, chọn thể loại (đơn giá gợi ý theo thiết lập). 4) Lưu và kiểm tra trên danh sách.",
        "glossary":
          "Thể loại / Trang đăng / Nguồn đăng: cấu hình tại Thiết lập bài viết. Đơn giá: số tiền ghi trên từng bài (có thể khớp hoặc chỉnh so với đơn giá thể loại).",
        "faq":
          "Tại sao không thêm được bài? Kiểm tra tài khoản đã gắn nhân viên (nhan_vien_id). Làm sao chỉ xem bài của mình? Dùng tab Của tôi.",
        "contact": "Liên hệ quản trị hệ thống hoặc phòng hành chính nếu cần điều chỉnh phân quyền hoặc thiết lập danh mục.",
      },
      "quanLyGiaoViec_congViec": {
        "intro": "Theo dõi công việc được giao: mức độ, thời hạn, tiến độ theo hạn, người trách nhiệm và người hỗ trợ.",
        "overview":
          "Dữ liệu lưu trên bảng cong_viec_danh_sach (Supabase). Người tạo phiếu là người giao việc; một nhân viên trách nhiệm chính và danh sách nhân viên hỗ trợ. Cột tiến độ hiển thị theo thời hạn (còn bao nhiêu ngày, quá hạn, đã hoàn thành…), không dùng phần trăm trên danh sách.",
        "permissions":
          "Theo ma trận phân quyền module Danh sách công việc: Xem, Thêm, Sửa, Xóa, Xuất. Tab chỉ lọc giao diện (Tôi làm / Tôi hỗ trợ / Tôi giao); quyền thao tác vẫn theo module.",
        "workflow": "Thêm công việc (form: thông tin chính, không nhập trạng thái/kết quả) → Lưu. Báo cáo và đổi trạng thái từ chi tiết (nút Báo cáo). Hủy việc từ chi tiết có xác nhận. Sửa thông tin chung từ nút Sửa hoặc xóa bản ghi khi được phép.",
        "quickStart":
          "1) Vào Quản lý giao việc → Công việc. 2) Chọn tab phù hợp. 3) Thêm công việc, gán người trách nhiệm và người hỗ trợ. 4) Mở chi tiết để báo cáo kết quả / trạng thái hoặc hủy công việc.",
        "glossary":
          "Tôi làm: bạn là người trách nhiệm. Tôi hỗ trợ: bạn nằm trong danh sách hỗ trợ. Tôi giao: bạn là người tạo phiếu. Báo cáo: cập nhật trạng thái và phần kết quả (mô tả, link, ngày hoàn thành khi chọn Hoàn thành).",
        "faq":
          "Không thấy việc trên tab? Kiểm tra đúng tab và tài khoản đã gắn nhân viên (nhan_vien_id). Không thêm được? Cần quyền Thêm và hồ sơ nhân viên.",
        "contact": "Liên hệ quản trị hệ thống để gán quyền module hoặc liên kết tài khoản với hồ sơ nhân viên.",
      },
    },
  },
  "settings": {
    "primaryColor": "Màu",
    "colorBlue": "Xanh dương",
    "colorViolet": "Tím",
    "colorEmerald": "Xanh lá",
    "colorRose": "Hồng",
    "colorAmber": "Cam vàng",
    "colorOrange": "Cam",
    "colorCyan": "Xanh lơ",
    "colorSlate": "Xám"
  }
} as const;
