export const matTranNhiemKy = {
  noViewPermission: 'Bạn không có quyền xem danh sách nhiệm kỳ.',
  noEmployeeBanner: 'Tài khoản chưa gắn hồ sơ nhân viên — không thể ghi nhận người tạo bản ghi.',
  service: {
    noEmployeeProfile: 'Không xác định được nhân viên đăng nhập để ghi người tạo.',
    notFound: 'Không tìm thấy bản ghi nhiệm kỳ.',
  },
  deleteTitle: 'Xóa nhiệm kỳ?',
  deleteMessage: 'Bản ghi sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều nhiệm kỳ?',
  bulkDeleteMessage: 'Sẽ xóa {{count}} bản ghi.',
  noExportData: 'Không có dữ liệu để xuất.',
  exportFileName: 'danh-sach-nhiem-ky',
  toast: {
    create: 'Đã tạo nhiệm kỳ.',
    update: 'Đã cập nhật nhiệm kỳ.',
    delete: 'Đã xóa {{count}} bản ghi.',
    importSuccess: 'Đã nhập {{count}} nhiệm kỳ.',
  },
  import: {
    rowError: 'Dòng {{row}}: {{message}}',
    templateName: 'mau-nhap-nhiem-ky',
  },
  validation: {
    tenRequired: 'Nhập tên nhiệm kỳ.',
    yearRange: 'Năm phải là số nguyên từ 2000 đến 2100 (hoặc để trống).',
    tuDenNamOrder: 'Từ năm không được lớn hơn đến năm.',
  },
  store: {
    tenCol: 'Tên nhiệm kỳ',
    tuNamCol: 'Từ năm',
    denNamCol: 'Đến năm',
    slDangThamGiaCol: 'SL đang tham gia',
    slDauNhiemKyCol: 'SL đầu nhiệm kỳ',
    slThoiThamGiaCol: 'SL thôi tham gia',
    slCanBoSungCol: 'SL cần bổ sung',
    slThieuCol: 'SL thiếu',
    nguoiTaoCol: 'Người tạo',
    tgCapNhatCol: 'Cập nhật',
  },
  toolbar: {
    title: 'Nhiệm kỳ',
  },
  searchPlaceholder: 'Tìm theo tên, năm, ghi chú…',
  emptyTitle: 'Chưa có nhiệm kỳ',
  emptyHint: 'Thêm nhiệm kỳ mới để bắt đầu.',
  emptyFilteredHint: 'Thử xóa bộ lọc hoặc đổi từ khóa tìm kiếm.',
  form: {
    sectionMain: 'Thông tin nhiệm kỳ',
    sectionCounts: 'Số liệu',
    tenNhiemKy: 'Tên nhiệm kỳ',
    tuNam: 'Từ năm',
    denNam: 'Đến năm',
    thongTin: 'Thông tin',
    ghiChu: 'Ghi chú',
    slDauNhiemKy: 'SL đầu nhiệm kỳ',
    slDangThamGia: 'SL đang tham gia',
    slThoiThamGia: 'SL thôi tham gia',
    slCanBoSung: 'SL cần bổ sung',
    slThieu: 'SL thiếu',
    createSubtitle: 'Thêm nhiệm kỳ mới',
    editSubtitle: 'Sửa nhiệm kỳ',
  },
  detail: {
    title: 'Chi tiết nhiệm kỳ',
    sectionMain: 'Thông tin',
    sectionCounts: 'Số liệu',
    systemInfo: 'Thông tin hệ thống',
    tgTao: 'Thời điểm tạo',
    tgCapNhat: 'Cập nhật lần cuối',
  },
} as const;
